name: Docker update

inputs:
  release:
    required: true
    type: bool
  rebuild:
    required: true
    type: bool
secrets:
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to tag
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          call: ${{ inputs.rebuild && 'build' || 'call' }}
          tags: 'ghcr.io/gyselax/gyselalibxx_env:${{ github.SHA }}${{ inputs.release && ',ghcr.io/gyselax/gyselalibxx_env:latest' || ''}}'

