name: Docker update

inputs:
  rebuild:
    required: true
    type: bool
  release_tag:
    description: 'A tag for the release version'
    type: string
    required: false
    default: ''
secrets:
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build final tags
        id: get-tags
        runs: |
          import os
          sha_tag = "ghcr.io/gyselax/gyselalibxx_env:${{ github.SHA }}"
          release_tag = "ghcr.io/gyselax/gyselalibxx_env:${{ inputs.release_tag }}"
          # Build a CSV representation of the tags
          full_tags = sha_tag + ((','+release_tag) if release_tag.endswith(":") else '')
          # Save the CSV to the outputs for use in the build-push-action
          print("full_tags='", full_tags, "'", file=open(os.environ["GITHUB_OUTPUT"], sep='')
        shell: python
      - name: Build and push to tag
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          call: ${{ inputs.rebuild && 'build' || 'call' }}
          tags: ${{ steps.get-tags.outputs.full_tags }}

