name: "Get a token from a PEM file"
inputs:
  pem:
    description: "The PEM that needs to be used to generate the token"
    required: true
outputs:
  token:
    description: "The generated token"
    value: ${{ steps.token_gen.outputs.TOKEN }}

runs:
  using: "composite"
  steps:
    - name: "Generate token"
      id: token_gen
      run: |
        import jwt
        import os
        import sys
        import time
        # Get PEM file path
        # Get the Client ID
        client_id = "1132905"
        signing_key = jwt.jwk_from_pem(${{ inputs.pem }})
        # Issued at time
        # JWT expiration time (10 minutes maximum)
        # GitHub App's identifier
        payload = {'iat': int(time.time()), 'exp': int(time.time()) + 60, 'iss': client_id}
        jw_token=jwt.JWT().encode(payload, signing_key, alg='RS256')
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          fh.write(f"TOKEN={jw_token}\n")
        print("::add-mask::$TOKEN")
      shell: python
