var annotated =
[
    [ "collisions_dimensions", "namespacecollisions__dimensions.html", [
      [ "InternalSpoofGrid", "structcollisions__dimensions_1_1InternalSpoofGrid.html", null ],
      [ "InternalSpoofGridR", "structcollisions__dimensions_1_1InternalSpoofGridR.html", null ],
      [ "InternalSpoofGridTheta", "structcollisions__dimensions_1_1InternalSpoofGridTheta.html", null ],
      [ "ExtractRDim", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim", null ],
      [ "ExtractThetaDim", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim", null ],
      [ "ExtractRDim< double >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01double_01_4", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractRDim_3_01double_01_4_dup" ],
      [ "ExtractRDim< ConstField< double, IdxRange< GridR >, Kokkos::DefaultExecutionSpace::memory_space, Layout > >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01ConstField_3_01double_00_01IdxRange_3_01GridR_01d49ad374498953b7d2b9069aa134d214", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractRDim_3_01ConstField_3_01double_00_01IdxRange_3_01GridR_01d49ad374498953b7d2b9069aa134d214_dup" ],
      [ "ExtractRDim< Field< ElementType, IdxRange, MemSpace, Layout > >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01Field_3_01ElementType_00_01IdxRange_00_01MemSpace_00_01Layout_01_4_01_4", null ],
      [ "ExtractThetaDim< double, InternalSpoofGridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01double_00_01InternalSpoofGridR_01_4", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01double_00_01InternalSpoofGridR_01_4_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridR >, Kokkos::DefaultExecutionSpace::memory_space, Layout >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid4d06e1e2d0c2d7c6dba5eb3f62b8c1f6", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid4d06e1e2d0c2d7c6dba5eb3f62b8c1f6_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridTheta >, Kokkos::DefaultExecutionSpace::memory_space, Layout >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid60b078372e4f21da53e41a7105d0e223", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid60b078372e4f21da53e41a7105d0e223_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridTheta, GridR >, Kokkos::DefaultExecutionSpace::memory_space, Layout >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grida5f24db67f7287ccd8eb306d1be5d530", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grida5f24db67f7287ccd8eb306d1be5d530_dup" ],
      [ "ExtractThetaDim< Field< ElementType, IdxRange, MemSpace, Layout >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01Field_3_01ElementType_00_01IdxRange_00_01Memb61e2a7adc5523dde8976f9c0d44ef20", null ]
    ] ],
    [ "connectivity_details", null, [
      [ "PatchConnection", "structconnectivity__details_1_1PatchConnection.html", null ],
      [ "PatchConnection< Patch, ddc::detail::TypeSeq<> >", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_4_01_4.html", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_4_01_4" ],
      [ "PatchConnection< Patch, ddc::detail::TypeSeq< InterfaceType > >", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01InterfaceType_01_4_01_4.html", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01InterfaceType_01_4_01_4" ],
      [ "PatchConnection< Patch, ddc::detail::TypeSeq< InterfaceType1, RemainingInterfaceTypes... > >", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01Interd9a0a5e7aafe0b71fe7c76720b7c5da6.html", "structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01Interd9a0a5e7aafe0b71fe7c76720b7c5da6" ],
      [ "StripOutsideEdges", "structconnectivity__details_1_1StripOutsideEdges.html", null ],
      [ "StripOutsideEdges< ddc::detail::TypeSeq< EdgeType > >", "structconnectivity__details_1_1StripOutsideEdges_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType_01_4_01_4.html", "structconnectivity__details_1_1StripOutsideEdges_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType_01_4_01_4" ],
      [ "StripOutsideEdges< ddc::detail::TypeSeq< EdgeType1, RemainingEdgeTypes... > >", "structconnectivity__details_1_1StripOutsideEdges_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType1_00_036e9ce7e4506982efa52c09ca049ae90.html", "structconnectivity__details_1_1StripOutsideEdges_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType1_00_036e9ce7e4506982efa52c09ca049ae90" ],
      [ "ToTuple", "structconnectivity__details_1_1ToTuple.html", null ],
      [ "ToTuple< ddc::detail::TypeSeq< I... > >", "structconnectivity__details_1_1ToTuple_3_01ddc_1_1detail_1_1TypeSeq_3_01I_8_8_8_01_4_01_4.html", "structconnectivity__details_1_1ToTuple_3_01ddc_1_1detail_1_1TypeSeq_3_01I_8_8_8_01_4_01_4" ],
      [ "ExtractPatches", "structconnectivity__details_1_1ExtractPatches.html", null ],
      [ "ExtractPatches< ddc::detail::TypeSeq<> >", "structconnectivity__details_1_1ExtractPatches_3_01ddc_1_1detail_1_1TypeSeq_3_4_01_4.html", "structconnectivity__details_1_1ExtractPatches_3_01ddc_1_1detail_1_1TypeSeq_3_4_01_4" ],
      [ "ExtractPatches< ddc::detail::TypeSeq< EdgeType1, EdgeTypes... > >", "structconnectivity__details_1_1ExtractPatches_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType1_00_01EdgeTypes_8_8_8_01_4_01_4.html", "structconnectivity__details_1_1ExtractPatches_3_01ddc_1_1detail_1_1TypeSeq_3_01EdgeType1_00_01EdgeTypes_8_8_8_01_4_01_4" ],
      [ "FindPatch", "structconnectivity__details_1_1FindPatch.html", null ],
      [ "FindPatch< Grid1D, ddc::detail::TypeSeq<> >", "structconnectivity__details_1_1FindPatch_3_01Grid1D_00_01ddc_1_1detail_1_1TypeSeq_3_4_01_4.html", null ],
      [ "FindPatch< QueryGrid1D, ddc::detail::TypeSeq< Patch< QueryGrid1D, OGrid, BSpl1, BSpl2 >, RemainingPatchTypes... > >", "structconnectivity__details_1_1FindPatch_3_01QueryGrid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patchd8fc8921dec760f8fe4c90c2a6947228.html", "structconnectivity__details_1_1FindPatch_3_01QueryGrid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patchd8fc8921dec760f8fe4c90c2a6947228" ],
      [ "FindPatch< QueryGrid1D, ddc::detail::TypeSeq< Patch< OGrid, QueryGrid1D, BSpl1, BSpl2 >, RemainingPatchTypes... > >", "structconnectivity__details_1_1FindPatch_3_01QueryGrid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patch5f5acd76cfd59a22ebf513823679a320.html", "structconnectivity__details_1_1FindPatch_3_01QueryGrid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patch5f5acd76cfd59a22ebf513823679a320" ],
      [ "FindPatch< Grid1D, ddc::detail::TypeSeq< Patch1, RemainingPatchTypes... > >", "structconnectivity__details_1_1FindPatch_3_01Grid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patch1_00_33770856242f7c5cee1ce419b2efaf64.html", "structconnectivity__details_1_1FindPatch_3_01Grid1D_00_01ddc_1_1detail_1_1TypeSeq_3_01Patch1_00_33770856242f7c5cee1ce419b2efaf64" ],
      [ "FindInterface", "structconnectivity__details_1_1FindInterface.html", null ],
      [ "FindInterface< Edge, ddc::detail::TypeSeq<> >", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_4_01_4.html", null ],
      [ "FindInterface< Edge, ddc::detail::TypeSeq< Interface1, RemainingInterfaceTypes... > >", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfac6d31b188ee73012ad6c98be99219379f.html", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfac6d31b188ee73012ad6c98be99219379f" ],
      [ "FindInterface< Edge, ddc::detail::TypeSeq< Interface< Edge, OEdge, Orientations >, RemainingInterfaceTypes... > >", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfacd1aa547d7cc4bf022e85928246ab2d07.html", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfacd1aa547d7cc4bf022e85928246ab2d07" ],
      [ "FindInterface< Edge, ddc::detail::TypeSeq< Interface< OEdge, Edge, Orientations >, RemainingInterfaceTypes... > >", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfacee698732bdf35f06db097afe1714904c.html", "structconnectivity__details_1_1FindInterface_3_01Edge_00_01ddc_1_1detail_1_1TypeSeq_3_01Interfacee698732bdf35f06db097afe1714904c" ],
      [ "EnforceFirstInterfaceEdge", "structconnectivity__details_1_1EnforceFirstInterfaceEdge.html", null ],
      [ "EnforceFirstInterfaceEdge< Interface< FirstEdge, Edge2, Orientations >, FirstEdge >", "structconnectivity__details_1_1EnforceFirstInterfaceEdge_3_01Interface_3_01FirstEdge_00_01Edge2_788676fcb3310ca4c1ec984ff0b4531b.html", "structconnectivity__details_1_1EnforceFirstInterfaceEdge_3_01Interface_3_01FirstEdge_00_01Edge2_788676fcb3310ca4c1ec984ff0b4531b" ],
      [ "EnforceFirstInterfaceEdge< Interface< Edge2, FirstEdge, Orientations >, FirstEdge >", "structconnectivity__details_1_1EnforceFirstInterfaceEdge_3_01Interface_3_01Edge2_00_01FirstEdge_221a02b03250a49af1745b2263467420.html", "structconnectivity__details_1_1EnforceFirstInterfaceEdge_3_01Interface_3_01Edge2_00_01FirstEdge_221a02b03250a49af1745b2263467420" ],
      [ "SwapExtremity", "structconnectivity__details_1_1SwapExtremity.html", null ],
      [ "SwapExtremity< Edge< Patch, Grid1D, FRONT > >", "structconnectivity__details_1_1SwapExtremity_3_01Edge_3_01Patch_00_01Grid1D_00_01FRONT_01_4_01_4.html", "structconnectivity__details_1_1SwapExtremity_3_01Edge_3_01Patch_00_01Grid1D_00_01FRONT_01_4_01_4" ],
      [ "SwapExtremity< Edge< Patch, Grid1D, BACK > >", "structconnectivity__details_1_1SwapExtremity_3_01Edge_3_01Patch_00_01Grid1D_00_01BACK_01_4_01_4.html", "structconnectivity__details_1_1SwapExtremity_3_01Edge_3_01Patch_00_01Grid1D_00_01BACK_01_4_01_4" ],
      [ "AddToTypeSeq", "structconnectivity__details_1_1AddToTypeSeq.html", null ],
      [ "AddToTypeSeq< ToInsert, TypeSeq, FrontInsert >", "structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01FrontInsert_01_4.html", "structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01FrontInsert_01_4" ],
      [ "AddToTypeSeq< ToInsert, TypeSeq, BackInsert >", "structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01BackInsert_01_4.html", "structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01BackInsert_01_4" ],
      [ "CollectInterfacesAlongDim", "structconnectivity__details_1_1CollectInterfacesAlongDim.html", null ],
      [ "CollectInterfacesAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundInterfaces, MatchingEdge, false >", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_b2108f65f3430e895714f416a2f43701.html", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_b2108f65f3430e895714f416a2f43701" ],
      [ "CollectInterfacesAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundInterfaces, MatchingEdge, true >", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_36879d7a164b5ac728612e4a981c6d65.html", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_36879d7a164b5ac728612e4a981c6d65" ],
      [ "CollectInterfacesAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundInterfaces, OutsideEdge, false >", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_ebd86d7b2345baf351562d16964c47d9.html", "structconnectivity__details_1_1CollectInterfacesAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_ebd86d7b2345baf351562d16964c47d9" ],
      [ "CollectGridsAlongDim", "structconnectivity__details_1_1CollectGridsAlongDim.html", null ],
      [ "CollectGridsAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundGrids, MatchingEdge, false >", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01insd7a4bdb826ecb568487bbd509c5f008b.html", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01insd7a4bdb826ecb568487bbd509c5f008b" ],
      [ "CollectGridsAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundGrids, MatchingEdge, true >", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01ins8ee738c554d8fbbf6bab92ba87dd3b80.html", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01ins8ee738c554d8fbbf6bab92ba87dd3b80" ],
      [ "CollectGridsAlongDim< StartEdge, InterfaceTypeSeq, insert_pos, FoundGrids, OutsideEdge, false >", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01ins70deef724c6e45ed62db534c3d9697ec.html", "structconnectivity__details_1_1CollectGridsAlongDim_3_01StartEdge_00_01InterfaceTypeSeq_00_01ins70deef724c6e45ed62db534c3d9697ec" ],
      [ "CollectAllGridsOnDim", "structconnectivity__details_1_1CollectAllGridsOnDim.html", "structconnectivity__details_1_1CollectAllGridsOnDim" ],
      [ "CollectAllInterfacesOnDim", "structconnectivity__details_1_1CollectAllInterfacesOnDim.html", "structconnectivity__details_1_1CollectAllInterfacesOnDim" ],
      [ "SelectRelevantIdxRangeType", "structconnectivity__details_1_1SelectRelevantIdxRangeType.html", null ],
      [ "SelectRelevantIdxRangeType< QueryGrid1D, IdxRange< IdxRangeGrids... > >", "structconnectivity__details_1_1SelectRelevantIdxRangeType_3_01QueryGrid1D_00_01IdxRange_3_01IdxRangeGrids_8_8_8_01_4_01_4.html", "structconnectivity__details_1_1SelectRelevantIdxRangeType_3_01QueryGrid1D_00_01IdxRange_3_01IdxRangeGrids_8_8_8_01_4_01_4" ],
      [ "FindRelevantIdxRangeType", "structconnectivity__details_1_1FindRelevantIdxRangeType.html", null ],
      [ "FindRelevantIdxRangeType< QueryGrid1D, std::tuple<> >", "structconnectivity__details_1_1FindRelevantIdxRangeType_3_01QueryGrid1D_00_01std_1_1tuple_3_4_01_4.html", "structconnectivity__details_1_1FindRelevantIdxRangeType_3_01QueryGrid1D_00_01std_1_1tuple_3_4_01_4" ],
      [ "FindRelevantIdxRangeType< QueryGrid1D, std::tuple< IdxRangeHead, IdxRangeTypes... > >", "structconnectivity__details_1_1FindRelevantIdxRangeType_3_01QueryGrid1D_00_01std_1_1tuple_3_01Id3b131c802b30082f4412eb4689d6d53b.html", "structconnectivity__details_1_1FindRelevantIdxRangeType_3_01QueryGrid1D_00_01std_1_1tuple_3_01Id3b131c802b30082f4412eb4689d6d53b" ]
    ] ],
    [ "ddcHelper", null, [
      [ "NonUniformInterpolationPoints", "classddcHelper_1_1NonUniformInterpolationPoints.html", "classddcHelper_1_1NonUniformInterpolationPoints" ],
      [ "is_non_uniform_interpolation_points", "structddcHelper_1_1is__non__uniform__interpolation__points.html", null ],
      [ "is_non_uniform_interpolation_points< NonUniformInterpolationPoints< BSplines, BcXmin, BcXmax > >", "structddcHelper_1_1is__non__uniform__interpolation__points_3_01NonUniformInterpolationPoints_3_047d1c8570873e3c052e2e394afcf9270.html", null ]
    ] ],
    [ "figure_of_eight_5patches", null, [
      [ "X", "structfigure__of__eight__5patches_1_1X.html", null ],
      [ "Y", "structfigure__of__eight__5patches_1_1Y.html", null ],
      [ "GridX", "structfigure__of__eight__5patches_1_1GridX.html", null ],
      [ "GridY", "structfigure__of__eight__5patches_1_1GridY.html", null ],
      [ "BSplinesX", "structfigure__of__eight__5patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structfigure__of__eight__5patches_1_1BSplinesY.html", null ]
    ] ],
    [ "non_periodic_non_uniform_2d_2patches", null, [
      [ "X", "structnon__periodic__non__uniform__2d__2patches_1_1X.html", null ],
      [ "Y", "structnon__periodic__non__uniform__2d__2patches_1_1Y.html", null ],
      [ "GridX", "structnon__periodic__non__uniform__2d__2patches_1_1GridX.html", null ],
      [ "GridY", "structnon__periodic__non__uniform__2d__2patches_1_1GridY.html", null ],
      [ "BSplinesX", "structnon__periodic__non__uniform__2d__2patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structnon__periodic__non__uniform__2d__2patches_1_1BSplinesY.html", null ]
    ] ],
    [ "non_periodic_non_uniform_2d_3patches", null, [
      [ "X", "structnon__periodic__non__uniform__2d__3patches_1_1X.html", null ],
      [ "Y", "structnon__periodic__non__uniform__2d__3patches_1_1Y.html", null ],
      [ "GridX", "structnon__periodic__non__uniform__2d__3patches_1_1GridX.html", null ],
      [ "GridY", "structnon__periodic__non__uniform__2d__3patches_1_1GridY.html", null ],
      [ "BSplinesX", "structnon__periodic__non__uniform__2d__3patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structnon__periodic__non__uniform__2d__3patches_1_1BSplinesY.html", null ]
    ] ],
    [ "non_periodic_uniform_2d_2patches", null, [
      [ "X", "structnon__periodic__uniform__2d__2patches_1_1X.html", null ],
      [ "Y", "structnon__periodic__uniform__2d__2patches_1_1Y.html", null ],
      [ "GridX", "structnon__periodic__uniform__2d__2patches_1_1GridX.html", null ],
      [ "GridY", "structnon__periodic__uniform__2d__2patches_1_1GridY.html", null ],
      [ "BSplinesX", "structnon__periodic__uniform__2d__2patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structnon__periodic__uniform__2d__2patches_1_1BSplinesY.html", null ]
    ] ],
    [ "non_periodic_uniform_2d_3patches", null, [
      [ "X", "structnon__periodic__uniform__2d__3patches_1_1X.html", null ],
      [ "Y", "structnon__periodic__uniform__2d__3patches_1_1Y.html", null ],
      [ "GridX", "structnon__periodic__uniform__2d__3patches_1_1GridX.html", null ],
      [ "GridY", "structnon__periodic__uniform__2d__3patches_1_1GridY.html", null ],
      [ "BSplinesX", "structnon__periodic__uniform__2d__3patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structnon__periodic__uniform__2d__3patches_1_1BSplinesY.html", null ]
    ] ],
    [ "onion_shape_non_uniform_2d_2patches", null, [
      [ "R", "structonion__shape__non__uniform__2d__2patches_1_1R.html", null ],
      [ "Theta", "structonion__shape__non__uniform__2d__2patches_1_1Theta.html", null ],
      [ "GridR", "structonion__shape__non__uniform__2d__2patches_1_1GridR.html", null ],
      [ "GridTheta", "structonion__shape__non__uniform__2d__2patches_1_1GridTheta.html", null ],
      [ "BSplinesR", "structonion__shape__non__uniform__2d__2patches_1_1BSplinesR.html", null ],
      [ "BSplinesTheta", "structonion__shape__non__uniform__2d__2patches_1_1BSplinesTheta.html", null ]
    ] ],
    [ "onion_shape_uniform_2d_2patches", null, [
      [ "R", "structonion__shape__uniform__2d__2patches_1_1R.html", null ],
      [ "Theta", "structonion__shape__uniform__2d__2patches_1_1Theta.html", null ],
      [ "GridR", "structonion__shape__uniform__2d__2patches_1_1GridR.html", null ],
      [ "GridTheta", "structonion__shape__uniform__2d__2patches_1_1GridTheta.html", null ],
      [ "BSplinesR", "structonion__shape__uniform__2d__2patches_1_1BSplinesR.html", null ],
      [ "BSplinesTheta", "structonion__shape__uniform__2d__2patches_1_1BSplinesTheta.html", null ]
    ] ],
    [ "periodic_strips_uniform_2d_9patches", null, [
      [ "X", "structperiodic__strips__uniform__2d__9patches_1_1X.html", null ],
      [ "Y", "structperiodic__strips__uniform__2d__9patches_1_1Y.html", null ],
      [ "GridX", "structperiodic__strips__uniform__2d__9patches_1_1GridX.html", null ],
      [ "GridY", "structperiodic__strips__uniform__2d__9patches_1_1GridY.html", null ],
      [ "BSplinesX", "structperiodic__strips__uniform__2d__9patches_1_1BSplinesX.html", null ],
      [ "BSplinesY", "structperiodic__strips__uniform__2d__9patches_1_1BSplinesY.html", null ]
    ] ],
    [ "physical_geometry", null, [
      [ "X", "structphysical__geometry_1_1X.html", null ],
      [ "Y", "structphysical__geometry_1_1Y.html", null ]
    ] ],
    [ "AdvectionDomain", "classAdvectionDomain.html", "classAdvectionDomain" ],
    [ "AdvectionField", "classAdvectionField.html", "classAdvectionField" ],
    [ "AdvectionField_decentred_rotation", "classAdvectionField__decentred__rotation.html", "classAdvectionField__decentred__rotation" ],
    [ "AdvectionField_rotation", "classAdvectionField__rotation.html", "classAdvectionField__rotation" ],
    [ "AdvectionField_translation", "classAdvectionField__translation.html", "classAdvectionField__translation" ],
    [ "AdvectionFieldFinder", "classAdvectionFieldFinder.html", "classAdvectionFieldFinder" ],
    [ "AdvectionFieldSimulation", "classAdvectionFieldSimulation.html", "classAdvectionFieldSimulation" ],
    [ "AdvectionPhysicalDomain", "classAdvectionPhysicalDomain.html", "classAdvectionPhysicalDomain" ],
    [ "AdvectionPseudoCartesianDomain", "classAdvectionPseudoCartesianDomain.html", "classAdvectionPseudoCartesianDomain" ],
    [ "AdvectionSimulation", "classAdvectionSimulation.html", "classAdvectionSimulation" ],
    [ "BernsteinPolynomialBasis", "classBernsteinPolynomialBasis.html", "classBernsteinPolynomialBasis" ],
    [ "BslAdvection1D", "classBslAdvection1D.html", "classBslAdvection1D" ],
    [ "BslAdvectionRTheta", "classBslAdvectionRTheta.html", "classBslAdvectionRTheta" ],
    [ "BslAdvectionSpatial", "classBslAdvectionSpatial.html", "classBslAdvectionSpatial" ],
    [ "BslAdvectionVelocity", "classBslAdvectionVelocity.html", "classBslAdvectionVelocity" ],
    [ "BslExplicitPredCorrRTheta", "classBslExplicitPredCorrRTheta.html", "classBslExplicitPredCorrRTheta" ],
    [ "BslImplicitPredCorrRTheta", "classBslImplicitPredCorrRTheta.html", "classBslImplicitPredCorrRTheta" ],
    [ "BslPredCorrRTheta", "classBslPredCorrRTheta.html", "classBslPredCorrRTheta" ],
    [ "BSplinesMu", "structBSplinesMu.html", null ],
    [ "BSplinesR", "structBSplinesR.html", null ],
    [ "BSplinesTheta", "structBSplinesTheta.html", null ],
    [ "BSplinesVpar", "structBSplinesVpar.html", null ],
    [ "BSplinesVx", "structBSplinesVx.html", null ],
    [ "BSplinesVy", "structBSplinesVy.html", null ],
    [ "BSplinesX", "structBSplinesX.html", null ],
    [ "BSplinesY", "structBSplinesY.html", null ],
    [ "BumpontailEquilibrium", "classBumpontailEquilibrium.html", "classBumpontailEquilibrium" ],
    [ "cartesian_product_impl", "structcartesian__product__impl.html", null ],
    [ "cartesian_product_impl< std::tuple< std::tuple< HeadArgs... >, TailTuples... >, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_01std_1_1tuple_3_01HeadArgs_8_8_8_01_4_00_01Ta2e54ffdefaa524ceede7a120148cdbe5.html", null ],
    [ "cartesian_product_impl< std::tuple<>, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4.html", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4" ],
    [ "CartesianSolution", "classCartesianSolution.html", "classCartesianSolution" ],
    [ "CartesianToBarycentricCoordinates", "classCartesianToBarycentricCoordinates.html", "classCartesianToBarycentricCoordinates" ],
    [ "ChargeDensityCalculator", "classChargeDensityCalculator.html", "classChargeDensityCalculator" ],
    [ "ChargeExchangeRate", "classChargeExchangeRate.html", "classChargeExchangeRate" ],
    [ "CircularToCartesian", "classCircularToCartesian.html", "classCircularToCartesian" ],
    [ "CollisionInfo", "classCollisionInfo.html", "classCollisionInfo" ],
    [ "CollisionInfoRadial", "classCollisionInfoRadial.html", "classCollisionInfoRadial" ],
    [ "CollisionsInter", "classCollisionsInter.html", "classCollisionsInter" ],
    [ "CollisionsIntra", "classCollisionsIntra.html", "classCollisionsIntra" ],
    [ "CollisionSpVparMu", "classCollisionSpVparMu.html", "classCollisionSpVparMu" ],
    [ "ConstantExtrapolationRuleOnion", "structConstantExtrapolationRuleOnion.html", "structConstantExtrapolationRuleOnion" ],
    [ "ConstantFluidInitialization", "classConstantFluidInitialization.html", "classConstantFluidInitialization" ],
    [ "ConstantRate", "classConstantRate.html", "classConstantRate" ],
    [ "CoordinateConverter", "classCoordinateConverter.html", "classCoordinateConverter" ],
    [ "CosineEvaluator", "structCosineEvaluator.html", [
      [ "Evaluator", "classCosineEvaluator_1_1Evaluator.html", "classCosineEvaluator_1_1Evaluator" ]
    ] ],
    [ "CrankNicolson", "classCrankNicolson.html", "classCrankNicolson" ],
    [ "Curvilinear2DToCartesian", "classCurvilinear2DToCartesian.html", "classCurvilinear2DToCartesian" ],
    [ "CurvilinearSolution", "classCurvilinearSolution.html", "classCurvilinearSolution" ],
    [ "CzarnyToCartesian", "classCzarnyToCartesian.html", "classCzarnyToCartesian" ],
    [ "DecentredRotationAdvectionFieldSimulation", "classDecentredRotationAdvectionFieldSimulation.html", "classDecentredRotationAdvectionFieldSimulation" ],
    [ "DecentredRotationSimulation", "classDecentredRotationSimulation.html", "classDecentredRotationSimulation" ],
    [ "DerivField", "classDerivField.html", null ],
    [ "DerivField< ElementType, IdxRange< DDims... >, MemorySpace, LayoutStridedPolicy >", "classDerivField_3_01ElementType_00_01IdxRange_3_01DDims_8_8_8_01_4_00_01MemorySpace_00_01LayoutStridedPolicy_01_4.html", "classDerivField_3_01ElementType_00_01IdxRange_3_01DDims_8_8_8_01_4_00_01MemorySpace_00_01LayoutStridedPolicy_01_4" ],
    [ "DerivFieldCommon", "classDerivFieldCommon.html", null ],
    [ "DerivFieldCommon< FieldType, IdxRange< DDims... > >", "classDerivFieldCommon_3_01FieldType_00_01IdxRange_3_01DDims_8_8_8_01_4_01_4.html", "classDerivFieldCommon_3_01FieldType_00_01IdxRange_3_01DDims_8_8_8_01_4_01_4" ],
    [ "DerivFieldMem", "classDerivFieldMem.html", null ],
    [ "DerivFieldMem< ElementType, IdxRange< DDims... >, NDerivs, MemSpace >", "classDerivFieldMem_3_01ElementType_00_01IdxRange_3_01DDims_8_8_8_01_4_00_01NDerivs_00_01MemSpace_01_4.html", "classDerivFieldMem_3_01ElementType_00_01IdxRange_3_01DDims_8_8_8_01_4_00_01NDerivs_00_01MemSpace_01_4" ],
    [ "DiffusiveNeutralSolver", "classDiffusiveNeutralSolver.html", "classDiffusiveNeutralSolver" ],
    [ "DimX_pC", "structDimX__pC.html", null ],
    [ "DimY_pC", "structDimY__pC.html", null ],
    [ "DiocotronDensitySolution", "classDiocotronDensitySolution.html", "classDiocotronDensitySolution" ],
    [ "DiscreteToCartesian", "classDiscreteToCartesian.html", "classDiscreteToCartesian" ],
    [ "DiscreteToCartesianBuilder", "classDiscreteToCartesianBuilder.html", "classDiscreteToCartesianBuilder" ],
    [ "Edge", "structEdge.html", "structEdge" ],
    [ "EdgeTransformation", "classEdgeTransformation.html", "classEdgeTransformation" ],
    [ "ElectrostaticalPotentialSimulation", "classElectrostaticalPotentialSimulation.html", "classElectrostaticalPotentialSimulation" ],
    [ "ElectrostaticalPotentialSimulation_decentred_rotation", "classElectrostaticalPotentialSimulation__decentred__rotation.html", "classElectrostaticalPotentialSimulation__decentred__rotation" ],
    [ "ElectrostaticalPotentialSimulation_rotation", "classElectrostaticalPotentialSimulation__rotation.html", "classElectrostaticalPotentialSimulation__rotation" ],
    [ "ElectrostaticalPotentialSimulation_translation", "classElectrostaticalPotentialSimulation__translation.html", "classElectrostaticalPotentialSimulation__translation" ],
    [ "Euler", "classEuler.html", "classEuler" ],
    [ "Evaluator2D", "structEvaluator2D.html", [
      [ "Evaluator", "classEvaluator2D_1_1Evaluator.html", "classEvaluator2D_1_1Evaluator" ]
    ] ],
    [ "FEM1DPoissonSolver", "classFEM1DPoissonSolver.html", "classFEM1DPoissonSolver" ],
    [ "FFTPoissonSolver", "classFFTPoissonSolver.html", null ],
    [ "FFTPoissonSolver< IdxRange< GridPDEDim1D... >, IdxRangeFull, ExecSpace, LayoutSpace >", "classFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace_00_01LayoutSpace_01_4.html", "classFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace_00_01LayoutSpace_01_4" ],
    [ "FluidMoments", "classFluidMoments.html", "classFluidMoments" ],
    [ "for_each_tuple_cat", "structfor__each__tuple__cat.html", null ],
    [ "for_each_tuple_cat< std::tuple< Tuples... >, Tuple >", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4.html", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4" ],
    [ "FunctionToBeAdvected", "classFunctionToBeAdvected.html", "classFunctionToBeAdvected" ],
    [ "FunctionToBeAdvected_cos_4_elipse", "classFunctionToBeAdvected__cos__4__elipse.html", "classFunctionToBeAdvected__cos__4__elipse" ],
    [ "FunctionToBeAdvected_gaussian", "classFunctionToBeAdvected__gaussian.html", "classFunctionToBeAdvected__gaussian" ],
    [ "GaussLegendre", "classGaussLegendre.html", "classGaussLegendre" ],
    [ "GaussLegendreCoefficients", "structGaussLegendreCoefficients.html", null ],
    [ "GeometryXVx", "classGeometryXVx.html", "classGeometryXVx" ],
    [ "GeometryXYVxVy", "classGeometryXYVxVy.html", "classGeometryXYVxVy" ],
    [ "GridBuilder", "classGridBuilder.html", "classGridBuilder" ],
    [ "GridMom", "structGridMom.html", null ],
    [ "GridMu", "structGridMu.html", null ],
    [ "GridR", "structGridR.html", null ],
    [ "GridTheta", "structGridTheta.html", null ],
    [ "GridTor1", "structGridTor1.html", null ],
    [ "GridTor2", "structGridTor2.html", null ],
    [ "GridTor3", "structGridTor3.html", null ],
    [ "GridVpar", "structGridVpar.html", null ],
    [ "GridVx", "structGridVx.html", null ],
    [ "GridVy", "structGridVy.html", null ],
    [ "GridX", "structGridX.html", null ],
    [ "GridY", "structGridY.html", null ],
    [ "IAdvectionRTheta", "classIAdvectionRTheta.html", "classIAdvectionRTheta" ],
    [ "IAdvectionSpatial", "classIAdvectionSpatial.html", "classIAdvectionSpatial" ],
    [ "IAdvectionVelocity", "classIAdvectionVelocity.html", "classIAdvectionVelocity" ],
    [ "IBoltzmannSolver", "classIBoltzmannSolver.html", "classIBoltzmannSolver" ],
    [ "IChargeDensityCalculator", "classIChargeDensityCalculator.html", "classIChargeDensityCalculator" ],
    [ "IdxRangeSlice", "classIdxRangeSlice.html", "classIdxRangeSlice" ],
    [ "IdxRangeSliceIterator", "structIdxRangeSliceIterator.html", "structIdxRangeSliceIterator" ],
    [ "IdxRangeToSlice", "structIdxRangeToSlice.html", null ],
    [ "IEquilibrium", "classIEquilibrium.html", "classIEquilibrium" ],
    [ "IFluidInitialization", "classIFluidInitialization.html", "classIFluidInitialization" ],
    [ "IFluidTransportSolver", "classIFluidTransportSolver.html", "classIFluidTransportSolver" ],
    [ "IFootFinder", "classIFootFinder.html", "classIFootFinder" ],
    [ "IInitialization", "classIInitialization.html", "classIInitialization" ],
    [ "IInterpolator", "classIInterpolator.html", "classIInterpolator" ],
    [ "IInterpolatorRTheta", "classIInterpolatorRTheta.html", "classIInterpolatorRTheta" ],
    [ "IKineticFluidCoupling", "classIKineticFluidCoupling.html", "classIKineticFluidCoupling" ],
    [ "IMPILayout", "classIMPILayout.html", "classIMPILayout" ],
    [ "IMPITranspose", "classIMPITranspose.html", "classIMPITranspose" ],
    [ "Interface", "structInterface.html", "structInterface" ],
    [ "interpolator_on_idx_range", "structinterpolator__on__idx__range.html", null ],
    [ "interpolator_on_idx_range< Interp, GridInterp, IdxRange< Grid1D... > >", "structinterpolator__on__idx__range_3_01Interp_00_01GridInterp_00_01IdxRange_3_01Grid1D_8_8_8_01_4_01_4.html", "structinterpolator__on__idx__range_3_01Interp_00_01GridInterp_00_01IdxRange_3_01Grid1D_8_8_8_01_4_01_4" ],
    [ "IonizationRate", "classIonizationRate.html", "classIonizationRate" ],
    [ "IPoissonSolver", "classIPoissonSolver.html", null ],
    [ "IPoissonSolver< IdxRange< ODims... >, IdxRangeFull, MemorySpace, LayoutSpace >", "classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01MemorySpace_00_01LayoutSpace_01_4.html", "classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01MemorySpace_00_01LayoutSpace_01_4" ],
    [ "IPreallocatableInterpolator", "classIPreallocatableInterpolator.html", "classIPreallocatableInterpolator" ],
    [ "IPreallocatableInterpolatorRTheta", "classIPreallocatableInterpolatorRTheta.html", "classIPreallocatableInterpolatorRTheta" ],
    [ "IQNSolver", "classIQNSolver.html", "classIQNSolver" ],
    [ "IReactionRate", "classIReactionRate.html", "classIReactionRate" ],
    [ "IRightHandSide", "classIRightHandSide.html", "classIRightHandSide" ],
    [ "is_onion_patch_locator", "structis__onion__patch__locator.html", null ],
    [ "is_onion_patch_locator< OnionPatchLocator< MultipatchIdxRanges, Mapping, ExecSpace > >", "structis__onion__patch__locator_3_01OnionPatchLocator_3_01MultipatchIdxRanges_00_01Mapping_00_01ExecSpace_01_4_01_4.html", null ],
    [ "is_subidx_range_collection", "structis__subidx__range__collection.html", null ],
    [ "is_subidx_range_collection< IdxRangeSlice< Tags... > >", "structis__subidx__range__collection_3_01IdxRangeSlice_3_01Tags_8_8_8_01_4_01_4.html", null ],
    [ "ITimeSolver", "classITimeSolver.html", "classITimeSolver" ],
    [ "ITimeSolverHybrid", "classITimeSolverHybrid.html", "classITimeSolverHybrid" ],
    [ "ITimeSolverRTheta", "classITimeSolverRTheta.html", "classITimeSolverRTheta" ],
    [ "ITimeStepper", "classITimeStepper.html", "classITimeStepper" ],
    [ "IVlasovSolver", "classIVlasovSolver.html", "classIVlasovSolver" ],
    [ "Jacobian", "classJacobian.html", "classJacobian" ],
    [ "KelvinHelmholtzInstabilityInitialization", "classKelvinHelmholtzInstabilityInitialization.html", "classKelvinHelmholtzInstabilityInitialization" ],
    [ "KineticFluidCouplingSource", "classKineticFluidCouplingSource.html", "classKineticFluidCouplingSource" ],
    [ "KineticSource", "classKineticSource.html", "classKineticSource" ],
    [ "KrookSourceAdaptive", "classKrookSourceAdaptive.html", "classKrookSourceAdaptive" ],
    [ "KrookSourceConstant", "classKrookSourceConstant.html", "classKrookSourceConstant" ],
    [ "Lagrange", "classLagrange.html", "classLagrange" ],
    [ "LagrangeInterpolator", "classLagrangeInterpolator.html", "classLagrangeInterpolator" ],
    [ "ManufacturedPoissonTest", "classManufacturedPoissonTest.html", "classManufacturedPoissonTest" ],
    [ "MatchingIdxSlice", "classMatchingIdxSlice.html", "classMatchingIdxSlice" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "Matrix_Banded", "classMatrix__Banded.html", "classMatrix__Banded" ],
    [ "Matrix_Center_Block", "classMatrix__Center__Block.html", "classMatrix__Center__Block" ],
    [ "Matrix_Corner_Block", "classMatrix__Corner__Block.html", "classMatrix__Corner__Block" ],
    [ "Matrix_Dense", "classMatrix__Dense.html", "classMatrix__Dense" ],
    [ "Matrix_PDS_Tridiag", "classMatrix__PDS__Tridiag.html", "classMatrix__PDS__Tridiag" ],
    [ "Matrix_Periodic_Banded", "classMatrix__Periodic__Banded.html", "classMatrix__Periodic__Banded" ],
    [ "MatrixBatch", "classMatrixBatch.html", "classMatrixBatch" ],
    [ "MatrixBatchCsr", "classMatrixBatchCsr.html", "classMatrixBatchCsr" ],
    [ "MatrixBatchEll", "classMatrixBatchEll.html", "classMatrixBatchEll" ],
    [ "MatrixBatchTridiag", "classMatrixBatchTridiag.html", "classMatrixBatchTridiag" ],
    [ "MaxwellianEquilibrium", "classMaxwellianEquilibrium.html", "classMaxwellianEquilibrium" ],
    [ "MetricTensor", "classMetricTensor.html", "classMetricTensor" ],
    [ "Moments", "classMoments.html", "classMoments" ],
    [ "MPIDim", "structMPIDim.html", "structMPIDim" ],
    [ "MPILayout", "classMPILayout.html", "classMPILayout" ],
    [ "MPITransposeAllToAll", "classMPITransposeAllToAll.html", "classMPITransposeAllToAll" ],
    [ "Mu", "structMu.html", null ],
    [ "MultipatchConnectivity", "classMultipatchConnectivity.html", "classMultipatchConnectivity" ],
    [ "MultipatchField", "classMultipatchField.html", "classMultipatchField" ],
    [ "MultipatchFieldMem", "classMultipatchFieldMem.html", "classMultipatchFieldMem" ],
    [ "MultipatchSplineBuilder", "classMultipatchSplineBuilder.html", "classMultipatchSplineBuilder" ],
    [ "MultipatchSplineBuilder2D", "classMultipatchSplineBuilder2D.html", "classMultipatchSplineBuilder2D" ],
    [ "MultipatchSplineEvaluator2D", "classMultipatchSplineEvaluator2D.html", "classMultipatchSplineEvaluator2D" ],
    [ "MultipatchSplineOnionShapeTest", "classMultipatchSplineOnionShapeTest.html", "classMultipatchSplineOnionShapeTest" ],
    [ "MultipatchType", "classMultipatchType.html", "classMultipatchType" ],
    [ "NonAnalyticalJacobian", "classNonAnalyticalJacobian.html", "classNonAnalyticalJacobian" ],
    [ "NoPerturbInitialization", "classNoPerturbInitialization.html", "classNoPerturbInitialization" ],
    [ "NullAdvectionVelocity", "classNullAdvectionVelocity.html", "classNullAdvectionVelocity" ],
    [ "NullExtrapolationRule", "structNullExtrapolationRule.html", "structNullExtrapolationRule" ],
    [ "NullFluidSolver", "classNullFluidSolver.html", "classNullFluidSolver" ],
    [ "NullQNSolver", "classNullQNSolver.html", "classNullQNSolver" ],
    [ "OnionPatchLocator", "classOnionPatchLocator.html", null ],
    [ "OnionPatchLocator< MultipatchType< IdxRangeOnPatch, Patches... >, Mapping, ExecSpace >", "classOnionPatchLocator_3_01MultipatchType_3_01IdxRangeOnPatch_00_01Patches_8_8_8_01_4_00_01Mapping_00_01ExecSpace_01_4.html", "classOnionPatchLocator_3_01MultipatchType_3_01IdxRangeOnPatch_00_01Patches_8_8_8_01_4_00_01Mapping_00_01ExecSpace_01_4" ],
    [ "OutsideEdge", "structOutsideEdge.html", null ],
    [ "Patch", "structPatch.html", null ],
    [ "Patch< grid1, grid2, bsplines_dim1, bsplines_dim2 >", "structPatch_3_01grid1_00_01grid2_00_01bsplines__dim1_00_01bsplines__dim2_01_4.html", "structPatch_3_01grid1_00_01grid2_00_01bsplines__dim1_00_01bsplines__dim2_01_4" ],
    [ "PoissonLikeRHSFunction", "classPoissonLikeRHSFunction.html", "classPoissonLikeRHSFunction" ],
    [ "PoissonSolution", "classPoissonSolution.html", "classPoissonSolution" ],
    [ "PolarBSplines", "classPolarBSplines.html", "classPolarBSplines" ],
    [ "PolarBSplinesRTheta", "structPolarBSplinesRTheta.html", null ],
    [ "PolarSpline", "structPolarSpline.html", "structPolarSpline" ],
    [ "PolarSplineEvaluator", "classPolarSplineEvaluator.html", "classPolarSplineEvaluator" ],
    [ "PolarSplineFEMPoissonLikeSolver", "classPolarSplineFEMPoissonLikeSolver.html", "classPolarSplineFEMPoissonLikeSolver" ],
    [ "PolarSplineSpan", "structPolarSplineSpan.html", "structPolarSplineSpan" ],
    [ "PolarSplineView", "structPolarSplineView.html", "structPolarSplineView" ],
    [ "PolynomialEvaluator", "structPolynomialEvaluator.html", [
      [ "Evaluator", "classPolynomialEvaluator_1_1Evaluator.html", "classPolynomialEvaluator_1_1Evaluator" ]
    ] ],
    [ "PreallocatableLagrangeInterpolator", "classPreallocatableLagrangeInterpolator.html", "classPreallocatableLagrangeInterpolator" ],
    [ "PreallocatableSplineInterpolator", "classPreallocatableSplineInterpolator.html", "classPreallocatableSplineInterpolator" ],
    [ "PreallocatableSplineInterpolatorRTheta", "classPreallocatableSplineInterpolatorRTheta.html", "classPreallocatableSplineInterpolatorRTheta" ],
    [ "PredCorr", "classPredCorr.html", "classPredCorr" ],
    [ "PredCorrHybrid", "classPredCorrHybrid.html", "classPredCorrHybrid" ],
    [ "PredCorrRK2XY", "classPredCorrRK2XY.html", "classPredCorrRK2XY" ],
    [ "PseudoCartesianCompatibleMapping", "classPseudoCartesianCompatibleMapping.html", "classPseudoCartesianCompatibleMapping" ],
    [ "QNSolver", "classQNSolver.html", "classQNSolver" ],
    [ "Quadrature", "classQuadrature.html", "classQuadrature" ],
    [ "R", "structR.html", null ],
    [ "RecombinationRate", "classRecombinationRate.html", "classRecombinationRate" ],
    [ "RefinedDiscreteToCartesianBuilder", "classRefinedDiscreteToCartesianBuilder.html", "classRefinedDiscreteToCartesianBuilder" ],
    [ "RestartInitialization", "classRestartInitialization.html", "classRestartInitialization" ],
    [ "RK2", "classRK2.html", "classRK2" ],
    [ "RK3", "classRK3.html", "classRK3" ],
    [ "RK4", "classRK4.html", "classRK4" ],
    [ "RotationAdvectionFieldSimulation", "classRotationAdvectionFieldSimulation.html", "classRotationAdvectionFieldSimulation" ],
    [ "RotationSimulation", "classRotationSimulation.html", "classRotationSimulation" ],
    [ "SingleModePerturbInitialization", "classSingleModePerturbInitialization.html", "classSingleModePerturbInitialization" ],
    [ "Species", "structSpecies.html", null ],
    [ "SpeciesInformation", "classSpeciesInformation.html", "classSpeciesInformation" ],
    [ "SplineFootFinder", "classSplineFootFinder.html", "classSplineFootFinder" ],
    [ "SplineInterpolator", "classSplineInterpolator.html", "classSplineInterpolator" ],
    [ "SplineInterpolatorRTheta", "classSplineInterpolatorRTheta.html", "classSplineInterpolatorRTheta" ],
    [ "SplitRightHandSideSolver", "classSplitRightHandSideSolver.html", "classSplitRightHandSideSolver" ],
    [ "SplitVlasovSolver", "classSplitVlasovSolver.html", "classSplitVlasovSolver" ],
    [ "T", "structT.html", null ],
    [ "Theta", "structTheta.html", null ],
    [ "to_tuple", "structto__tuple.html", "structto__tuple" ],
    [ "to_tuple< std::integer_sequence< T, Ints... > >", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4.html", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4" ],
    [ "to_tuple< std::pair< T, U > >", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4" ],
    [ "Tor1", "structTor1.html", null ],
    [ "Tor2", "structTor2.html", null ],
    [ "Tor3", "structTor3.html", null ],
    [ "TranslationAdvectionFieldSimulation", "classTranslationAdvectionFieldSimulation.html", "classTranslationAdvectionFieldSimulation" ],
    [ "TranslationSimulation", "classTranslationSimulation.html", "classTranslationSimulation" ],
    [ "tuple_to_types", "structtuple__to__types.html", "structtuple__to__types" ],
    [ "tuple_to_types< std::tuple< Args... > >", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4" ],
    [ "VectorField", "classVectorField.html", "classVectorField" ],
    [ "VectorFieldCommon", "classVectorFieldCommon.html", null ],
    [ "VectorFieldMem", "classVectorFieldMem.html", "classVectorFieldMem" ],
    [ "VortexMergerDensitySolution", "classVortexMergerDensitySolution.html", "classVortexMergerDensitySolution" ],
    [ "VortexMergerEquilibria", "classVortexMergerEquilibria.html", "classVortexMergerEquilibria" ],
    [ "Vpar", "structVpar.html", null ],
    [ "Vr", "structVr.html", null ],
    [ "Vtheta", "structVtheta.html", null ],
    [ "Vx", "structVx.html", null ],
    [ "Vy", "structVy.html", null ],
    [ "X", "structX.html", null ],
    [ "Y", "structY.html", null ]
];