var annotated =
[
    [ "collisions_dimensions", "namespacecollisions__dimensions.html", [
      [ "InternalSpoofGrid", "structcollisions__dimensions_1_1InternalSpoofGrid.html", null ],
      [ "InternalSpoofGridR", "structcollisions__dimensions_1_1InternalSpoofGridR.html", null ],
      [ "InternalSpoofGridTheta", "structcollisions__dimensions_1_1InternalSpoofGridTheta.html", null ],
      [ "ExtractRDim", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim", null ],
      [ "ExtractThetaDim", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim", null ],
      [ "ExtractRDim< double >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01double_01_4", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractRDim_3_01double_01_4_dup" ],
      [ "ExtractRDim< ConstField< double, IdxRange< GridR >, Layout, Kokkos::DefaultExecutionSpace::memory_space > >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01ConstField_3_01double_00_01IdxRange_3_01GridR_01e5eec9867dc0367509479a78f691ed0d", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractRDim_3_01ConstField_3_01double_00_01IdxRange_3_01GridR_01e5eec9867dc0367509479a78f691ed0d_dup" ],
      [ "ExtractRDim< Field< ElementType, IdxRange, Layout, MemSpace > >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractRDim_3_01Field_3_01ElementType_00_01IdxRange_00_01Layout_00_01MemSpace_01_4_01_4", null ],
      [ "ExtractThetaDim< double, InternalSpoofGridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01double_00_01InternalSpoofGridR_01_4", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01double_00_01InternalSpoofGridR_01_4_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridR >, Layout, Kokkos::DefaultExecutionSpace::memory_space >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Gridefb14dd7b92083f6c86f080a59b9ace4", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Gridefb14dd7b92083f6c86f080a59b9ace4_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridTheta >, Layout, Kokkos::DefaultExecutionSpace::memory_space >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid60f8483db1988437fdeb2a198e9fb77b", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid60f8483db1988437fdeb2a198e9fb77b_dup" ],
      [ "ExtractThetaDim< ConstField< double, IdxRange< GridTheta, GridR >, Layout, Kokkos::DefaultExecutionSpace::memory_space >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid57b262a660e92e54969d1eee8b470fb5", "namespacecollisions__dimensions_structcollisions__dimensions_1_1ExtractThetaDim_3_01ConstField_3_01double_00_01IdxRange_3_01Grid57b262a660e92e54969d1eee8b470fb5_dup" ],
      [ "ExtractThetaDim< Field< ElementType, IdxRange, Layout, MemSpace >, GridR >", "namespacecollisions__dimensions.html#structcollisions__dimensions_1_1ExtractThetaDim_3_01Field_3_01ElementType_00_01IdxRange_00_01Lay7ee29cfb5ae685a651db9670325b8a2b", null ]
    ] ],
    [ "AdvectionDomain", "classAdvectionDomain.html", "classAdvectionDomain" ],
    [ "AdvectionField", "classAdvectionField.html", "classAdvectionField" ],
    [ "AdvectionField_decentred_rotation", "classAdvectionField__decentred__rotation.html", "classAdvectionField__decentred__rotation" ],
    [ "AdvectionField_rotation", "classAdvectionField__rotation.html", "classAdvectionField__rotation" ],
    [ "AdvectionField_translation", "classAdvectionField__translation.html", "classAdvectionField__translation" ],
    [ "AdvectionFieldFinder", "classAdvectionFieldFinder.html", "classAdvectionFieldFinder" ],
    [ "AdvectionFieldSimulation", "classAdvectionFieldSimulation.html", "classAdvectionFieldSimulation" ],
    [ "AdvectionPhysicalDomain", "classAdvectionPhysicalDomain.html", "classAdvectionPhysicalDomain" ],
    [ "AdvectionPseudoCartesianDomain", "classAdvectionPseudoCartesianDomain.html", "classAdvectionPseudoCartesianDomain" ],
    [ "AdvectionSimulation", "classAdvectionSimulation.html", "classAdvectionSimulation" ],
    [ "AnalyticalInvertibleCurvilinear2DToCartesian", "classAnalyticalInvertibleCurvilinear2DToCartesian.html", "classAnalyticalInvertibleCurvilinear2DToCartesian" ],
    [ "BernsteinPolynomialBasis", "classBernsteinPolynomialBasis.html", "classBernsteinPolynomialBasis" ],
    [ "BslAdvection1D", "classBslAdvection1D.html", "classBslAdvection1D" ],
    [ "BslAdvectionRTheta", "classBslAdvectionRTheta.html", "classBslAdvectionRTheta" ],
    [ "BslAdvectionSpatial", "classBslAdvectionSpatial.html", "classBslAdvectionSpatial" ],
    [ "BslAdvectionVelocity", "classBslAdvectionVelocity.html", "classBslAdvectionVelocity" ],
    [ "BslExplicitPredCorrRTheta", "classBslExplicitPredCorrRTheta.html", "classBslExplicitPredCorrRTheta" ],
    [ "BslImplicitPredCorrRTheta", "classBslImplicitPredCorrRTheta.html", "classBslImplicitPredCorrRTheta" ],
    [ "BslPredCorrRTheta", "classBslPredCorrRTheta.html", "classBslPredCorrRTheta" ],
    [ "BSplinesMu", "structBSplinesMu.html", null ],
    [ "BSplinesP1", "structBSplinesP1.html", null ],
    [ "BSplinesP2", "structBSplinesP2.html", null ],
    [ "BSplinesR", "structBSplinesR.html", null ],
    [ "BSplinesR1", "structBSplinesR1.html", null ],
    [ "BSplinesR2", "structBSplinesR2.html", null ],
    [ "BSplinesTheta", "structBSplinesTheta.html", null ],
    [ "BSplinesVpar", "structBSplinesVpar.html", null ],
    [ "BSplinesVx", "structBSplinesVx.html", null ],
    [ "BSplinesVy", "structBSplinesVy.html", null ],
    [ "BSplinesX", "structBSplinesX.html", null ],
    [ "BSplinesX1", "structBSplinesX1.html", null ],
    [ "BSplinesX2", "structBSplinesX2.html", null ],
    [ "BSplinesY", "structBSplinesY.html", null ],
    [ "BSplinesY1", "structBSplinesY1.html", null ],
    [ "BSplinesY2", "structBSplinesY2.html", null ],
    [ "BumpontailEquilibrium", "classBumpontailEquilibrium.html", "classBumpontailEquilibrium" ],
    [ "cartesian_product_impl", "structcartesian__product__impl.html", null ],
    [ "cartesian_product_impl< std::tuple< std::tuple< HeadArgs... >, TailTuples... >, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_01std_1_1tuple_3_01HeadArgs_8_8_8_01_4_00_01Ta2e54ffdefaa524ceede7a120148cdbe5.html", null ],
    [ "cartesian_product_impl< std::tuple<>, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4.html", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4" ],
    [ "CartesianSolution", "classCartesianSolution.html", "classCartesianSolution" ],
    [ "CartesianToBarycentricCoordinates", "classCartesianToBarycentricCoordinates.html", "classCartesianToBarycentricCoordinates" ],
    [ "ChargeDensityCalculator", "classChargeDensityCalculator.html", "classChargeDensityCalculator" ],
    [ "ChargeExchangeRate", "classChargeExchangeRate.html", "classChargeExchangeRate" ],
    [ "CircularToCartesian", "classCircularToCartesian.html", "classCircularToCartesian" ],
    [ "CollisionInfo", "classCollisionInfo.html", "classCollisionInfo" ],
    [ "CollisionInfoRadial", "classCollisionInfoRadial.html", "classCollisionInfoRadial" ],
    [ "CollisionsInter", "classCollisionsInter.html", "classCollisionsInter" ],
    [ "CollisionsIntra", "classCollisionsIntra.html", "classCollisionsIntra" ],
    [ "CollisionSpVparMu", "classCollisionSpVparMu.html", "classCollisionSpVparMu" ],
    [ "ConstantFluidInitialization", "classConstantFluidInitialization.html", "classConstantFluidInitialization" ],
    [ "ConstantRate", "classConstantRate.html", "classConstantRate" ],
    [ "CosineEvaluator", "structCosineEvaluator.html", [
      [ "Evaluator", "classCosineEvaluator_1_1Evaluator.html", "classCosineEvaluator_1_1Evaluator" ]
    ] ],
    [ "CrankNicolson", "classCrankNicolson.html", "classCrankNicolson" ],
    [ "Curvilinear2DToCartesian", "classCurvilinear2DToCartesian.html", "classCurvilinear2DToCartesian" ],
    [ "CurvilinearSolution", "classCurvilinearSolution.html", "classCurvilinearSolution" ],
    [ "CzarnyToCartesian", "classCzarnyToCartesian.html", "classCzarnyToCartesian" ],
    [ "DecentredRotationAdvectionFieldSimulation", "classDecentredRotationAdvectionFieldSimulation.html", "classDecentredRotationAdvectionFieldSimulation" ],
    [ "DecentredRotationSimulation", "classDecentredRotationSimulation.html", "classDecentredRotationSimulation" ],
    [ "DerivField", "classDerivField.html", null ],
    [ "DerivField< ElementType, ddc::DiscreteDomain< DDims... >, NDerivs, Allocator >", "classDerivField_3_01ElementType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01NDerivs_00_01Allocator_01_4.html", "classDerivField_3_01ElementType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01NDerivs_00_01Allocator_01_4" ],
    [ "DerivFieldCommon", "classDerivFieldCommon.html", null ],
    [ "DerivFieldCommon< ChunkType, ddc::DiscreteDomain< DDims... > >", "classDerivFieldCommon_3_01ChunkType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_01_4.html", "classDerivFieldCommon_3_01ChunkType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_01_4" ],
    [ "DerivFieldSpan", "classDerivFieldSpan.html", null ],
    [ "DerivFieldSpan< ElementType, ddc::DiscreteDomain< DDims... >, LayoutStridedPolicy, MemorySpace >", "classDerivFieldSpan_3_01ElementType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutSba1f79012ba40bd1581d6d5cbe3180bb.html", "classDerivFieldSpan_3_01ElementType_00_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutSba1f79012ba40bd1581d6d5cbe3180bb" ],
    [ "DiffusiveNeutralSolver", "classDiffusiveNeutralSolver.html", "classDiffusiveNeutralSolver" ],
    [ "DimX_pC", "structDimX__pC.html", null ],
    [ "DimY_pC", "structDimY__pC.html", null ],
    [ "DiocotronDensitySolution", "classDiocotronDensitySolution.html", "classDiocotronDensitySolution" ],
    [ "DiscreteSubDomain", "classDiscreteSubDomain.html", "classDiscreteSubDomain" ],
    [ "DiscreteSubDomainIterator", "structDiscreteSubDomainIterator.html", "structDiscreteSubDomainIterator" ],
    [ "DiscreteToCartesian", "classDiscreteToCartesian.html", "classDiscreteToCartesian" ],
    [ "Edge", "structEdge.html", "structEdge" ],
    [ "EdgeTransformation", "classEdgeTransformation.html", "classEdgeTransformation" ],
    [ "ElectrostaticalPotentialSimulation", "classElectrostaticalPotentialSimulation.html", "classElectrostaticalPotentialSimulation" ],
    [ "ElectrostaticalPotentialSimulation_decentred_rotation", "classElectrostaticalPotentialSimulation__decentred__rotation.html", "classElectrostaticalPotentialSimulation__decentred__rotation" ],
    [ "ElectrostaticalPotentialSimulation_rotation", "classElectrostaticalPotentialSimulation__rotation.html", "classElectrostaticalPotentialSimulation__rotation" ],
    [ "ElectrostaticalPotentialSimulation_translation", "classElectrostaticalPotentialSimulation__translation.html", "classElectrostaticalPotentialSimulation__translation" ],
    [ "Euler", "classEuler.html", "classEuler" ],
    [ "Evaluator2D", "structEvaluator2D.html", [
      [ "Evaluator", "classEvaluator2D_1_1Evaluator.html", "classEvaluator2D_1_1Evaluator" ]
    ] ],
    [ "FEM1DPoissonSolver", "classFEM1DPoissonSolver.html", "classFEM1DPoissonSolver" ],
    [ "FFTPoissonSolver", "classFFTPoissonSolver.html", null ],
    [ "FFTPoissonSolver< ddc::DiscreteDomain< DDims... >, FullDomain, ExecSpace, LayoutSpace >", "classFFTPoissonSolver_3_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01FullDomain_00_01ExecSpace_00_01LayoutSpace_01_4.html", "classFFTPoissonSolver_3_01ddc_1_1DiscreteDomain_3_01DDims_8_8_8_01_4_00_01FullDomain_00_01ExecSpace_00_01LayoutSpace_01_4" ],
    [ "FluidMoments", "classFluidMoments.html", "classFluidMoments" ],
    [ "for_each_tuple_cat", "structfor__each__tuple__cat.html", null ],
    [ "for_each_tuple_cat< std::tuple< Tuples... >, Tuple >", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4.html", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4" ],
    [ "FunctionToBeAdvected", "classFunctionToBeAdvected.html", "classFunctionToBeAdvected" ],
    [ "FunctionToBeAdvected_cos_4_elipse", "classFunctionToBeAdvected__cos__4__elipse.html", "classFunctionToBeAdvected__cos__4__elipse" ],
    [ "FunctionToBeAdvected_gaussian", "classFunctionToBeAdvected__gaussian.html", "classFunctionToBeAdvected__gaussian" ],
    [ "GaussLegendre", "classGaussLegendre.html", "classGaussLegendre" ],
    [ "GaussLegendreCoefficients", "structGaussLegendreCoefficients.html", null ],
    [ "GeometryXVx", "classGeometryXVx.html", "classGeometryXVx" ],
    [ "GeometryXYVxVy", "classGeometryXYVxVy.html", "classGeometryXYVxVy" ],
    [ "GridMom", "structGridMom.html", null ],
    [ "GridMu", "structGridMu.html", null ],
    [ "GridP1", "structGridP1.html", null ],
    [ "GridP2", "structGridP2.html", null ],
    [ "GridR", "structGridR.html", null ],
    [ "GridR1", "structGridR1.html", null ],
    [ "GridR2", "structGridR2.html", null ],
    [ "GridTheta", "structGridTheta.html", null ],
    [ "GridTor1", "structGridTor1.html", null ],
    [ "GridTor2", "structGridTor2.html", null ],
    [ "GridTor3", "structGridTor3.html", null ],
    [ "GridVpar", "structGridVpar.html", null ],
    [ "GridVx", "structGridVx.html", null ],
    [ "GridVy", "structGridVy.html", null ],
    [ "GridX", "structGridX.html", null ],
    [ "GridX1", "structGridX1.html", null ],
    [ "GridX2", "structGridX2.html", null ],
    [ "GridY", "structGridY.html", null ],
    [ "GridY1", "structGridY1.html", null ],
    [ "GridY2", "structGridY2.html", null ],
    [ "IAdvectionRTheta", "classIAdvectionRTheta.html", "classIAdvectionRTheta" ],
    [ "IAdvectionSpatial", "classIAdvectionSpatial.html", "classIAdvectionSpatial" ],
    [ "IAdvectionVelocity", "classIAdvectionVelocity.html", "classIAdvectionVelocity" ],
    [ "IBoltzmannSolver", "classIBoltzmannSolver.html", "classIBoltzmannSolver" ],
    [ "IChargeDensityCalculator", "classIChargeDensityCalculator.html", "classIChargeDensityCalculator" ],
    [ "IDimX", "structIDimX.html", null ],
    [ "IDimY", "structIDimY.html", null ],
    [ "IEquilibrium", "classIEquilibrium.html", "classIEquilibrium" ],
    [ "IFluidInitialization", "classIFluidInitialization.html", "classIFluidInitialization" ],
    [ "IFluidTransportSolver", "classIFluidTransportSolver.html", "classIFluidTransportSolver" ],
    [ "IFootFinder", "classIFootFinder.html", "classIFootFinder" ],
    [ "IInitialization", "classIInitialization.html", "classIInitialization" ],
    [ "IInterpolator", "classIInterpolator.html", "classIInterpolator" ],
    [ "IInterpolatorRTheta", "classIInterpolatorRTheta.html", "classIInterpolatorRTheta" ],
    [ "IKineticFluidCoupling", "classIKineticFluidCoupling.html", "classIKineticFluidCoupling" ],
    [ "IMPILayout", "classIMPILayout.html", "classIMPILayout" ],
    [ "IMPITranspose", "classIMPITranspose.html", "classIMPITranspose" ],
    [ "Interface", "structInterface.html", "structInterface" ],
    [ "interpolator_on_idx_range", "structinterpolator__on__idx__range.html", null ],
    [ "interpolator_on_idx_range< Interp, GridInterp, IdxRange< Grid1D... > >", "structinterpolator__on__idx__range_3_01Interp_00_01GridInterp_00_01IdxRange_3_01Grid1D_8_8_8_01_4_01_4.html", "structinterpolator__on__idx__range_3_01Interp_00_01GridInterp_00_01IdxRange_3_01Grid1D_8_8_8_01_4_01_4" ],
    [ "IonizationRate", "classIonizationRate.html", "classIonizationRate" ],
    [ "IPoissonSolver", "classIPoissonSolver.html", null ],
    [ "IPoissonSolver< ddc::DiscreteDomain< ODims... >, FullDomain, LayoutSpace, MemorySpace >", "classIPoissonSolver_3_01ddc_1_1DiscreteDomain_3_01ODims_8_8_8_01_4_00_01FullDomain_00_01LayoutSpace_00_01MemorySpace_01_4.html", "classIPoissonSolver_3_01ddc_1_1DiscreteDomain_3_01ODims_8_8_8_01_4_00_01FullDomain_00_01LayoutSpace_00_01MemorySpace_01_4" ],
    [ "IPreallocatableInterpolator", "classIPreallocatableInterpolator.html", "classIPreallocatableInterpolator" ],
    [ "IPreallocatableInterpolatorRTheta", "classIPreallocatableInterpolatorRTheta.html", "classIPreallocatableInterpolatorRTheta" ],
    [ "IQNSolver", "classIQNSolver.html", "classIQNSolver" ],
    [ "IReactionRate", "classIReactionRate.html", "classIReactionRate" ],
    [ "IRightHandSide", "classIRightHandSide.html", "classIRightHandSide" ],
    [ "is_subdomain_collection", "structis__subdomain__collection.html", null ],
    [ "is_subdomain_collection< DiscreteSubDomain< Tags... > >", "structis__subdomain__collection_3_01DiscreteSubDomain_3_01Tags_8_8_8_01_4_01_4.html", null ],
    [ "ITimeSolver", "classITimeSolver.html", "classITimeSolver" ],
    [ "ITimeSolverHybrid", "classITimeSolverHybrid.html", "classITimeSolverHybrid" ],
    [ "ITimeSolverRTheta", "classITimeSolverRTheta.html", "classITimeSolverRTheta" ],
    [ "ITimeStepper", "classITimeStepper.html", null ],
    [ "IVlasovSolver", "classIVlasovSolver.html", "classIVlasovSolver" ],
    [ "KelvinHelmholtzInstabilityInitialization", "classKelvinHelmholtzInstabilityInitialization.html", "classKelvinHelmholtzInstabilityInitialization" ],
    [ "KineticFluidCouplingSource", "classKineticFluidCouplingSource.html", "classKineticFluidCouplingSource" ],
    [ "KineticSource", "classKineticSource.html", "classKineticSource" ],
    [ "KrookSourceAdaptive", "classKrookSourceAdaptive.html", "classKrookSourceAdaptive" ],
    [ "KrookSourceConstant", "classKrookSourceConstant.html", "classKrookSourceConstant" ],
    [ "Lagrange", "classLagrange.html", "classLagrange" ],
    [ "LagrangeInterpolator", "classLagrangeInterpolator.html", "classLagrangeInterpolator" ],
    [ "ManufacturedPoissonTest", "classManufacturedPoissonTest.html", "classManufacturedPoissonTest" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "Matrix_Banded", "classMatrix__Banded.html", "classMatrix__Banded" ],
    [ "Matrix_Center_Block", "classMatrix__Center__Block.html", "classMatrix__Center__Block" ],
    [ "Matrix_Corner_Block", "classMatrix__Corner__Block.html", "classMatrix__Corner__Block" ],
    [ "Matrix_Dense", "classMatrix__Dense.html", "classMatrix__Dense" ],
    [ "Matrix_PDS_Tridiag", "classMatrix__PDS__Tridiag.html", "classMatrix__PDS__Tridiag" ],
    [ "Matrix_Periodic_Banded", "classMatrix__Periodic__Banded.html", "classMatrix__Periodic__Banded" ],
    [ "MatrixBatch", "classMatrixBatch.html", "classMatrixBatch" ],
    [ "MatrixBatchCsr", "classMatrixBatchCsr.html", "classMatrixBatchCsr" ],
    [ "MatrixBatchEll", "classMatrixBatchEll.html", "classMatrixBatchEll" ],
    [ "MatrixBatchTridiag", "classMatrixBatchTridiag.html", "classMatrixBatchTridiag" ],
    [ "MaxwellianEquilibrium", "classMaxwellianEquilibrium.html", "classMaxwellianEquilibrium" ],
    [ "Moments", "classMoments.html", "classMoments" ],
    [ "MPIDim", "structMPIDim.html", "structMPIDim" ],
    [ "MPILayout", "classMPILayout.html", "classMPILayout" ],
    [ "MPITransposeAllToAll", "classMPITransposeAllToAll.html", "classMPITransposeAllToAll" ],
    [ "Mu", "structMu.html", null ],
    [ "MultipatchSplineBuilder", "classMultipatchSplineBuilder.html", "classMultipatchSplineBuilder" ],
    [ "NoPerturbInitialization", "classNoPerturbInitialization.html", "classNoPerturbInitialization" ],
    [ "NullAdvectionVelocity", "classNullAdvectionVelocity.html", "classNullAdvectionVelocity" ],
    [ "NullFluidSolver", "classNullFluidSolver.html", "classNullFluidSolver" ],
    [ "NullQNSolver", "classNullQNSolver.html", "classNullQNSolver" ],
    [ "OutsideEdge", "structOutsideEdge.html", null ],
    [ "P1", "structP1.html", null ],
    [ "P2", "structP2.html", null ],
    [ "Patch", "structPatch.html", null ],
    [ "Patch< grid1, grid2, bsplines_dim1, bsplines_dim2 >", "structPatch_3_01grid1_00_01grid2_00_01bsplines__dim1_00_01bsplines__dim2_01_4.html", "structPatch_3_01grid1_00_01grid2_00_01bsplines__dim1_00_01bsplines__dim2_01_4" ],
    [ "PoissonLikeRHSFunction", "classPoissonLikeRHSFunction.html", "classPoissonLikeRHSFunction" ],
    [ "PoissonSolution", "classPoissonSolution.html", "classPoissonSolution" ],
    [ "PolarBSplines", "classPolarBSplines.html", "classPolarBSplines" ],
    [ "PolarBSplinesRTheta", "structPolarBSplinesRTheta.html", null ],
    [ "PolarSpline", "structPolarSpline.html", "structPolarSpline" ],
    [ "PolarSplineEvaluator", "classPolarSplineEvaluator.html", "classPolarSplineEvaluator" ],
    [ "PolarSplineFEMPoissonLikeSolver", "classPolarSplineFEMPoissonLikeSolver.html", "classPolarSplineFEMPoissonLikeSolver" ],
    [ "PolarSplineSpan", "structPolarSplineSpan.html", "structPolarSplineSpan" ],
    [ "PolarSplineView", "structPolarSplineView.html", "structPolarSplineView" ],
    [ "PolynomialEvaluator", "structPolynomialEvaluator.html", [
      [ "Evaluator", "classPolynomialEvaluator_1_1Evaluator.html", "classPolynomialEvaluator_1_1Evaluator" ]
    ] ],
    [ "PreallocatableLagrangeInterpolator", "classPreallocatableLagrangeInterpolator.html", "classPreallocatableLagrangeInterpolator" ],
    [ "PreallocatableSplineInterpolator", "classPreallocatableSplineInterpolator.html", "classPreallocatableSplineInterpolator" ],
    [ "PreallocatableSplineInterpolatorRTheta", "classPreallocatableSplineInterpolatorRTheta.html", "classPreallocatableSplineInterpolatorRTheta" ],
    [ "PredCorr", "classPredCorr.html", "classPredCorr" ],
    [ "PredCorrHybrid", "classPredCorrHybrid.html", "classPredCorrHybrid" ],
    [ "PredCorrRK2XY", "classPredCorrRK2XY.html", "classPredCorrRK2XY" ],
    [ "QNSolver", "classQNSolver.html", "classQNSolver" ],
    [ "Quadrature", "classQuadrature.html", "classQuadrature" ],
    [ "R", "structR.html", null ],
    [ "R1", "structR1.html", null ],
    [ "R2", "structR2.html", null ],
    [ "RDimX", "structRDimX.html", null ],
    [ "RDimY", "structRDimY.html", null ],
    [ "RecombinationRate", "classRecombinationRate.html", "classRecombinationRate" ],
    [ "RefinedDiscreteToCartesian", "classRefinedDiscreteToCartesian.html", "classRefinedDiscreteToCartesian" ],
    [ "RestartInitialization", "classRestartInitialization.html", "classRestartInitialization" ],
    [ "RK2", "classRK2.html", "classRK2" ],
    [ "RK3", "classRK3.html", "classRK3" ],
    [ "RK4", "classRK4.html", "classRK4" ],
    [ "RotationAdvectionFieldSimulation", "classRotationAdvectionFieldSimulation.html", "classRotationAdvectionFieldSimulation" ],
    [ "RotationSimulation", "classRotationSimulation.html", "classRotationSimulation" ],
    [ "SingleModePerturbInitialization", "classSingleModePerturbInitialization.html", "classSingleModePerturbInitialization" ],
    [ "Species", "structSpecies.html", null ],
    [ "SpeciesInformation", "classSpeciesInformation.html", "classSpeciesInformation" ],
    [ "SplineFootFinder", "classSplineFootFinder.html", "classSplineFootFinder" ],
    [ "SplineInterpolator", "classSplineInterpolator.html", "classSplineInterpolator" ],
    [ "SplineInterpolatorRTheta", "classSplineInterpolatorRTheta.html", "classSplineInterpolatorRTheta" ],
    [ "SplitRightHandSideSolver", "classSplitRightHandSideSolver.html", "classSplitRightHandSideSolver" ],
    [ "SplitVlasovSolver", "classSplitVlasovSolver.html", "classSplitVlasovSolver" ],
    [ "T", "structT.html", null ],
    [ "Theta", "structTheta.html", null ],
    [ "to_tuple", "structto__tuple.html", "structto__tuple" ],
    [ "to_tuple< std::integer_sequence< T, Ints... > >", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4.html", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4" ],
    [ "to_tuple< std::pair< T, U > >", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4" ],
    [ "ToDiscreteSubDomain", "structToDiscreteSubDomain.html", null ],
    [ "Tor1", "structTor1.html", null ],
    [ "Tor2", "structTor2.html", null ],
    [ "Tor3", "structTor3.html", null ],
    [ "TranslationAdvectionFieldSimulation", "classTranslationAdvectionFieldSimulation.html", "classTranslationAdvectionFieldSimulation" ],
    [ "TranslationSimulation", "classTranslationSimulation.html", "classTranslationSimulation" ],
    [ "tuple_to_types", "structtuple__to__types.html", "structtuple__to__types" ],
    [ "tuple_to_types< std::tuple< Args... > >", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4" ],
    [ "VectorField", "classVectorField.html", "classVectorField" ],
    [ "VectorFieldCommon", "classVectorFieldCommon.html", null ],
    [ "VectorFieldSpan", "classVectorFieldSpan.html", "classVectorFieldSpan" ],
    [ "VortexMergerDensitySolution", "classVortexMergerDensitySolution.html", "classVortexMergerDensitySolution" ],
    [ "VortexMergerEquilibria", "classVortexMergerEquilibria.html", "classVortexMergerEquilibria" ],
    [ "Vpar", "structVpar.html", null ],
    [ "Vr", "structVr.html", null ],
    [ "Vtheta", "structVtheta.html", null ],
    [ "Vx", "structVx.html", null ],
    [ "Vy", "structVy.html", null ],
    [ "X", "structX.html", null ],
    [ "X1", "structX1.html", null ],
    [ "X2", "structX2.html", null ],
    [ "Y", "structY.html", null ],
    [ "Y1", "structY1.html", null ],
    [ "Y2", "structY2.html", null ]
];