var annotated =
[
    [ "deprecated", null, [
      [ "BSplines", "classdeprecated_1_1BSplines.html", "classdeprecated_1_1BSplines" ],
      [ "NonUniformBSplines", "classdeprecated_1_1NonUniformBSplines.html", "classdeprecated_1_1NonUniformBSplines" ],
      [ "UniformBSplines", "classdeprecated_1_1UniformBSplines.html", "classdeprecated_1_1UniformBSplines" ],
      [ "Spline1D", "classdeprecated_1_1Spline1D.html", "classdeprecated_1_1Spline1D" ],
      [ "Spline2D", "classdeprecated_1_1Spline2D.html", "classdeprecated_1_1Spline2D" ],
      [ "SplineBuilder1D", "classdeprecated_1_1SplineBuilder1D.html", "classdeprecated_1_1SplineBuilder1D" ],
      [ "Boundary_data_2d", "structdeprecated_1_1Boundary__data__2d.html", "structdeprecated_1_1Boundary__data__2d" ],
      [ "SplineBuilder2D", "classdeprecated_1_1SplineBuilder2D.html", "classdeprecated_1_1SplineBuilder2D" ]
    ] ],
    [ "AdvectionDomain", "classAdvectionDomain.html", "classAdvectionDomain" ],
    [ "AdvectionField", "classAdvectionField.html", "classAdvectionField" ],
    [ "AdvectionField_decentred_rotation", "classAdvectionField__decentred__rotation.html", "classAdvectionField__decentred__rotation" ],
    [ "AdvectionField_rotation", "classAdvectionField__rotation.html", "classAdvectionField__rotation" ],
    [ "AdvectionField_translation", "classAdvectionField__translation.html", "classAdvectionField__translation" ],
    [ "AdvectionPhysicalDomain", "classAdvectionPhysicalDomain.html", "classAdvectionPhysicalDomain" ],
    [ "AdvectionPseudoCartesianDomain", "classAdvectionPseudoCartesianDomain.html", "classAdvectionPseudoCartesianDomain" ],
    [ "AdvectionSimulation", "classAdvectionSimulation.html", "classAdvectionSimulation" ],
    [ "AnalyticalInvertibleCurvilinear2DToCartesian", "classAnalyticalInvertibleCurvilinear2DToCartesian.html", "classAnalyticalInvertibleCurvilinear2DToCartesian" ],
    [ "BernsteinPolynomialBasis", "classBernsteinPolynomialBasis.html", "classBernsteinPolynomialBasis" ],
    [ "BslAdvectionRP", "classBslAdvectionRP.html", "classBslAdvectionRP" ],
    [ "BslAdvectionSpatial", "classBslAdvectionSpatial.html", "classBslAdvectionSpatial" ],
    [ "BslAdvectionSpatialBatched", "classBslAdvectionSpatialBatched.html", "classBslAdvectionSpatialBatched" ],
    [ "BslAdvectionVelocity", "classBslAdvectionVelocity.html", "classBslAdvectionVelocity" ],
    [ "BslAdvectionVelocityBatched", "classBslAdvectionVelocityBatched.html", "classBslAdvectionVelocityBatched" ],
    [ "BslExplicitPredCorrRP", "classBslExplicitPredCorrRP.html", "classBslExplicitPredCorrRP" ],
    [ "BslImplicitPredCorrRP", "classBslImplicitPredCorrRP.html", "classBslImplicitPredCorrRP" ],
    [ "BslPredCorrRP", "classBslPredCorrRP.html", "classBslPredCorrRP" ],
    [ "BSpline", "structBSpline.html", null ],
    [ "BumpontailEquilibrium", "classBumpontailEquilibrium.html", "classBumpontailEquilibrium" ],
    [ "cartesian_product_impl", "structcartesian__product__impl.html", null ],
    [ "cartesian_product_impl< std::tuple< std::tuple< HeadArgs... >, TailTuples... >, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_01std_1_1tuple_3_01HeadArgs_8_8_8_01_4_00_01Ta2e54ffdefaa524ceede7a120148cdbe5.html", null ],
    [ "cartesian_product_impl< std::tuple<>, OutTupleOfTuples >", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4.html", "structcartesian__product__impl_3_01std_1_1tuple_3_4_00_01OutTupleOfTuples_01_4" ],
    [ "CartesianSolution", "classCartesianSolution.html", "classCartesianSolution" ],
    [ "CartesianToBarycentricCoordinates", "classCartesianToBarycentricCoordinates.html", "classCartesianToBarycentricCoordinates" ],
    [ "ChargeDensityCalculator", "classChargeDensityCalculator.html", "classChargeDensityCalculator" ],
    [ "CircularToCartesian", "classCircularToCartesian.html", "classCircularToCartesian" ],
    [ "CollisionsInter", "classCollisionsInter.html", "classCollisionsInter" ],
    [ "CollisionsIntra", "classCollisionsIntra.html", "classCollisionsIntra" ],
    [ "ConstantExtrapolationBoundaryValue", "classConstantExtrapolationBoundaryValue.html", "classConstantExtrapolationBoundaryValue" ],
    [ "ConstantExtrapolationBoundaryValue2D", "classConstantExtrapolationBoundaryValue2D.html", "classConstantExtrapolationBoundaryValue2D" ],
    [ "CosineEvaluator", "structCosineEvaluator.html", [
      [ "Evaluator", "classCosineEvaluator_1_1Evaluator.html", "classCosineEvaluator_1_1Evaluator" ]
    ] ],
    [ "CrankNicolson", "classCrankNicolson.html", "classCrankNicolson" ],
    [ "Curvilinear2DToCartesian", "classCurvilinear2DToCartesian.html", "classCurvilinear2DToCartesian" ],
    [ "CurvilinearSolution", "classCurvilinearSolution.html", "classCurvilinearSolution" ],
    [ "CzarnyToCartesian", "classCzarnyToCartesian.html", "classCzarnyToCartesian" ],
    [ "DecentredRotationSimulation", "classDecentredRotationSimulation.html", "classDecentredRotationSimulation" ],
    [ "DimX_pC", "structDimX__pC.html", null ],
    [ "DimY_pC", "structDimY__pC.html", null ],
    [ "DiocotronDensitySolution", "classDiocotronDensitySolution.html", "classDiocotronDensitySolution" ],
    [ "DiscreteToCartesian", "classDiscreteToCartesian.html", "classDiscreteToCartesian" ],
    [ "ElectricField", "classElectricField.html", "classElectricField" ],
    [ "Euler", "classEuler.html", "classEuler" ],
    [ "Evaluator2D", "structEvaluator2D.html", [
      [ "Evaluator", "classEvaluator2D_1_1Evaluator.html", "classEvaluator2D_1_1Evaluator" ]
    ] ],
    [ "FemNonPeriodicPoissonSolver", "classFemNonPeriodicPoissonSolver.html", "classFemNonPeriodicPoissonSolver" ],
    [ "FemPeriodicPoissonSolver", "classFemPeriodicPoissonSolver.html", "classFemPeriodicPoissonSolver" ],
    [ "FftPoissonSolver", "classFftPoissonSolver.html", "classFftPoissonSolver" ],
    [ "FluidMoments", "classFluidMoments.html", "classFluidMoments" ],
    [ "for_each_tuple_cat", "structfor__each__tuple__cat.html", null ],
    [ "for_each_tuple_cat< std::tuple< Tuples... >, Tuple >", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4.html", "structfor__each__tuple__cat_3_01std_1_1tuple_3_01Tuples_8_8_8_01_4_00_01Tuple_01_4" ],
    [ "FunctionToBeAdvected", "classFunctionToBeAdvected.html", "classFunctionToBeAdvected" ],
    [ "FunctionToBeAdvected_cos_4_elipse", "classFunctionToBeAdvected__cos__4__elipse.html", "classFunctionToBeAdvected__cos__4__elipse" ],
    [ "FunctionToBeAdvected_gaussian", "classFunctionToBeAdvected__gaussian.html", "classFunctionToBeAdvected__gaussian" ],
    [ "GaussLegendre", "classGaussLegendre.html", "classGaussLegendre" ],
    [ "GaussLegendreCoefficients", "structGaussLegendreCoefficients.html", null ],
    [ "GeometryXVx", "classGeometryXVx.html", "classGeometryXVx" ],
    [ "GeometryXYVxVy", "classGeometryXYVxVy.html", "classGeometryXYVxVy" ],
    [ "GrevilleInterpolationPoints", "classGrevilleInterpolationPoints.html", "classGrevilleInterpolationPoints" ],
    [ "IAdvectionRP", "classIAdvectionRP.html", "classIAdvectionRP" ],
    [ "IAdvectionSpatial", "classIAdvectionSpatial.html", "classIAdvectionSpatial" ],
    [ "IAdvectionVelocity", "classIAdvectionVelocity.html", "classIAdvectionVelocity" ],
    [ "IBoltzmannSolver", "classIBoltzmannSolver.html", "classIBoltzmannSolver" ],
    [ "IChargeDensityCalculator", "classIChargeDensityCalculator.html", "classIChargeDensityCalculator" ],
    [ "IEquilibrium", "classIEquilibrium.html", "classIEquilibrium" ],
    [ "IFootFinder", "classIFootFinder.html", "classIFootFinder" ],
    [ "IInitialization", "classIInitialization.html", "classIInitialization" ],
    [ "IInterpolator", "classIInterpolator.html", "classIInterpolator" ],
    [ "IInterpolatorBatched", "classIInterpolatorBatched.html", "classIInterpolatorBatched" ],
    [ "IInterpolatorRP", "classIInterpolatorRP.html", "classIInterpolatorRP" ],
    [ "interpolator_on_domain", "structinterpolator__on__domain.html", null ],
    [ "interpolator_on_domain< Interp, DDimI, ddc::DiscreteDomain< DDim... > >", "structinterpolator__on__domain_3_01Interp_00_01DDimI_00_01ddc_1_1DiscreteDomain_3_01DDim_8_8_8_01_4_01_4.html", "structinterpolator__on__domain_3_01Interp_00_01DDimI_00_01ddc_1_1DiscreteDomain_3_01DDim_8_8_8_01_4_01_4" ],
    [ "IPoissonSolver", "classIPoissonSolver.html", "classIPoissonSolver" ],
    [ "IPreallocatableInterpolator", "classIPreallocatableInterpolator.html", "classIPreallocatableInterpolator" ],
    [ "IPreallocatableInterpolatorBatched", "classIPreallocatableInterpolatorBatched.html", "classIPreallocatableInterpolatorBatched" ],
    [ "IPreallocatableInterpolatorRP", "classIPreallocatableInterpolatorRP.html", "classIPreallocatableInterpolatorRP" ],
    [ "IRightHandSide", "classIRightHandSide.html", "classIRightHandSide" ],
    [ "ITimeSolver", "classITimeSolver.html", "classITimeSolver" ],
    [ "ITimeSolverRP", "classITimeSolverRP.html", "classITimeSolverRP" ],
    [ "ITimeStepper", "classITimeStepper.html", null ],
    [ "IVlasovSolver", "classIVlasovSolver.html", "classIVlasovSolver" ],
    [ "KineticSource", "classKineticSource.html", "classKineticSource" ],
    [ "KnotsAsInterpolationPoints", "classKnotsAsInterpolationPoints.html", "classKnotsAsInterpolationPoints" ],
    [ "KrookSourceAdaptive", "classKrookSourceAdaptive.html", "classKrookSourceAdaptive" ],
    [ "KrookSourceConstant", "classKrookSourceConstant.html", "classKrookSourceConstant" ],
    [ "Lagrange", "classLagrange.html", "classLagrange" ],
    [ "LagrangeInterpolator", "classLagrangeInterpolator.html", "classLagrangeInterpolator" ],
    [ "LagrangeInterpolatorBatched", "classLagrangeInterpolatorBatched.html", "classLagrangeInterpolatorBatched" ],
    [ "ManufacturedPoissonTest", "classManufacturedPoissonTest.html", "classManufacturedPoissonTest" ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "Matrix_Banded", "classMatrix__Banded.html", "classMatrix__Banded" ],
    [ "Matrix_Center_Block", "classMatrix__Center__Block.html", "classMatrix__Center__Block" ],
    [ "Matrix_Corner_Block", "classMatrix__Corner__Block.html", "classMatrix__Corner__Block" ],
    [ "Matrix_Dense", "classMatrix__Dense.html", "classMatrix__Dense" ],
    [ "Matrix_PDS_Tridiag", "classMatrix__PDS__Tridiag.html", "classMatrix__PDS__Tridiag" ],
    [ "Matrix_Periodic_Banded", "classMatrix__Periodic__Banded.html", "classMatrix__Periodic__Banded" ],
    [ "MaxwellianEquilibrium", "classMaxwellianEquilibrium.html", "classMaxwellianEquilibrium" ],
    [ "NonUniformBSplines", "classNonUniformBSplines.html", "classNonUniformBSplines" ],
    [ "NullAdvectionVelocity", "classNullAdvectionVelocity.html", "classNullAdvectionVelocity" ],
    [ "NullBoundaryValue", "classNullBoundaryValue.html", "classNullBoundaryValue" ],
    [ "NullBoundaryValue2D", "classNullBoundaryValue2D.html", "classNullBoundaryValue2D" ],
    [ "NullPoissonSolver", "classNullPoissonSolver.html", "classNullPoissonSolver" ],
    [ "PoissonRHSFunction", "classPoissonRHSFunction.html", "classPoissonRHSFunction" ],
    [ "PoissonSolution", "classPoissonSolution.html", "classPoissonSolution" ],
    [ "PolarBSplines", "classPolarBSplines.html", "classPolarBSplines" ],
    [ "PolarNullBoundaryValue2D", "classPolarNullBoundaryValue2D.html", "classPolarNullBoundaryValue2D" ],
    [ "PolarSpline", "structPolarSpline.html", "structPolarSpline" ],
    [ "PolarSplineBoundaryValue2D", "classPolarSplineBoundaryValue2D.html", "classPolarSplineBoundaryValue2D" ],
    [ "PolarSplineEvaluator", "classPolarSplineEvaluator.html", "classPolarSplineEvaluator" ],
    [ "PolarSplineFEMPoissonSolver", "classPolarSplineFEMPoissonSolver.html", "classPolarSplineFEMPoissonSolver" ],
    [ "PolarSplineSpan", "structPolarSplineSpan.html", "structPolarSplineSpan" ],
    [ "PolarSplineView", "structPolarSplineView.html", "structPolarSplineView" ],
    [ "PolynomialEvaluator", "structPolynomialEvaluator.html", [
      [ "Evaluator", "classPolynomialEvaluator_1_1Evaluator.html", "classPolynomialEvaluator_1_1Evaluator" ]
    ] ],
    [ "PreallocatableLagrangeInterpolator", "classPreallocatableLagrangeInterpolator.html", "classPreallocatableLagrangeInterpolator" ],
    [ "PreallocatableLagrangeInterpolatorBatched", "classPreallocatableLagrangeInterpolatorBatched.html", "classPreallocatableLagrangeInterpolatorBatched" ],
    [ "PreallocatableSplineInterpolator", "classPreallocatableSplineInterpolator.html", "classPreallocatableSplineInterpolator" ],
    [ "PreallocatableSplineInterpolatorBatched", "classPreallocatableSplineInterpolatorBatched.html", "classPreallocatableSplineInterpolatorBatched" ],
    [ "PreallocatableSplineInterpolatorRP", "classPreallocatableSplineInterpolatorRP.html", "classPreallocatableSplineInterpolatorRP" ],
    [ "PredCorr", "classPredCorr.html", "classPredCorr" ],
    [ "Quadrature", "classQuadrature.html", "classQuadrature" ],
    [ "RDimP", "structRDimP.html", null ],
    [ "RDimR", "structRDimR.html", null ],
    [ "RDimT", "structRDimT.html", null ],
    [ "RDimVp", "structRDimVp.html", null ],
    [ "RDimVr", "structRDimVr.html", null ],
    [ "RDimVx", "structRDimVx.html", null ],
    [ "RDimVy", "structRDimVy.html", null ],
    [ "RDimX", "structRDimX.html", null ],
    [ "RDimY", "structRDimY.html", null ],
    [ "RefinedDiscreteToCartesian", "classRefinedDiscreteToCartesian.html", "classRefinedDiscreteToCartesian" ],
    [ "RestartInitialization", "classRestartInitialization.html", "classRestartInitialization" ],
    [ "RK2", "classRK2.html", "classRK2" ],
    [ "RK3", "classRK3.html", "classRK3" ],
    [ "RK4", "classRK4.html", "classRK4" ],
    [ "RotationSimulation", "classRotationSimulation.html", "classRotationSimulation" ],
    [ "SingleModePerturbInitialization", "classSingleModePerturbInitialization.html", "classSingleModePerturbInitialization" ],
    [ "SpeciesInformation", "classSpeciesInformation.html", "classSpeciesInformation" ],
    [ "SplineBoundaryValue", "classSplineBoundaryValue.html", "classSplineBoundaryValue" ],
    [ "SplineBoundaryValue2D", "classSplineBoundaryValue2D.html", "classSplineBoundaryValue2D" ],
    [ "SplineBuilder", "classSplineBuilder.html", "classSplineBuilder" ],
    [ "SplineBuilder2D", "classSplineBuilder2D.html", "classSplineBuilder2D" ],
    [ "SplineChargeDensityCalculator", "classSplineChargeDensityCalculator.html", "classSplineChargeDensityCalculator" ],
    [ "SplineErrorBounds", "classSplineErrorBounds.html", "classSplineErrorBounds" ],
    [ "SplineEvaluator", "classSplineEvaluator.html", "classSplineEvaluator" ],
    [ "SplineEvaluator2D", "classSplineEvaluator2D.html", "classSplineEvaluator2D" ],
    [ "SplineFootFinder", "classSplineFootFinder.html", "classSplineFootFinder" ],
    [ "SplineInterpolator", "classSplineInterpolator.html", "classSplineInterpolator" ],
    [ "SplineInterpolatorBatched", "classSplineInterpolatorBatched.html", "classSplineInterpolatorBatched" ],
    [ "SplineInterpolatorRP", "classSplineInterpolatorRP.html", "classSplineInterpolatorRP" ],
    [ "SplitRightHandSideSolver", "classSplitRightHandSideSolver.html", "classSplitRightHandSideSolver" ],
    [ "SplitVlasovSolver", "classSplitVlasovSolver.html", "classSplitVlasovSolver" ],
    [ "to_tuple", "structto__tuple.html", "structto__tuple" ],
    [ "to_tuple< std::integer_sequence< T, Ints... > >", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4.html", "structto__tuple_3_01std_1_1integer__sequence_3_01T_00_01Ints_8_8_8_01_4_01_4" ],
    [ "to_tuple< std::pair< T, U > >", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html", "structto__tuple_3_01std_1_1pair_3_01T_00_01U_01_4_01_4" ],
    [ "TranslationSimulation", "classTranslationSimulation.html", "classTranslationSimulation" ],
    [ "tuple_to_types", "structtuple__to__types.html", "structtuple__to__types" ],
    [ "tuple_to_types< std::tuple< Args... > >", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", "structtuple__to__types_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4" ],
    [ "UniformBSplines", "classUniformBSplines.html", "classUniformBSplines" ],
    [ "VectorField", "classVectorField.html", "classVectorField" ],
    [ "VectorFieldCommon", "classVectorFieldCommon.html", null ],
    [ "VectorFieldSpan", "classVectorFieldSpan.html", "classVectorFieldSpan" ],
    [ "VlasovPoissonSolver", "classVlasovPoissonSolver.html", "classVlasovPoissonSolver" ]
];