var dir_040b90264b67cd95a975364a9a6adb0b =
[
    [ "Field setup", "simulations_geometryRTheta_diocotron.html#autotoc_md20", null ],
    [ "General case", "simulations_geometryRTheta_diocotron.html#autotoc_md21", null ],
    [ "Simplified case", "simulations_geometryRTheta_diocotron.html#autotoc_md22", null ],
    [ "Predictor-corrector", "simulations_geometryRTheta_diocotron.html#autotoc_md23", null ],
    [ "Recommended parameters:", "simulations_geometryRTheta_diocotron.html#autotoc_md24", null ],
    [ "Executables:", "simulations_geometryRTheta_diocotron.html#autotoc_md25", null ],
    [ "Field setup", "simulations_geometryRTheta_vortex_merger.html#autotoc_md26", null ],
    [ "General case", "simulations_geometryRTheta_vortex_merger.html#autotoc_md27", null ],
    [ "Simplified case", "simulations_geometryRTheta_vortex_merger.html#autotoc_md28", null ],
    [ "Recommended parameters:", "simulations_geometryRTheta_vortex_merger.html#autotoc_md29", null ],
    [ "Executables:", "simulations_geometryRTheta_vortex_merger.html#autotoc_md30", null ],
    [ "Studied equation", "src_geometryRTheta_advection.html#autotoc_md31", null ],
    [ "Backward Semi-Lagrangian method", "src_geometryRTheta_advection.html#autotoc_md32", null ],
    [ "Time integration methods", "src_geometryRTheta_advection.html#autotoc_md33", [
      [ "Explicit Euler method", "src_geometryRTheta_advection.html#autotoc_md34", null ],
      [ "Crank-Nicolson method", "src_geometryRTheta_advection.html#autotoc_md35", null ],
      [ "RK3 method", "src_geometryRTheta_advection.html#autotoc_md36", null ],
      [ "RK4 method", "src_geometryRTheta_advection.html#autotoc_md37", null ]
    ] ],
    [ "Advection domain", "src_geometryRTheta_advection.html#autotoc_md38", null ],
    [ "B-splines FEM", "src_geometryRTheta_poisson.html#autotoc_md44", [
      [ "The B-splines", "src_geometryRTheta_poisson.html#autotoc_md45", null ],
      [ "Treatment of the O-point", "src_geometryRTheta_poisson.html#autotoc_md46", null ],
      [ "Weak formulation", "src_geometryRTheta_poisson.html#autotoc_md47", null ]
    ] ],
    [ "Initialization", "src_geometryRTheta_initialization.html#autotoc_md39", null ],
    [ "Equilibirum", "src_geometryRTheta_initialization.html#autotoc_md40", null ],
    [ "Dispersion relation", "src_geometryRTheta_initialization.html#autotoc_md41", null ],
    [ "Equilibirum", "src_geometryRTheta_initialization.html#autotoc_md42", null ],
    [ "References", "src_geometryRTheta_initialization.html#autotoc_md43", null ],
    [ "- The mapping and the domain used for the advection:", "tests_geometryRTheta_advection_2d_rp.html#autotoc_md50", null ],
    [ "- The time integration method used to solve the characteristic equation:", "tests_geometryRTheta_advection_2d_rp.html#autotoc_md51", null ],
    [ "- The test simulation:", "tests_geometryRTheta_advection_2d_rp.html#autotoc_md52", null ],
    [ "Functions tests:", "tests_geometryRTheta_2d_spline_interpolator.html#autotoc_md48", null ],
    [ "Python scripts", "tests_geometryRTheta_2d_spline_interpolator.html#autotoc_md49", null ],
    [ "deprecated", "dir_bf05ee1a50b262d9ca6db6046de9e516.html", "dir_bf05ee1a50b262d9ca6db6046de9e516" ],
    [ "mapping", "dir_401f8b249764c6753d0f677d3a20782c.html", "dir_401f8b249764c6753d0f677d3a20782c" ],
    [ "bernstein.hpp", "bernstein_8hpp_source.html", null ],
    [ "bspline.hpp", "bspline_8hpp_source.html", null ],
    [ "bsplines_non_uniform.hpp", "bsplines__non__uniform_8hpp_source.html", null ],
    [ "bsplines_uniform.hpp", "bsplines__uniform_8hpp_source.html", null ],
    [ "constant_extrapolation_boundary_value.hpp", "constant__extrapolation__boundary__value_8hpp_source.html", null ],
    [ "gauss_legendre_integration.hpp", "gauss__legendre__integration_8hpp_source.html", null ],
    [ "greville_interpolation_points.hpp", "greville__interpolation__points_8hpp_source.html", null ],
    [ "knots_as_interpolation_points.hpp", "knots__as__interpolation__points_8hpp_source.html", null ],
    [ "math_tools.hpp", "math__tools_8hpp_source.html", null ],
    [ "matrix.hpp", "matrix_8hpp_source.html", null ],
    [ "matrix_banded.hpp", "matrix__banded_8hpp_source.html", null ],
    [ "matrix_center_block.hpp", "matrix__center__block_8hpp_source.html", null ],
    [ "matrix_corner_block.hpp", "matrix__corner__block_8hpp_source.html", null ],
    [ "matrix_dense.hpp", "matrix__dense_8hpp_source.html", null ],
    [ "matrix_pds_tridiag.hpp", "matrix__pds__tridiag_8hpp_source.html", null ],
    [ "matrix_periodic_banded.hpp", "matrix__periodic__banded_8hpp_source.html", null ],
    [ "null_boundary_value.hpp", "null__boundary__value_8hpp_source.html", null ],
    [ "polar_bsplines.hpp", "polar__bsplines_8hpp_source.html", null ],
    [ "polar_spline.hpp", "polar__spline_8hpp_source.html", null ],
    [ "polar_spline_evaluator.hpp", "polar__spline__evaluator_8hpp_source.html", null ],
    [ "spline_boundary_conditions.hpp", "spline__boundary__conditions_8hpp_source.html", null ],
    [ "spline_boundary_value.hpp", "spline__boundary__value_8hpp_source.html", null ],
    [ "spline_builder.hpp", "spline__builder_8hpp_source.html", null ],
    [ "spline_builder_2d.hpp", "spline__builder__2d_8hpp_source.html", null ],
    [ "spline_evaluator.hpp", "spline__evaluator_8hpp_source.html", null ],
    [ "spline_evaluator_2d.hpp", "spline__evaluator__2d_8hpp_source.html", null ],
    [ "view.hpp", "view_8hpp_source.html", null ]
];