
# Kokkos flags
set(Kokkos_ENABLE_DEPRECATED_CODE_4 OFF)
set(Kokkos_ENABLE_DEPRECATION_WARNINGS OFF)

# Deactivate slow tests if requested
if (DEFINED ENV{SLL_BUILD_TESTING})
    set(SLL_BUILD_TESTING $ENV{SLL_BUILD_TESTING})
endif()
if (DEFINED ENV{POISSON_2D_BUILD_TESTING})
    set(POISSON_2D_BUILD_TESTING $ENV{POISSON_2D_BUILD_TESTING})
endif()

# CTest flags
set(CTEST_OUTPUT_ON_FAILURE ON)
