var searchData=
[
  ['rbasissubset_374',['RBasisSubset',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RBasisSubset',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rcelldim_375',['RCellDim',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RCellDim',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rdimp_376',['RDimP',['../structRDimP.html',1,'']]],
  ['rdimprefined_377',['RDimPRefined',['../structRefinedDiscreteToCartesian_1_1RDimPRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimr_378',['RDimR',['../structRDimR.html',1,'']]],
  ['rdimrrefined_379',['RDimRRefined',['../structRefinedDiscreteToCartesian_1_1RDimRRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimt_380',['RDimT',['../structRDimT.html',1,'']]],
  ['rdimvp_381',['RDimVp',['../structRDimVp.html',1,'']]],
  ['rdimvr_382',['RDimVr',['../structRDimVr.html',1,'']]],
  ['rdimvx_383',['RDimVx',['../structRDimVx.html',1,'']]],
  ['rdimvy_384',['RDimVy',['../structRDimVy.html',1,'']]],
  ['rdimx_385',['RDimX',['../structRDimX.html',1,'']]],
  ['rdimx_5fadv_386',['RDimX_adv',['../classAdvectionPseudoCartesianDomain.html#a76a522695ce2d2704583afb7a91f218a',1,'AdvectionPseudoCartesianDomain::RDimX_adv()'],['../classAdvectionPhysicalDomain.html#a77b189d95314b128a28c1cc16cb82812',1,'AdvectionPhysicalDomain::RDimX_adv()']]],
  ['rdimxrefined_387',['RDimXRefined',['../structRefinedDiscreteToCartesian_1_1RDimXRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimy_388',['RDimY',['../structRDimY.html',1,'']]],
  ['rdimy_5fadv_389',['RDimY_adv',['../classAdvectionPhysicalDomain.html#ade892d96a026786816cc72679b18e496',1,'AdvectionPhysicalDomain::RDimY_adv()'],['../classAdvectionPseudoCartesianDomain.html#a761b8ac4b157cce005008ca24ba11c2b',1,'AdvectionPseudoCartesianDomain::RDimY_adv()']]],
  ['rdimyrefined_390',['RDimYRefined',['../structRefinedDiscreteToCartesian_1_1RDimYRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['refineddiscretetocartesian_391',['RefinedDiscreteToCartesian',['../classRefinedDiscreteToCartesian.html',1,'RefinedDiscreteToCartesian&lt; RDimX, RDimY, SplineRPBuilder, SplineRPEvaluator, Nr, Nt &gt;'],['../classRefinedDiscreteToCartesian.html#ae29f077f94f09fc84bd19d45f8e7e225',1,'RefinedDiscreteToCartesian::RefinedDiscreteToCartesian(RefinedDiscreteToCartesian const &amp;x)=default'],['../classRefinedDiscreteToCartesian.html#ae5bba01bd6c921ef16dc603188003936',1,'RefinedDiscreteToCartesian::RefinedDiscreteToCartesian(RefinedDiscreteToCartesian &amp;&amp;x)=default'],['../classRefinedDiscreteToCartesian.html#afc2031614bda057a5d97e89ad44fe0f2',1,'RefinedDiscreteToCartesian::RefinedDiscreteToCartesian(IDomainRPRefined const &amp;refined_domain, ddc::Chunk&lt; double, BSDomainRPRefined &gt; &amp;&amp;curvilinear_to_x, ddc::Chunk&lt; double, BSDomainRPRefined &gt; &amp;&amp;curvilinear_to_y, CoordRRefined r_min, CoordRRefined r_max)']]],
  ['restartinitialization_392',['RestartInitialization',['../classRestartInitialization.html',1,'RestartInitialization'],['../classRestartInitialization.html#a9af5fa49fc9e082a38025f5d20db255f',1,'RestartInitialization::RestartInitialization()']]],
  ['rhs_393',['RHS',['../src_geometry5D_rhs.html',1,'src_geometry5D'],['../src_geometryXVx_rhs.html',1,'src_geometryXVx']]],
  ['rk2_394',['RK2',['../classRK2.html#a29590ce29977600f0a17c7cdfcbb3584',1,'RK2::RK2()'],['../classRK2.html',1,'RK2&lt; ValChunk, DerivChunk &gt;']]],
  ['rk3_395',['RK3',['../classRK3.html#ab75113e8885dfdbc7c41494db8d2f269',1,'RK3::RK3()'],['../classRK3.html',1,'RK3&lt; ValChunk, DerivChunk &gt;']]],
  ['rk4_396',['RK4',['../classRK4.html',1,'RK4&lt; ValChunk, DerivChunk &gt;'],['../classRK4.html#a63289a986749f2cffeb0180bb37b8cfa',1,'RK4::RK4()']]],
  ['rotationadvectionfieldsimulation_397',['RotationAdvectionFieldSimulation',['../classRotationAdvectionFieldSimulation.html',1,'RotationAdvectionFieldSimulation&lt; Mapping &gt;'],['../classRotationAdvectionFieldSimulation.html#a7680c2f088d504f2879865b190c5128a',1,'RotationAdvectionFieldSimulation::RotationAdvectionFieldSimulation()']]],
  ['rotationsimulation_398',['RotationSimulation',['../classRotationSimulation.html',1,'RotationSimulation&lt; Mapping &gt;'],['../classRotationSimulation.html#a24cab55207f4b65feffd1255545b92dd',1,'RotationSimulation::RotationSimulation()']]]
];
