var searchData=
[
  ['lagrange_0',['lagrange',['../classLagrange.html#a71594722ed82a25a22c9ef7a74e4aa65',1,'Lagrange::Lagrange()'],['../classLagrange.html',1,'Lagrange&lt; Execspace, GridInterp, BcMin, BcMax &gt;']]],
  ['lagrangeinterpolator_1',['lagrangeinterpolator',['../classLagrangeInterpolator.html',1,'LagrangeInterpolator&lt; GridInterp, BcMin, BcMax, Grid1D &gt;'],['../classLagrangeInterpolator.html#a60914d8391f7ea2e47c624a088ec5d92',1,'LagrangeInterpolator::LagrangeInterpolator()']]],
  ['lagrangeinterpolator_3c_20gridinterp_2c_20bcmin_2c_20bcmax_2c_20grid1d_2e_2e_2e_20_3e_2',['LagrangeInterpolator&lt; GridInterp, BcMin, BcMax, Grid1D... &gt;',['../classLagrangeInterpolator.html',1,'']]],
  ['lagrangian_20method_3',['Backward Semi-Lagrangian method',['../src_geometryRTheta_advection.html#src_geometryRTheta_advection__Backward_Semi-Lagrangian_method',1,'']]],
  ['lambda_20cannot_20be_20used_20in_20the_20template_20argument_20type_20of_20a_20_5f_5fglobal_5f_5f_20function_4',['The closure type for a lambda cannot be used in the template argument type of a &apos;__global__&apos; function',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_closure_type_for_a_lambda_cannot_be_used_in_the_template_argument_type_of_a____global____function',1,'']]],
  ['lambda_20cannot_20have_20private_20or_20protected_20access_20within_20its_20class_5',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda cannot have private or protected access within its class',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_cannot_have_private_or_protected_access_within_its_class',1,'']]],
  ['lambda_20expression_6',['Implicit capture of &apos;this&apos; in extended lambda expression',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__Implicit_capture_of__this__in_extended_lambda_expression',1,'']]],
  ['laplacian_5fidx_5frange_5ftype_7',['laplacian_idx_range_type',['../classFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace_00_01LayoutSpace_01_4.html#af83b239c2f9ffce4663b0210488b5cc0',1,'FFTPoissonSolver&lt; IdxRange&lt; GridPDEDim1D... &gt;, IdxRangeFull, ExecSpace, LayoutSpace &gt;::laplacian_idx_range_type'],['../classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01LayoutSpace_00_01MemorySpace_01_4.html#a5ad99076e4c004c485a3a2dbae577292',1,'IPoissonSolver&lt; IdxRange&lt; ODims... &gt;, IdxRangeFull, LayoutSpace, MemorySpace &gt;::laplacian_idx_range_type']]],
  ['laplacian_5ftags_8',['laplacian_tags',['../classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01LayoutSpace_00_01MemorySpace_01_4.html#a21c134f46e023ca6077b8e058da70a8b',1,'IPoissonSolver&lt; IdxRange&lt; ODims... &gt;, IdxRangeFull, LayoutSpace, MemorySpace &gt;']]],
  ['layout_9',['Layout',['../src_mpi_parallelisation.html#src_mpi_parallelisation__Layout',1,'']]],
  ['layout_5fspace_10',['layout_space',['../classFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace_00_01LayoutSpace_01_4.html#a3a64a6ecef7debc55b0e7acefcb4a8e1',1,'FFTPoissonSolver&lt; IdxRange&lt; GridPDEDim1D... &gt;, IdxRangeFull, ExecSpace, LayoutSpace &gt;::layout_space'],['../classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01LayoutSpace_00_01MemorySpace_01_4.html#ab3a2f43488c4c75120371ea5c379a005',1,'IPoissonSolver&lt; IdxRange&lt; ODims... &gt;, IdxRangeFull, LayoutSpace, MemorySpace &gt;::layout_space']]],
  ['layout_5ftype_11',['layout_type',['../classVectorField.html#a9f64c689d0da7b283020b30fc6a67a9f',1,'VectorField']]],
  ['like_20equation_12',['The Poisson-like equation',['../src_geometryRTheta_poisson.html#src_geometryRTheta_poisson__The_Poisson-like_equation',1,'']]],
  ['line_13',['Command line',['../simulations_geometryXY_guiding_center.html#autotoc_md35',1,'']]],
  ['locally_14',['Building documentation locally',['../docs_Adding_docs.html#docs_Adding_docs__Building_documentation_locally',1,'']]],
  ['locator_15',['Patch locator',['../src_multipatch_connectivity.html#src_multipatch_connectivity__Patch_locator',1,'']]],
  ['logical_20domain_20axis_16',['Advection field along the logical domain axis',['../src_geometryRTheta_advection_field.html#autotoc_md49',1,'']]]
];
