var searchData=
[
  ['unit_20tests_0',['unit tests',['../src_geometryRTheta_poisson.html#src_geometryRTheta_poisson__Unit_tests',1,'Unit tests'],['../src_geometryRTheta_advection.html#autotoc_md45',1,'Unit tests']]],
  ['up_1',['Set-up',['../index.html#__Set-up',1,'']]],
  ['update_2',['update',['../classCrankNicolson.html#aeffa66677ee474545531df76a8c07a6d',1,'CrankNicolson::update()'],['../classRK4.html#a0bffdc18f1c874e94864f8bb0d4c34dc',1,'RK4::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy, std::function&lt; void(ValField, DerivConstField, double)&gt; y_update) const'],['../classRK4.html#a732a7d0bddff6dad7454d4f0da6549b0',1,'RK4::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classRK4.html#ac74c2d32e81293af91dbe282296e5b99',1,'RK4::update(ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classRK3.html#a10ec8a72fe24f3ab51d7f85905b8fda4',1,'RK3::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy, std::function&lt; void(ValField, DerivConstField, double)&gt; y_update) const'],['../classRK3.html#a165f7b293eb74b754551428df512c8e6',1,'RK3::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classRK3.html#a277909007e34e4c0d757164eabcf8b45',1,'RK3::update(ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classRK2.html#aa9d83c57da43660ee63a555957f37981',1,'RK2::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classRK2.html#afedd4b2ac6d505e801544ed4c65f7492',1,'RK2::update(ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classEuler.html#aa71f4620ef32ee8d620630baf04f98c7',1,'Euler::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy, std::function&lt; void(ValField, DerivConstField, double)&gt; y_update) const'],['../classEuler.html#a7027b27fbd24e828ee6f03e3d58c30b5',1,'Euler::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classEuler.html#ad041a4b9b4ab5d7fb453c03fe1008c60',1,'Euler::update(ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classCrankNicolson.html#a55861c1516576c81d426ec330fbb2f80',1,'CrankNicolson::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy) const'],['../classCrankNicolson.html#ab4f2952ddd9d9bac670fafd20e15448f',1,'CrankNicolson::update(ExecSpace const &amp;exec_space, ValField y, double dt, std::function&lt; void(DerivFieldMem, ValConstField)&gt; dy, std::function&lt; void(ValField, DerivConstField, double)&gt; y_update) const'],['../classRK2.html#a7488abb4ec806238cec4e2c0568360de',1,'RK2::update()']]],
  ['usage_3',['usage',['../toolchains.html#toolchains__General_usage',1,'General usage'],['../simulations_geometryXVx_sheath.html#simulations_geometryXVx_sheath__Usage',1,'Usage'],['../simulations_geometryXVx_neutrals.html#simulations_geometryXVx_neutrals__Usage',1,'Usage']]],
  ['use_4',['Example of use',['../src_advection.html#autotoc_md39',1,'']]],
  ['use_20of_20index_20step_20for_20finite_20differences_5',['Example use of Index Step for Finite Differences',['../docs_DDC_in_gyselalibxx.html#autotoc_md17',1,'']]],
  ['use_20of_20multipatchsplinebuilder_6',['Example of use of MultipatchSplineBuilder',['../src_multipatch_spline.html#autotoc_md74',1,'']]],
  ['used_20for_20input_20and_20output_7',['Functions used for input and output.',['../src_io.html',1,'src']]],
  ['used_20for_20the_20advection_3a_8',['- The mapping and the domain used for the advection:',['../tests_geometryRTheta_advection_2d_rp.html#autotoc_md81',1,'']]],
  ['used_20in_20the_20template_20argument_20type_20of_20a_20_5f_5fglobal_5f_5f_20function_9',['The closure type for a lambda cannot be used in the template argument type of a &apos;__global__&apos; function',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_closure_type_for_a_lambda_cannot_be_used_in_the_template_argument_type_of_a____global____function',1,'']]],
  ['used_20to_20solve_20the_20characteristic_20equation_3a_10',['- The time integration method used to solve the characteristic equation:',['../tests_geometryRTheta_advection_2d_rp.html#autotoc_md82',1,'']]],
  ['useful_20references_11',['Useful references',['../simulations_geometryRTheta_vortex_merger.html#simulations_geometryRTheta_vortex_merger__Useful_references',1,'']]],
  ['using_20ddc_20in_20gyselalibxx_12',['Using DDC in Gyselalibxx',['../docs_DDC_in_gyselalibxx.html',1,'']]],
  ['using_20git_13',['Using Git',['../docs_Using_git.html',1,'']]],
  ['using_5fvector_5ffield_14',['using_vector_field',['../classIPoissonSolver_3_01IdxRange_3_01ODims_8_8_8_01_4_00_01IdxRangeFull_00_01LayoutSpace_00_01MemorySpace_01_4.html#a4fe95be66770e3939f09a33ef5ce7625',1,'IPoissonSolver&lt; IdxRange&lt; ODims... &gt;, IdxRangeFull, LayoutSpace, MemorySpace &gt;']]],
  ['utility_20functions_15',['Utility Functions',['../src_utils.html',1,'src']]],
  ['utility_20tools_16',['Utility tools',['../src_utils.html#src_utils__Utility_tools',1,'']]],
  ['utils_17',['Utils',['../src_geometryXVx_utils.html',1,'src_geometryXVx']]],
  ['utils_5ftools_2ehpp_18',['utils_tools.hpp',['../utils__tools_8hpp.html',1,'']]]
];
