var searchData=
[
  ['kelvin_20helmholtz_20instability_20test_20case_0',['kelvin helmholtz instability test case',['../src_geometryXY_initialization.html#src_geometryXY_initialization__Kelvin-Helmholtz_instability_test_case',1,'Kelvin-Helmholtz instability test case'],['../simulations_geometryXY_guiding_center.html#autotoc_md37',1,'Test case: Kelvin-Helmholtz instability test case']]],
  ['kelvinhelmholtzinstabilityinitialization_1',['kelvinhelmholtzinstabilityinitialization',['../classKelvinHelmholtzInstabilityInitialization.html',1,'KelvinHelmholtzInstabilityInitialization'],['../classKelvinHelmholtzInstabilityInitialization.html#a24ff959246cb56cf388f412cb0933c08',1,'KelvinHelmholtzInstabilityInitialization::KelvinHelmholtzInstabilityInitialization()']]],
  ['kineticsource_2',['kineticsource',['../classKineticSource.html',1,'KineticSource'],['../classKineticSource.html#ac1eb6d9a4a099ed40aa4bd3b22165358',1,'KineticSource::KineticSource()']]],
  ['koliop_5finterface_3',['koliop_interface',['../namespacekoliop__interface.html',1,'']]],
  ['krooksourceadaptive_4',['krooksourceadaptive',['../classKrookSourceAdaptive.html',1,'KrookSourceAdaptive'],['../classKrookSourceAdaptive.html#a2e0a23353e923920745e63ec47543fbc',1,'KrookSourceAdaptive::KrookSourceAdaptive(IdxRangeX const &amp;gridx, IdxRangeVx const &amp;gridvx, RhsType const type, double extent, double stiffness, double amplitude, double density, double temperature)'],['../classKrookSourceAdaptive.html#a7bddcb9927245e841113f9483271e6a0',1,'KrookSourceAdaptive::KrookSourceAdaptive(KrookSourceAdaptive &amp;&amp;)=default']]],
  ['krooksourceconstant_5',['krooksourceconstant',['../classKrookSourceConstant.html',1,'KrookSourceConstant'],['../classKrookSourceConstant.html#a23f3846feea732e1d57eae70823c546e',1,'KrookSourceConstant::KrookSourceConstant(IdxRangeX const &amp;gridx, IdxRangeVx const &amp;gridv, RhsType const type, double extent, double stiffness, double amplitude, double density, double temperature)'],['../classKrookSourceConstant.html#a94d8fa0b721fbe980a11a9edc298b9c8',1,'KrookSourceConstant::KrookSourceConstant(KrookSourceConstant &amp;&amp;)=default']]]
];
