var searchData=
[
  ['a_20given_20advection_20field_0',['1D advection with a given advection field',['../src_advection.html#src_advection__1D_advection_with_a_given_advection_field',1,'']]],
  ['a_20lambda_20cannot_20be_20used_20in_20the_20template_20argument_20type_20of_20a_20_5f_5fglobal_5f_5f_20function_1',['The closure type for a lambda cannot be used in the template argument type of a &apos;__global__&apos; function',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_closure_type_for_a_lambda_cannot_be_used_in_the_template_argument_type_of_a____global____function',1,'']]],
  ['a_20nonstatic_20member_20reference_20must_20be_20relative_20to_20a_20specific_20object_2',['A nonstatic member reference must be relative to a specific object',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__A_nonstatic_member_reference_must_be_relative_to_a_specific_object',1,'']]],
  ['a_20specific_20object_3',['A nonstatic member reference must be relative to a specific object',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__A_nonstatic_member_reference_must_be_relative_to_a_specific_object',1,'']]],
  ['abm_5f1_5fgamma_4',['Abm_1_gamma',['../classMatrix__Corner__Block.html#afd674000287386818ce4e1a149a36ef3',1,'Matrix_Corner_Block']]],
  ['abm_5f1_5fgamma_5fptr_5',['Abm_1_gamma_ptr',['../classMatrix__Corner__Block.html#a7414c90ca623f4adc9ca5951ef96fe7f',1,'Matrix_Corner_Block']]],
  ['abort_20assert_20or_20static_5fassert_20to_20raise_20an_20error_6',['Should I use abort, assert, or static_assert to raise an error?',['../docs_developer_FAQ.html#docs_developer_FAQ__Should_I_use_abort_assert_or_static_assert_to_raise_an_error',1,'']]],
  ['above_7',['. Combined coordinate transformation which combines two of the coordinate transformations above.',['../src_mapping.html#src_mapping__Combined_coordinate_transformation_which_combines_two_of_the_coordinate_transformations_above',1,'']]],
  ['access_20within_20its_20class_8',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda cannot have private or protected access within its class',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_cannot_have_private_or_protected_access_within_its_class',1,'']]],
  ['accessing_20allocated_20data_9',['Accessing allocated data',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__Accessing_allocated_data',1,'']]],
  ['adding_20documentation_10',['Adding Documentation',['../docs_Adding_docs.html',1,'']]],
  ['address_20to_20be_20taken_11',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda must allow its address to be taken',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_must_allow_its_address_to_be_taken',1,'']]],
  ['addtotypeseq_12',['AddToTypeSeq',['../structconnectivity__details_1_1AddToTypeSeq.html',1,'connectivity_details']]],
  ['addtotypeseq_3c_20toinsert_2c_20typeseq_2c_20backinsert_20_3e_13',['AddToTypeSeq&lt; ToInsert, TypeSeq, BackInsert &gt;',['../structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01BackInsert_01_4.html',1,'connectivity_details']]],
  ['addtotypeseq_3c_20toinsert_2c_20typeseq_2c_20frontinsert_20_3e_14',['AddToTypeSeq&lt; ToInsert, TypeSeq, FrontInsert &gt;',['../structconnectivity__details_1_1AddToTypeSeq_3_01ToInsert_00_01TypeSeq_00_01FrontInsert_01_4.html',1,'connectivity_details']]],
  ['adjust_5findexes_15',['adjust_indexes',['../classMatrix__Centre__Block.html#a7cce0e26c2a0a31b8412a418f988dfb2',1,'Matrix_Centre_Block']]],
  ['advected_5ffunction_16',['advected_function',['../structAdvectionSimulation.html#ad01eab4bc2f1a9ae148eab35f1b1c815',1,'AdvectionSimulation']]],
  ['advection_17',['advection',['../src_advection.html#src_advection__Spatial_advection',1,'Spatial advection'],['../src_advection.html#src_advection__Velocity_advection',1,'Velocity advection']]],
  ['advection_20along_20x_20and_20y_20on_20t_20x_20y_20vx_20vy_18',['Advection along x and y on (t, x, y, vx, vy)',['../tests_advection.html#autotoc_md89',1,'']]],
  ['advection_20along_20x_20on_20t_20x_19',['Advection along x on (t, x)',['../tests_advection.html#autotoc_md87',1,'']]],
  ['advection_20along_20x_20on_20t_20x_20vx_20',['Advection along x on (t, x, vx)',['../tests_advection.html#autotoc_md88',1,'']]],
  ['advection_20domain_21',['advection domain',['../src_advection.html#autotoc_md47',1,'Advection domain'],['../src_geometryRTheta_advection.html#src_geometryRTheta_advection__Advection_domain',1,'Advection domain']]],
  ['advection_20field_22',['advection field',['../src_geometryRTheta_advection.html#src_geometryRTheta_advection__Advection_Field',1,'Advection Field'],['../src_geometryRTheta_advection_field.html#autotoc_md59',1,'Application to the advection field']]],
  ['advection_20field_20along_20the_20logical_20domain_20axis_23',['Advection field along the logical domain axis',['../src_geometryRTheta_advection_field.html#autotoc_md57',1,'']]],
  ['advection_20field_20along_20the_20physical_20domain_20axis_24',['Advection field along the physical domain axis',['../src_geometryRTheta_advection_field.html#autotoc_md56',1,'']]],
  ['advection_20field_20finder_25',['Advection Field finder',['../src_geometryRTheta_advection_field.html',1,'src_geometryRTheta']]],
  ['advection_20methods_26',['Advection methods',['../src_advection.html',1,'src']]],
  ['advection_20operator_27',['advection operator',['../src_geometryRTheta_advection.html',1,'Advection operator'],['../tests_geometryRTheta_advection_rtheta.html',1,'Tests on the 2D polar advection operator'],['../tests_geometryRTheta_advection_rtheta.html#tests_geometryRTheta_advection_rtheta__Tests_on_the_2D_polar_advection_operator',1,'Tests on the 2D polar advection operator']]],
  ['advection_20operators_28',['Tests on the templated advection operators',['../tests_advection.html',1,'tests']]],
  ['advection_20with_20a_20given_20advection_20field_29',['1D advection with a given advection field',['../src_advection.html#src_advection__1D_advection_with_a_given_advection_field',1,'']]],
  ['advection_3a_30',['- The mapping and the domain used for the advection:',['../tests_geometryRTheta_advection_rtheta.html#autotoc_md91',1,'']]],
  ['advection_5ffield_31',['advection_field',['../structAdvectionFieldSimulation.html#ad9b91146d71964104f3ade857f87263d',1,'AdvectionFieldSimulation::advection_field'],['../structAdvectionSimulation.html#a5514ff8c601c1df1602d37c656575c82',1,'AdvectionSimulation::advection_field']]],
  ['advectionfield_5fdecentred_5frotation_32',['advectionfield_decentred_rotation',['../classAdvectionField__decentred__rotation.html',1,'AdvectionField_decentred_rotation'],['../classAdvectionField__decentred__rotation.html#aa438ce9f694bb80d1dc86a99bc59913c',1,'AdvectionField_decentred_rotation::AdvectionField_decentred_rotation()'],['../classAdvectionField__decentred__rotation.html#a5e69f6dd4e295f06e7dac65192dd8494',1,'AdvectionField_decentred_rotation::AdvectionField_decentred_rotation(AdvectionField_decentred_rotation const &amp;)=default']]],
  ['advectionfield_5frotation_33',['advectionfield_rotation',['../classAdvectionField__rotation.html#acdc95a83c02d549e81bbd4f257dc10ca',1,'AdvectionField_rotation::AdvectionField_rotation()'],['../classAdvectionField__rotation.html',1,'AdvectionField_rotation'],['../classAdvectionField__rotation.html#a24804e9420cb6715fa9434df57e980f1',1,'AdvectionField_rotation::AdvectionField_rotation()']]],
  ['advectionfield_5ftranslation_34',['advectionfield_translation',['../classAdvectionField__translation.html#a77d512ab8cb0b4a4d8612228417bcdf3',1,'AdvectionField_translation::AdvectionField_translation()'],['../classAdvectionField__translation.html',1,'AdvectionField_translation'],['../classAdvectionField__translation.html#aef10266e12f74a1b3f2129d6ff849628',1,'AdvectionField_translation::AdvectionField_translation()']]],
  ['advectionfieldfinder_35',['advectionfieldfinder',['../classAdvectionFieldFinder.html',1,'AdvectionFieldFinder&lt; Mapping &gt;'],['../classAdvectionFieldFinder.html#a3086cce87c971e57d63e4ee31c0dadb6',1,'AdvectionFieldFinder::AdvectionFieldFinder()']]],
  ['advectionfieldsimulation_36',['AdvectionFieldSimulation',['../structAdvectionFieldSimulation.html',1,'']]],
  ['advectionsimulation_37',['AdvectionSimulation',['../structAdvectionSimulation.html',1,'']]],
  ['all_5fidx_5franges_38',['all_idx_ranges',['../classMultipatchSplineOnionShapeTest.html#a49d609e758c5e8fbf09eccf5accb8873',1,'MultipatchSplineOnionShapeTest']]],
  ['all_5fpatches_39',['all_patches',['../classMultipatchConnectivity.html#a0683fbe5d61d4239ea8586a70a1305e7',1,'MultipatchConnectivity']]],
  ['allocated_20data_40',['Accessing allocated data',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__Accessing_allocated_data',1,'']]],
  ['allocator_41',['Allocator',['../classVectorFieldMem.html#a86493fc429a78ba32b03e9311c17d202',1,'VectorFieldMem']]],
  ['allow_20its_20address_20to_20be_20taken_42',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda must allow its address to be taken',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_must_allow_its_address_to_be_taken',1,'']]],
  ['alltoall_20transpose_20operator_43',['Alltoall Transpose Operator',['../src_mpi_parallelisation.html#src_mpi_parallelisation__Alltoall_Transpose_Operator',1,'']]],
  ['along_20the_20logical_20domain_20axis_44',['Advection field along the logical domain axis',['../src_geometryRTheta_advection_field.html#autotoc_md57',1,'']]],
  ['along_20the_20physical_20domain_20axis_45',['Advection field along the physical domain axis',['../src_geometryRTheta_advection_field.html#autotoc_md56',1,'']]],
  ['along_20x_20and_20y_20on_20t_20x_20y_20vx_20vy_46',['Advection along x and y on (t, x, y, vx, vy)',['../tests_advection.html#autotoc_md89',1,'']]],
  ['along_20x_20on_20t_20x_47',['Advection along x on (t, x)',['../tests_advection.html#autotoc_md87',1,'']]],
  ['along_20x_20on_20t_20x_20vx_48',['Advection along x on (t, x, vx)',['../tests_advection.html#autotoc_md88',1,'']]],
  ['an_20error_49',['Should I use abort, assert, or static_assert to raise an error?',['../docs_developer_FAQ.html#docs_developer_FAQ__Should_I_use_abort_assert_or_static_assert_to_raise_an_error',1,'']]],
  ['an_20extended_20_5f_5fhost_5f_5f_20_5f_5fdevice_5f_5f_20lambda_20cannot_20have_20private_20or_20protected_20access_20within_20its_20class_50',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda cannot have private or protected access within its class',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_cannot_have_private_or_protected_access_within_its_class',1,'']]],
  ['an_20extended_20_5f_5fhost_5f_5f_20_5f_5fdevice_5f_5f_20lambda_20must_20allow_20its_20address_20to_20be_20taken_51',['The enclosing parent function for an extended &apos;__host__&apos; &apos;__device__&apos; lambda must allow its address to be taken',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_enclosing_parent_function_for_an_extended____host_______device____lambda_must_allow_its_address_to_be_taken',1,'']]],
  ['analytical_20invertible_20mapping_52',['Global analytical invertible mapping',['../src_multipatch_connectivity.html#autotoc_md83',1,'']]],
  ['analytically_20invertible_20coordinate_20transformations_53',['Analytically invertible coordinate transformations',['../src_mapping.html#src_mapping__Analytically_invertible_coordinate_transformations',1,'']]],
  ['and_20associated_20concepts_54',['Indexing and associated concepts',['../docs_DDC_in_gyselalibxx.html#docs_DDC_in_gyselalibxx__Indexing_and_associated_concepts',1,'']]],
  ['and_20bsladvectionvelocity_55',['Same test cases as for BslAdvectionSpatial and BslAdvectionVelocity',['../tests_advection.html#autotoc_md90',1,'']]],
  ['and_20coordinate_20transformation_56',['Sticking and Coordinate Transformation',['../src_multipatch_connectivity.html#autotoc_md79',1,'']]],
  ['and_20data_20structures_57',['Operators and Data Structures',['../docs_getting_started.html#autotoc_md23',1,'']]],
  ['and_20output_58',['Functions used for input and output.',['../src_io.html',1,'src']]],
  ['and_20release_20mode_59',['What is the difference between Debug and Release mode?',['../docs_developer_FAQ.html#docs_developer_FAQ__What_is_the_difference_between_Debug_and_Release_mode',1,'']]],
  ['and_20the_20domain_20used_20for_20the_20advection_3a_60',['- The mapping and the domain used for the advection:',['../tests_geometryRTheta_advection_rtheta.html#autotoc_md91',1,'']]],
  ['and_20y_20on_20t_20x_20y_20vx_20vy_61',['Advection along x and y on (t, x, y, vx, vy)',['../tests_advection.html#autotoc_md89',1,'']]],
  ['annotation_62',['annotation',['../docs_Adding_docs.html#autotoc_md2',1,'Argument annotation'],['../docs_Adding_docs.html#autotoc_md3',1,'Result annotation']]],
  ['application_20to_20the_20advection_20field_63',['Application to the advection field',['../src_geometryRTheta_advection_field.html#autotoc_md59',1,'']]],
  ['apply_5fevaluator_64',['apply_evaluator',['../classMultipatchSplineEvaluator2D.html#a3def2c5f1369f1aea6b42fbea68e2147',1,'MultipatchSplineEvaluator2D']]],
  ['apply_5fintegrate_65',['apply_integrate',['../classMultipatchSplineEvaluator2D.html#a053be081cbf738651cad0794dce5e579',1,'MultipatchSplineEvaluator2D']]],
  ['argument_20annotation_66',['Argument annotation',['../docs_Adding_docs.html#autotoc_md2',1,'']]],
  ['argument_20type_20of_20a_20_5f_5fglobal_5f_5f_20function_67',['The closure type for a lambda cannot be used in the template argument type of a &apos;__global__&apos; function',['../docs_Common_compilation_problems.html#docs_Common_compilation_problems__The_closure_type_for_a_lambda_cannot_be_used_in_the_template_argument_type_of_a____global____function',1,'']]],
  ['as_20for_20bsladvectionspatial_20and_20bsladvectionvelocity_68',['Same test cases as for BslAdvectionSpatial and BslAdvectionVelocity',['../tests_advection.html#autotoc_md90',1,'']]],
  ['assemble_5ffield_5fk_5ftotal_69',['assemble_field_k_total',['../classITimeStepper.html#ace32467b0d2e375becbfe913755d5851',1,'ITimeStepper']]],
  ['assemble_5fk_5ftotal_70',['assemble_k_total',['../classITimeStepper.html#a7d94fc389aad94e1af939a5f32c81edd',1,'ITimeStepper']]],
  ['assemble_5fvector_5ffield_5fk_5ftotal_71',['assemble_vector_field_k_total',['../classITimeStepper.html#a7047fa6fd6122b8dcea1f283461aa2ee',1,'ITimeStepper']]],
  ['assert_20or_20static_5fassert_20to_20raise_20an_20error_72',['Should I use abort, assert, or static_assert to raise an error?',['../docs_developer_FAQ.html#docs_developer_FAQ__Should_I_use_abort_assert_or_static_assert_to_raise_an_error',1,'']]],
  ['associated_20concepts_73',['Indexing and associated concepts',['../docs_DDC_in_gyselalibxx.html#docs_DDC_in_gyselalibxx__Indexing_and_associated_concepts',1,'']]],
  ['associated_5fpatch_74',['associated_patch',['../structEdge.html#a01bafe4f74a4d717a45f57c4f7e023a9',1,'Edge']]],
  ['axis_75',['axis',['../src_geometryRTheta_advection_field.html#autotoc_md57',1,'Advection field along the logical domain axis'],['../src_geometryRTheta_advection_field.html#autotoc_md56',1,'Advection field along the physical domain axis']]]
];
