var searchData=
[
  ['r_1024',['R',['../structR.html',1,'']]],
  ['r1_1025',['R1',['../structR1.html',1,'']]],
  ['r2_1026',['R2',['../structR2.html',1,'']]],
  ['rbasissubset_1027',['RBasisSubset',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RBasisSubset',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rcelldim_1028',['RCellDim',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RCellDim',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rdimprefined_1029',['RDimPRefined',['../structRefinedDiscreteToCartesian_1_1RDimPRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimrrefined_1030',['RDimRRefined',['../structRefinedDiscreteToCartesian_1_1RDimRRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimx_1031',['RDimX',['../structRDimX.html',1,'']]],
  ['rdimxrefined_1032',['RDimXRefined',['../structRefinedDiscreteToCartesian_1_1RDimXRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimy_1033',['RDimY',['../structRDimY.html',1,'']]],
  ['rdimyrefined_1034',['RDimYRefined',['../structRefinedDiscreteToCartesian_1_1RDimYRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['recombinationrate_1035',['RecombinationRate',['../classRecombinationRate.html',1,'']]],
  ['refineddiscretetocartesian_1036',['RefinedDiscreteToCartesian',['../classRefinedDiscreteToCartesian.html',1,'']]],
  ['restartinitialization_1037',['RestartInitialization',['../classRestartInitialization.html',1,'']]],
  ['rk2_1038',['RK2',['../classRK2.html',1,'']]],
  ['rk3_1039',['RK3',['../classRK3.html',1,'']]],
  ['rk4_1040',['RK4',['../classRK4.html',1,'']]],
  ['rotationadvectionfieldsimulation_1041',['RotationAdvectionFieldSimulation',['../classRotationAdvectionFieldSimulation.html',1,'']]],
  ['rotationsimulation_1042',['RotationSimulation',['../classRotationSimulation.html',1,'']]]
];
