var searchData=
[
  ['rbasissubset_612',['RBasisSubset',['../classPolarSplineFEMPoissonSolver.html#structPolarSplineFEMPoissonSolver_1_1RBasisSubset',1,'PolarSplineFEMPoissonSolver']]],
  ['rcelldim_613',['RCellDim',['../classPolarSplineFEMPoissonSolver.html#structPolarSplineFEMPoissonSolver_1_1RCellDim',1,'PolarSplineFEMPoissonSolver']]],
  ['rdimp_614',['RDimP',['../structRDimP.html',1,'']]],
  ['rdimprefined_615',['RDimPRefined',['../structRefinedDiscreteToCartesian_1_1RDimPRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimr_616',['RDimR',['../structRDimR.html',1,'']]],
  ['rdimrrefined_617',['RDimRRefined',['../structRefinedDiscreteToCartesian_1_1RDimRRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimt_618',['RDimT',['../structRDimT.html',1,'']]],
  ['rdimvp_619',['RDimVp',['../structRDimVp.html',1,'']]],
  ['rdimvr_620',['RDimVr',['../structRDimVr.html',1,'']]],
  ['rdimvx_621',['RDimVx',['../structRDimVx.html',1,'']]],
  ['rdimvy_622',['RDimVy',['../structRDimVy.html',1,'']]],
  ['rdimx_623',['RDimX',['../structRDimX.html',1,'']]],
  ['rdimxrefined_624',['RDimXRefined',['../structRefinedDiscreteToCartesian_1_1RDimXRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimy_625',['RDimY',['../structRDimY.html',1,'']]],
  ['rdimyrefined_626',['RDimYRefined',['../structRefinedDiscreteToCartesian_1_1RDimYRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['refineddiscretetocartesian_627',['RefinedDiscreteToCartesian',['../classRefinedDiscreteToCartesian.html',1,'']]],
  ['restartinitialization_628',['RestartInitialization',['../classRestartInitialization.html',1,'']]],
  ['rk2_629',['RK2',['../classRK2.html',1,'']]],
  ['rk3_630',['RK3',['../classRK3.html',1,'']]],
  ['rk4_631',['RK4',['../classRK4.html',1,'']]],
  ['rotationsimulation_632',['RotationSimulation',['../classRotationSimulation.html',1,'']]]
];
