var searchData=
[
  ['gausslegendre_0',['GaussLegendre',['../classGaussLegendre.html',1,'']]],
  ['gausslegendrecoefficients_1',['GaussLegendreCoefficients',['../structGaussLegendreCoefficients.html',1,'']]],
  ['geometryvxvyxy_2',['GeometryVxVyXY',['../classGeometryVxVyXY.html',1,'']]],
  ['geometryxvx_3',['GeometryXVx',['../classGeometryXVx.html',1,'']]],
  ['geometryxyvxvy_4',['GeometryXYVxVy',['../classGeometryXYVxVy.html',1,'']]],
  ['getcontravariantdims_5',['GetContravariantDims',['../namespacetensor__tools.html#structtensor__tools_1_1GetContravariantDims',1,'tensor_tools']]],
  ['getcontravariantdims_3c_20vectorindexset_3c_20dims_2e_2e_2e_20_3e_20_3e_6',['GetContravariantDims&lt; VectorIndexSet&lt; Dims... &gt; &gt;',['../namespacetensor__tools.html#structtensor__tools_1_1GetContravariantDims_3_01VectorIndexSet_3_01Dims_8_8_8_01_4_01_4',1,'tensor_tools']]],
  ['getcovariantdims_7',['GetCovariantDims',['../namespacetensor__tools.html#structtensor__tools_1_1GetCovariantDims',1,'tensor_tools']]],
  ['getcovariantdims_3c_20vectorindexset_3c_20dims_2e_2e_2e_20_3e_20_3e_8',['GetCovariantDims&lt; VectorIndexSet&lt; Dims... &gt; &gt;',['../namespacetensor__tools.html#structtensor__tools_1_1GetCovariantDims_3_01VectorIndexSet_3_01Dims_8_8_8_01_4_01_4',1,'tensor_tools']]],
  ['ghostedvx_9',['GhostedVx',['../structCollisionsIntra_1_1GhostedVx.html',1,'CollisionsIntra']]],
  ['ghostedvxstaggered_10',['GhostedVxStaggered',['../structCollisionsIntra_1_1GhostedVxStaggered.html',1,'CollisionsIntra']]],
  ['gridbuilder_11',['GridBuilder',['../classGridBuilder.html',1,'']]],
  ['gridfourier_12',['GridFourier',['../structFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace2aeecfe91d464f5738599cc105fb6087.html',1,'FFTPoissonSolver&lt; IdxRange&lt; GridPDEDim1D... &gt;, IdxRangeFull, ExecSpace, LayoutSpace &gt;']]],
  ['gridmom_13',['GridMom',['../structGridMom.html',1,'']]],
  ['gridmu_14',['GridMu',['../structGridMu.html',1,'']]],
  ['gridpdedimq_15',['GridPDEDimQ',['../structFEM1DPoissonSolver_1_1GridPDEDimQ.html',1,'FEM1DPoissonSolver']]],
  ['gridr_16',['gridr',['../structGEOM__NAMESPACE__NAME_1_1GridR.html',1,'GEOM_NAMESPACE_NAME::GridR&lt; PatchIdx &gt;'],['../structGridR.html',1,'GridR']]],
  ['gridrrefined_17',['GridRRefined',['../structRefinedDiscreteToCartesianBuilder_1_1GridRRefined.html',1,'RefinedDiscreteToCartesianBuilder']]],
  ['gridtheta_18',['gridtheta',['../structGEOM__NAMESPACE__NAME_1_1GridTheta.html',1,'GEOM_NAMESPACE_NAME::GridTheta&lt; PatchIdx &gt;'],['../structGridTheta.html',1,'GridTheta']]],
  ['gridthetarefined_19',['GridThetaRefined',['../structRefinedDiscreteToCartesianBuilder_1_1GridThetaRefined.html',1,'RefinedDiscreteToCartesianBuilder']]],
  ['gridvpar_20',['GridVpar',['../structGridVpar.html',1,'']]],
  ['gridvx_21',['GridVx',['../structGridVx.html',1,'']]],
  ['gridvy_22',['GridVy',['../structGridVy.html',1,'']]],
  ['gridx_23',['gridx',['../structfigure__of__eight__5patches_1_1GridX.html',1,'figure_of_eight_5patches::GridX&lt; PatchIdx &gt;'],['../structGEOM__NAMESPACE__NAME_1_1GridX.html',1,'GEOM_NAMESPACE_NAME::GridX&lt; PatchIdx &gt;'],['../structGridX.html',1,'GridX'],['../structperiodic__strips__uniform__2d__9patches_1_1GridX.html',1,'periodic_strips_uniform_2d_9patches::GridX&lt; PatchIdx &gt;']]],
  ['gridy_24',['gridy',['../structfigure__of__eight__5patches_1_1GridY.html',1,'figure_of_eight_5patches::GridY&lt; PatchIdx &gt;'],['../structGEOM__NAMESPACE__NAME_1_1GridY.html',1,'GEOM_NAMESPACE_NAME::GridY&lt; PatchIdx &gt;'],['../structGridY.html',1,'GridY'],['../structperiodic__strips__uniform__2d__9patches_1_1GridY.html',1,'periodic_strips_uniform_2d_9patches::GridY&lt; PatchIdx &gt;']]]
];
