var searchData=
[
  ['gausslegendre_0',['GaussLegendre',['../classGaussLegendre.html',1,'']]],
  ['gausslegendrecoefficients_1',['GaussLegendreCoefficients',['../structGaussLegendreCoefficients.html',1,'']]],
  ['geometryxvx_2',['GeometryXVx',['../classGeometryXVx.html',1,'']]],
  ['geometryxyvxvy_3',['GeometryXYVxVy',['../classGeometryXYVxVy.html',1,'']]],
  ['ghostedvx_4',['GhostedVx',['../structCollisionsIntra_1_1GhostedVx.html',1,'CollisionsIntra']]],
  ['ghostedvxstaggered_5',['GhostedVxStaggered',['../structCollisionsIntra_1_1GhostedVxStaggered.html',1,'CollisionsIntra']]],
  ['gridbuilder_6',['GridBuilder',['../classGridBuilder.html',1,'']]],
  ['gridfourier_7',['GridFourier',['../structFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01IdxRangeFull_00_01ExecSpace2aeecfe91d464f5738599cc105fb6087.html',1,'FFTPoissonSolver&lt; IdxRange&lt; GridPDEDim1D... &gt;, IdxRangeFull, ExecSpace, LayoutSpace &gt;']]],
  ['gridmom_8',['GridMom',['../structGridMom.html',1,'']]],
  ['gridmu_9',['GridMu',['../structGridMu.html',1,'']]],
  ['gridpdedimq_10',['GridPDEDimQ',['../structFEM1DPoissonSolver_1_1GridPDEDimQ.html',1,'FEM1DPoissonSolver']]],
  ['gridr_11',['gridr',['../structGridR.html',1,'GridR'],['../structonion__shape__uniform__2d__2patches_1_1GridR.html',1,'onion_shape_uniform_2d_2patches::GridR&lt; PatchIdx &gt;'],['../structonion__shape__non__uniform__2d__2patches_1_1GridR.html',1,'onion_shape_non_uniform_2d_2patches::GridR&lt; PatchIdx &gt;']]],
  ['gridrrefined_12',['GridRRefined',['../structRefinedDiscreteToCartesianBuilder_1_1GridRRefined.html',1,'RefinedDiscreteToCartesianBuilder']]],
  ['gridtheta_13',['gridtheta',['../structGridTheta.html',1,'GridTheta'],['../structonion__shape__non__uniform__2d__2patches_1_1GridTheta.html',1,'onion_shape_non_uniform_2d_2patches::GridTheta&lt; PatchIdx &gt;'],['../structonion__shape__uniform__2d__2patches_1_1GridTheta.html',1,'onion_shape_uniform_2d_2patches::GridTheta&lt; PatchIdx &gt;']]],
  ['gridthetarefined_14',['GridThetaRefined',['../structRefinedDiscreteToCartesianBuilder_1_1GridThetaRefined.html',1,'RefinedDiscreteToCartesianBuilder']]],
  ['gridtor1_15',['GridTor1',['../structGridTor1.html',1,'']]],
  ['gridtor2_16',['GridTor2',['../structGridTor2.html',1,'']]],
  ['gridtor3_17',['GridTor3',['../structGridTor3.html',1,'']]],
  ['gridvpar_18',['GridVpar',['../structGridVpar.html',1,'']]],
  ['gridvx_19',['GridVx',['../structGridVx.html',1,'']]],
  ['gridvy_20',['GridVy',['../structGridVy.html',1,'']]],
  ['gridx_21',['gridx',['../structnon__periodic__uniform__2d__2patches_1_1GridX.html',1,'non_periodic_uniform_2d_2patches::GridX&lt; PatchIdx &gt;'],['../structperiodic__strips__uniform__2d__9patches_1_1GridX.html',1,'periodic_strips_uniform_2d_9patches::GridX&lt; PatchIdx &gt;'],['../structnon__periodic__uniform__2d__3patches_1_1GridX.html',1,'non_periodic_uniform_2d_3patches::GridX&lt; PatchIdx &gt;'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridX.html',1,'non_periodic_non_uniform_2d_3patches::GridX&lt; PatchIdx &gt;'],['../structnon__periodic__non__uniform__2d__2patches_1_1GridX.html',1,'non_periodic_non_uniform_2d_2patches::GridX&lt; PatchIdx &gt;'],['../structGridX.html',1,'GridX'],['../structfigure__of__eight__5patches_1_1GridX.html',1,'figure_of_eight_5patches::GridX&lt; PatchIdx &gt;']]],
  ['gridy_22',['gridy',['../structfigure__of__eight__5patches_1_1GridY.html',1,'figure_of_eight_5patches::GridY&lt; PatchIdx &gt;'],['../structGridY.html',1,'GridY'],['../structnon__periodic__non__uniform__2d__2patches_1_1GridY.html',1,'non_periodic_non_uniform_2d_2patches::GridY&lt; PatchIdx &gt;'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridY.html',1,'non_periodic_non_uniform_2d_3patches::GridY&lt; PatchIdx &gt;'],['../structnon__periodic__uniform__2d__2patches_1_1GridY.html',1,'non_periodic_uniform_2d_2patches::GridY&lt; PatchIdx &gt;'],['../structnon__periodic__uniform__2d__3patches_1_1GridY.html',1,'non_periodic_uniform_2d_3patches::GridY&lt; PatchIdx &gt;'],['../structperiodic__strips__uniform__2d__9patches_1_1GridY.html',1,'periodic_strips_uniform_2d_9patches::GridY&lt; PatchIdx &gt;']]]
];
