var searchData=
[
  ['r_1115',['R',['../structR.html',1,'']]],
  ['r1_1116',['R1',['../structonion__shape__uniform__2d__2patches_1_1R1.html',1,'onion_shape_uniform_2d_2patches']]],
  ['r2_1117',['R2',['../structonion__shape__uniform__2d__2patches_1_1R2.html',1,'onion_shape_uniform_2d_2patches']]],
  ['rbasissubset_1118',['RBasisSubset',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RBasisSubset',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rcelldim_1119',['RCellDim',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RCellDim',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rdimprefined_1120',['RDimPRefined',['../structRefinedDiscreteToCartesian_1_1RDimPRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimrrefined_1121',['RDimRRefined',['../structRefinedDiscreteToCartesian_1_1RDimRRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimxrefined_1122',['RDimXRefined',['../structRefinedDiscreteToCartesian_1_1RDimXRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimyrefined_1123',['RDimYRefined',['../structRefinedDiscreteToCartesian_1_1RDimYRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['recombinationrate_1124',['RecombinationRate',['../classRecombinationRate.html',1,'']]],
  ['refineddiscretetocartesian_1125',['RefinedDiscreteToCartesian',['../classRefinedDiscreteToCartesian.html',1,'']]],
  ['restartinitialization_1126',['RestartInitialization',['../classRestartInitialization.html',1,'']]],
  ['rk2_1127',['RK2',['../classRK2.html',1,'']]],
  ['rk3_1128',['RK3',['../classRK3.html',1,'']]],
  ['rk4_1129',['RK4',['../classRK4.html',1,'']]],
  ['rotationadvectionfieldsimulation_1130',['RotationAdvectionFieldSimulation',['../classRotationAdvectionFieldSimulation.html',1,'']]],
  ['rotationsimulation_1131',['RotationSimulation',['../classRotationSimulation.html',1,'']]]
];
