var searchData=
[
  ['patch_1158',['Patch',['../structPatch.html',1,'']]],
  ['patch_3c_20grid1_2c_20grid2_2c_20bsplines_5fdim1_2c_20bsplines_5fdim2_20_3e_1159',['Patch&lt; grid1, grid2, bsplines_dim1, bsplines_dim2 &gt;',['../structPatch_3_01grid1_00_01grid2_00_01bsplines__dim1_00_01bsplines__dim2_01_4.html',1,'']]],
  ['patchconnection_1160',['PatchConnection',['../structconnectivity__details_1_1PatchConnection.html',1,'connectivity_details']]],
  ['patchconnection_3c_20patch_2c_20ddc_3a_3adetail_3a_3atypeseq_3c_20interfacetype_20_3e_20_3e_1161',['PatchConnection&lt; Patch, ddc::detail::TypeSeq&lt; InterfaceType &gt; &gt;',['../structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01InterfaceType_01_4_01_4.html',1,'connectivity_details']]],
  ['patchconnection_3c_20patch_2c_20ddc_3a_3adetail_3a_3atypeseq_3c_20interfacetype1_2c_20remaininginterfacetypes_2e_2e_2e_20_3e_20_3e_1162',['PatchConnection&lt; Patch, ddc::detail::TypeSeq&lt; InterfaceType1, RemainingInterfaceTypes... &gt; &gt;',['../structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_01Interd9a0a5e7aafe0b71fe7c76720b7c5da6.html',1,'connectivity_details']]],
  ['patchconnection_3c_20patch_2c_20ddc_3a_3adetail_3a_3atypeseq_3c_3e_20_3e_1163',['PatchConnection&lt; Patch, ddc::detail::TypeSeq&lt;&gt; &gt;',['../structconnectivity__details_1_1PatchConnection_3_01Patch_00_01ddc_1_1detail_1_1TypeSeq_3_4_01_4.html',1,'connectivity_details']]],
  ['poissonlikerhsfunction_1164',['PoissonLikeRHSFunction',['../classPoissonLikeRHSFunction.html',1,'']]],
  ['poissonsolution_1165',['PoissonSolution',['../classPoissonSolution.html',1,'']]],
  ['polarbsplines_1166',['PolarBSplines',['../classPolarBSplines.html',1,'']]],
  ['polarbsplines_3c_20bsplinesr_2c_20bsplinestheta_2c_201_20_3e_1167',['PolarBSplines&lt; BSplinesR, BSplinesTheta, 1 &gt;',['../classPolarBSplines.html',1,'']]],
  ['polarbsplinesrtheta_1168',['PolarBSplinesRTheta',['../structPolarBSplinesRTheta.html',1,'']]],
  ['polarspline_1169',['PolarSpline',['../structPolarSpline.html',1,'']]],
  ['polarsplineevaluator_1170',['PolarSplineEvaluator',['../classPolarSplineEvaluator.html',1,'']]],
  ['polarsplineevaluator_3c_20polarbsplinesrtheta_2c_20ddc_3a_3anullextrapolationrule_2c_20kokkos_3a_3ahostspace_20_3e_1171',['PolarSplineEvaluator&lt; PolarBSplinesRTheta, ddc::NullExtrapolationRule, Kokkos::HostSpace &gt;',['../classPolarSplineEvaluator.html',1,'']]],
  ['polarsplinefempoissonlikesolver_1172',['PolarSplineFEMPoissonLikeSolver',['../classPolarSplineFEMPoissonLikeSolver.html',1,'']]],
  ['polarsplinespan_1173',['PolarSplineSpan',['../structPolarSplineSpan.html',1,'']]],
  ['polarsplineview_1174',['PolarSplineView',['../structPolarSplineView.html',1,'']]],
  ['polynomialevaluator_1175',['PolynomialEvaluator',['../structPolynomialEvaluator.html',1,'']]],
  ['preallocatablelagrangeinterpolator_1176',['PreallocatableLagrangeInterpolator',['../classPreallocatableLagrangeInterpolator.html',1,'']]],
  ['preallocatablesplineinterpolator_1177',['PreallocatableSplineInterpolator',['../classPreallocatableSplineInterpolator.html',1,'']]],
  ['preallocatablesplineinterpolatorrtheta_1178',['PreallocatableSplineInterpolatorRTheta',['../classPreallocatableSplineInterpolatorRTheta.html',1,'']]],
  ['preallocatablesplineinterpolatorrtheta_3c_20ddc_3a_3anullextrapolationrule_20_3e_1179',['PreallocatableSplineInterpolatorRTheta&lt; ddc::NullExtrapolationRule &gt;',['../classPreallocatableSplineInterpolatorRTheta.html',1,'']]],
  ['predcorr_1180',['PredCorr',['../classPredCorr.html',1,'']]],
  ['predcorrrk2xy_1181',['PredCorrRK2XY',['../classPredCorrRK2XY.html',1,'']]],
  ['pseudocartesiancompatiblemapping_1182',['PseudoCartesianCompatibleMapping',['../classPseudoCartesianCompatibleMapping.html',1,'']]]
];
