var searchData=
[
  ['gausslegendre_959',['GaussLegendre',['../classGaussLegendre.html',1,'']]],
  ['gausslegendrecoefficients_960',['GaussLegendreCoefficients',['../structGaussLegendreCoefficients.html',1,'']]],
  ['geometryxvx_961',['GeometryXVx',['../classGeometryXVx.html',1,'']]],
  ['geometryxyvxvy_962',['GeometryXYVxVy',['../classGeometryXYVxVy.html',1,'']]],
  ['ghostedvx_963',['GhostedVx',['../structCollisionsIntra_1_1GhostedVx.html',1,'CollisionsIntra']]],
  ['ghostedvxstaggered_964',['GhostedVxStaggered',['../structCollisionsIntra_1_1GhostedVxStaggered.html',1,'CollisionsIntra']]],
  ['gridbuilder_965',['GridBuilder',['../classGridBuilder.html',1,'']]],
  ['gridfourier_966',['GridFourier',['../structFFTPoissonSolver_3_01IdxRange_3_01GridPDEDim1D_8_8_8_01_4_00_01FullIdxRange_00_01ExecSpace0e5661b22cfccf10bc7f0f673649be85.html',1,'FFTPoissonSolver&lt; IdxRange&lt; GridPDEDim1D... &gt;, FullIdxRange, ExecSpace, LayoutSpace &gt;']]],
  ['gridmom_967',['GridMom',['../structGridMom.html',1,'']]],
  ['gridmu_968',['GridMu',['../structGridMu.html',1,'']]],
  ['gridp1_969',['GridP1',['../structonion__shape__uniform__2d__2patches_1_1GridP1.html',1,'onion_shape_uniform_2d_2patches']]],
  ['gridp2_970',['GridP2',['../structonion__shape__uniform__2d__2patches_1_1GridP2.html',1,'onion_shape_uniform_2d_2patches']]],
  ['gridpdedimq_971',['GridPDEDimQ',['../structFEM1DPoissonSolver_1_1GridPDEDimQ.html',1,'FEM1DPoissonSolver']]],
  ['gridr_972',['GridR',['../structGridR.html',1,'']]],
  ['gridr1_973',['GridR1',['../structonion__shape__uniform__2d__2patches_1_1GridR1.html',1,'onion_shape_uniform_2d_2patches']]],
  ['gridr2_974',['GridR2',['../structonion__shape__uniform__2d__2patches_1_1GridR2.html',1,'onion_shape_uniform_2d_2patches']]],
  ['gridtheta_975',['GridTheta',['../structGridTheta.html',1,'']]],
  ['gridtor1_976',['GridTor1',['../structGridTor1.html',1,'']]],
  ['gridtor2_977',['GridTor2',['../structGridTor2.html',1,'']]],
  ['gridtor3_978',['GridTor3',['../structGridTor3.html',1,'']]],
  ['gridvpar_979',['GridVpar',['../structGridVpar.html',1,'']]],
  ['gridvx_980',['GridVx',['../structGridVx.html',1,'']]],
  ['gridvy_981',['GridVy',['../structGridVy.html',1,'']]],
  ['gridx_982',['GridX',['../structfigure__of__eight__5patches_1_1GridX.html',1,'figure_of_eight_5patches::GridX&lt; PatchIdx &gt;'],['../structGridX.html',1,'GridX'],['../structperiodic__strips__uniform__2d__9patches_1_1GridX.html',1,'periodic_strips_uniform_2d_9patches::GridX&lt; PatchIdx &gt;']]],
  ['gridx1_983',['GridX1',['../structnon__periodic__non__uniform__2d__2patches_1_1GridX1.html',1,'non_periodic_non_uniform_2d_2patches::GridX1'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridX1.html',1,'non_periodic_non_uniform_2d_3patches::GridX1'],['../structnon__periodic__uniform__2d__2patches_1_1GridX1.html',1,'non_periodic_uniform_2d_2patches::GridX1'],['../structnon__periodic__uniform__2d__3patches_1_1GridX1.html',1,'non_periodic_uniform_2d_3patches::GridX1']]],
  ['gridx2_984',['GridX2',['../structnon__periodic__non__uniform__2d__2patches_1_1GridX2.html',1,'non_periodic_non_uniform_2d_2patches::GridX2'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridX2.html',1,'non_periodic_non_uniform_2d_3patches::GridX2'],['../structnon__periodic__uniform__2d__2patches_1_1GridX2.html',1,'non_periodic_uniform_2d_2patches::GridX2'],['../structnon__periodic__uniform__2d__3patches_1_1GridX2.html',1,'non_periodic_uniform_2d_3patches::GridX2']]],
  ['gridx3_985',['GridX3',['../structnon__periodic__non__uniform__2d__3patches_1_1GridX3.html',1,'non_periodic_non_uniform_2d_3patches::GridX3'],['../structnon__periodic__uniform__2d__3patches_1_1GridX3.html',1,'non_periodic_uniform_2d_3patches::GridX3']]],
  ['gridy_986',['GridY',['../structfigure__of__eight__5patches_1_1GridY.html',1,'figure_of_eight_5patches::GridY&lt; PatchIdx &gt;'],['../structGridY.html',1,'GridY'],['../structperiodic__strips__uniform__2d__9patches_1_1GridY.html',1,'periodic_strips_uniform_2d_9patches::GridY&lt; PatchIdx &gt;']]],
  ['gridy1_987',['GridY1',['../structnon__periodic__non__uniform__2d__2patches_1_1GridY1.html',1,'non_periodic_non_uniform_2d_2patches::GridY1'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridY1.html',1,'non_periodic_non_uniform_2d_3patches::GridY1'],['../structnon__periodic__uniform__2d__2patches_1_1GridY1.html',1,'non_periodic_uniform_2d_2patches::GridY1'],['../structnon__periodic__uniform__2d__3patches_1_1GridY1.html',1,'non_periodic_uniform_2d_3patches::GridY1']]],
  ['gridy2_988',['GridY2',['../structnon__periodic__non__uniform__2d__2patches_1_1GridY2.html',1,'non_periodic_non_uniform_2d_2patches::GridY2'],['../structnon__periodic__non__uniform__2d__3patches_1_1GridY2.html',1,'non_periodic_non_uniform_2d_3patches::GridY2'],['../structnon__periodic__uniform__2d__2patches_1_1GridY2.html',1,'non_periodic_uniform_2d_2patches::GridY2'],['../structnon__periodic__uniform__2d__3patches_1_1GridY2.html',1,'non_periodic_uniform_2d_3patches::GridY2']]],
  ['gridy3_989',['GridY3',['../structnon__periodic__non__uniform__2d__3patches_1_1GridY3.html',1,'non_periodic_non_uniform_2d_3patches::GridY3'],['../structnon__periodic__uniform__2d__3patches_1_1GridY3.html',1,'non_periodic_uniform_2d_3patches::GridY3']]]
];
