var searchData=
[
  ['r_1110',['R',['../structR.html',1,'']]],
  ['r1_1111',['R1',['../structonion__shape__uniform__2d__2patches_1_1R1.html',1,'onion_shape_uniform_2d_2patches']]],
  ['r2_1112',['R2',['../structonion__shape__uniform__2d__2patches_1_1R2.html',1,'onion_shape_uniform_2d_2patches']]],
  ['rbasissubset_1113',['RBasisSubset',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RBasisSubset',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rcelldim_1114',['RCellDim',['../classPolarSplineFEMPoissonLikeSolver.html#structPolarSplineFEMPoissonLikeSolver_1_1RCellDim',1,'PolarSplineFEMPoissonLikeSolver']]],
  ['rdimprefined_1115',['RDimPRefined',['../structRefinedDiscreteToCartesian_1_1RDimPRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimrrefined_1116',['RDimRRefined',['../structRefinedDiscreteToCartesian_1_1RDimRRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimxrefined_1117',['RDimXRefined',['../structRefinedDiscreteToCartesian_1_1RDimXRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['rdimyrefined_1118',['RDimYRefined',['../structRefinedDiscreteToCartesian_1_1RDimYRefined.html',1,'RefinedDiscreteToCartesian']]],
  ['recombinationrate_1119',['RecombinationRate',['../classRecombinationRate.html',1,'']]],
  ['refineddiscretetocartesian_1120',['RefinedDiscreteToCartesian',['../classRefinedDiscreteToCartesian.html',1,'']]],
  ['restartinitialization_1121',['RestartInitialization',['../classRestartInitialization.html',1,'']]],
  ['rk2_1122',['RK2',['../classRK2.html',1,'']]],
  ['rk3_1123',['RK3',['../classRK3.html',1,'']]],
  ['rk4_1124',['RK4',['../classRK4.html',1,'']]],
  ['rotationadvectionfieldsimulation_1125',['RotationAdvectionFieldSimulation',['../classRotationAdvectionFieldSimulation.html',1,'']]],
  ['rotationsimulation_1126',['RotationSimulation',['../classRotationSimulation.html',1,'']]]
];
