name: "Set draft"

inputs:
  status:
    description: "The final status of the tests that were running [success|failure|etc]"
    required: true
  pr_number:
    description: "The number of the PR for which the status is reported"
    required: true
  sha:
    description: "The SHA the tests were run on"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - if: github.repository == 'gyselax/gyselalibxx' && inputs.status == 'success'
      run: |
        STATES=$(gh pr checks ${{ inputs.pr_number }} --required --json state)
        N_PASSES=$(echo $STATES | grep -o "\"state\":\"SUCCESS\"" | wc -l)
        if (( ${N_PASSES} >= 10 ))
        then
          # If all required tests (except GPU) are passing then mark as ready to review
          gh pr edit ${{ inputs.pr_number }} --add-label "Ready to review"
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}

    - if: github.repository == 'gyselax/gyselalibxx' && inputs.status == 'failure'
      # If any required tests are failing
      run: |
        LATEST_SHA=$(gh pr view ${{ inputs.pr_number }} --json headRefOid --jq '.["headRefOid"]')
        if [[ "${LATEST_SHA}" == "${{ inputs.sha }}" ]]
        then
          # If the PR hasn't been modified since then put it into draft
          gh pr comment ${{ github.event.pull_request.number }} -b "This PR is failing tests so it has been put back into draft. Please remove the draft status when the tests pass."
          gh pr ready ${{ github.event.pull_request.number }} --undo
        else
          # If the PR has been modified then cancel any runs associated with this SHA
          RUNNING_WORKFLOWS=$(gh run list --commit ${{ inputs.sha }} --json databaseId,status --jq '.[] | select(.status == "completed") | .["databaseId"]')
          for workflow_id in ${RUNNING_WORKFLOWS}
          do
            gh run cancel ${workflow_id}
          done
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
