#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
"""
diagnostic of energy conservation equation:
     d(pi)/dt + 2*sqrt(1/m)*d(Q)/dx = -S_Es + 2sqrt(1/m)nuqE
"""
import os

from argparse import ArgumentParser
from pathlib import Path

import numpy as np

from gysdata import DiskStore
from plot_utils import plot_field1d, plot_field2d
from math_utils import compute_moment, differentiate
from geometryXVx.utils import compute_krook_sink_constant, compute_kinetic_source


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the energy conservation equation error')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    path_data_structure = Path('data_structure_sheath.yaml')
    ds = DiskStore(args.data_dir, data_structure=path_data_structure)
    fdistribu = ds['fdistribu']
    electric_field = -ds['electrostatic_potential'].differentiate('x')
    charge = ds['fdistribu_charges']
    mass = ds['fdistribu_masses']

    density = compute_moment(fdistribu, 'v_x', moment_order=0)
    particle_flux = compute_moment(fdistribu, 'v_x', moment_order=1)
    momentum_flux = compute_moment(fdistribu, 'v_x', moment_order=2)
    energy_flux = compute_moment(fdistribu, 'v_x', moment_order=3)

    momentum_flux = momentum_flux.chunk({'time': len(momentum_flux['time'])})
    dmomentum_flux_dt = differentiate(momentum_flux, 'time')
    grad_flux_over_m = differentiate(energy_flux, 'x') / np.sqrt(mass)
    force_term = 2*particle_flux*charge/np.sqrt(mass)*electric_field
    energy_source = compute_moment(compute_krook_sink_constant(ds), 'v_x', moment_order=2) \
            + compute_moment(compute_kinetic_source(ds), 'v_x', moment_order=2)
    error = dmomentum_flux_dt + grad_flux_over_m - energy_source - force_term

    time_diag = fdistribu.coords['time'].values[args.itime]
    for species in density.coords['species'].values:
        title = f'energy conservation equation error {species}'
        output_filename = os.path.join(Path.cwd(), f'energy_conservation_error_{species}_xt.png')
        plot_field2d(error.sel(species=species),
                     title,
                     output_filename,
                     scale='linear',
                     cmap='viridis')

        output_filename = os.path.join(Path.cwd(), f'energy_conservation_error_{species}_t{time_diag}.png')
        data_dict = {r'$\partial_t \Pi_{s}$': dmomentum_flux_dt.sel(species=species, time=time_diag),
                     r'$\sqrt{A_s}\partial_x Q_{s}$': grad_flux_over_m.sel(species=species, time=time_diag),
                     r'$- 2\sqrt{A_s}q_{s}\Gamma_{s}E$': force_term.sel(species=species, time=time_diag),
                     r'$S_{hs}$': energy_source.sel(species=species, time=time_diag),
                     r'lhs-rhs': error.sel(species=species, time=time_diag)}

        plot_field1d(data_dict, title, output_filename)
