spack:
  definitions:
  - packages:
    - cmake@3.31
    - 'ddc@0.15 +fft +pdi +splines'
    - ginkgo@1.11 ~openmp +rocm amdgpu_target=gfx90a
    - gmgpolar@2.3
    - googletest@1.17 +gmock
    - kokkos@5.1 ~openmp +rocm amdgpu_target=gfx90a
    - kokkos-kernels@5.1 ~shared
    - kokkos-tools@git.3d33d0a783c5321d6981b3b4e43d3c157d2ca887=develop
    - 'koliop@0.2'
    - lapack
    - mpi
    - ninja@1.13
    - paraconf@1.0
    - pdi@1.11
    - pdiplugin-decl-hdf5@1.11 +mpi
    - pdiplugin-decl-netcdf@1.11 +mpi
    - pdiplugin-mpi@1.11
    - pdiplugin-pycall@1.11
    - pdiplugin-set-value@1.11
    - pdiplugin-trace@1.11
    - 'python@3.14'

    - py-dask
    - py-h5py
    - py-imageio
    - py-matplotlib
    - py-netcdf4 +mpi
    - py-numpy
    - py-pyyaml
    - py-scipy
    - py-sympy
    - py-xarray
  - architectures:
    - arch=linux-rhel8-zen3
  specs:
  - matrix:
    - [$packages]
    - [$architectures]
  repos:
    patches:
      git: https://github.com/gyselax/spack.git
      branch: releases/v2026.06
      paths:
        - spack_repo/patches_adastra
        - spack_repo/patches_common
    builtin:
      tag: v2026.06.0
  concretizer:
    unify: true
    reuse: false
    duplicates:
      strategy: none
  packages:
    all:
      permissions:
        read: world
        write: group
      variants: ~fortran ~mpi
    c:
      require: gcc@13.3.1
    cxx:
      require: gcc@13.3.1
    kokkos-fft:
      require: 'host_backend=fftw-serial'
    lapack:
      require: openblas@0.3
    mpi:
      require: cray-mpich
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
  modules:
    default:
      roots: {}
      enable: []
  view: false
