spack:
  concretizer:
    unify: true
  definitions:
  - compilers:
    - 'gcc@11'
  - packages:
    - 'cmake@3.22:3'
    - 'cuda@12.3:12.9'
    - 'gdb'
    - 'ginkgo@1.9 +cuda cuda_arch=70 +openmp'
    - 'googletest +gmock'
    - 'kokkos@4.6:4 ~shared +wrapper +cuda +cuda_constexpr +cuda_relocatable_device_code cuda_arch=70 +openmp'
    - 'kokkos-fft@0.3 host_backend=fftw-openmp device_backend=cufft'
    - 'kokkos-kernels@4.6:4 ~shared'
    - 'kokkos-tools'
    - 'ninja'
    - 'openmpi +cuda'
    - 'paraconf@1'
    - 'pdi@1.6:1'
    - 'pdiplugin-decl-hdf5 +mpi'
    - 'pdiplugin-decl-netcdf +mpi'
    - 'pdiplugin-mpi'
    - 'pdiplugin-set-value'
    - 'pdiplugin-trace'
  - python-packages:
    - 'py-dask'
    - 'py-h5py'
    - 'py-imageio'
    - 'py-matplotlib'
    - 'py-netcdf4 +mpi'
    - 'py-numpy'
    - 'py-pyyaml'
    - 'py-scipy'
    - 'py-sympy'
    - 'py-xarray'
  specs:
  - lapack
  - matrix:
    - [$packages]
    - [$%compilers]
  - matrix:
    - [$python-packages]
    - [$%compilers]
  view:
    default:
      root: .spack-env/view
      exclude: ['gcc-runtime']
  packages:
    all:
      variants: ~mpi +openmp cxxstd=17
