name: "Build code"

inputs:
  toolchain:
    description: "The toolchain that describes the parameters for cmake"
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile code
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ inputs.toolchain }} -B build -S .
        cmake --build build --parallel 4
      shell: bash

