#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

from argparse import ArgumentParser
from pathlib import Path
import xarray as xr

from diag_fdistribu import compute_deltaf
from gysdata import DiskStore
from plot_utils import anim_field3d


if __name__ == '__main__':
    parser = ArgumentParser(
        description="Plots the difference between the distribution
        function and equilibrium")
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('-o', '--output',
                        action='store',
                        default=None,
                        type=Path,
                        help='output file to generate',
                        metavar='OUTFILE')
    parser.add_argument('-s', '--start',
                        action='store',
                        default=0,
                        type=int,
                        help='start time index')
    parser.add_argument('-e', '--end',
                        action='store',
                        default=None,
                        type=int,
                        help='end time index')
    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)

    # Compute the diag
    species_id = 0
    diff = compute_deltaf(
        ds['fdistribu_eq'].isel(species=species_id),
        ds['fdistribu'].isel(species=species_id, time=slice(args.start, args.end))
        )

    # Generate the output
    if args.output is None:
        out_file = Path.cwd() / f'{diff.name}.gif'
    else:
        out_file = Path(args.output)
    anim_field3d(diff, out_file=out_file, scale='')
