#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import os

from argparse import ArgumentParser
from pathlib import Path

import diag_efield as diage
import diag_fdistribu as diagf
from gysdata import DiskStore


if __name__ == '__main__':
    parser = ArgumentParser(
        description="Plots the distribution function")
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    fdistribu = ds['fdistribu']
    basename = os.path.basename(args.data_dir)
    time_diag = fdistribu.coords["time"].values[args.itime]
    output_filename = Path.cwd() / (f'{basename}_fdistribu_t{time_diag}.png')
    diagf.plot_fdistribu_atonetime(fdistribu, args.itime, output_filename)
    output_filename = Path.cwd() / (f'{basename}_epot_t{time_diag}.png')
    diage.plot_epot_atonetime(ds['electrostatic_potential'], args.itime, output_filename)
