Mesh:
  r_size: 128
  p_size: 256
  r_min: 0.0
  r_minus: 0.45
  r_plus: 0.50
  r_max: 1.0 

Time:
  delta_t: 0.1
  final_T: 70.
  
Perturbation:
  charge_Q: 0
  l_mode: 9 
  eps: 0.0001
  
Output:
  time_step_diag: 10
