SplineMesh:
  r_ncells: 128
  r_min: 0.0
  r_max: 1.0 
  p_ncells: 256
  p_min: 0.0
  p_max: 6.283185307179586

Time:
  delta_t: 0.1
  final_T: 70.
  
Perturbation:
  charge_Q: 0
  l_mode: 9 
  eps: 0.0001
  r_min: 0.45
  r_max: 0.50
  
Output:
  time_step_diag: 10
