name: "Run tests"

runs:
  using: "composite"
  steps:
    - name: "Run tests"
      run: |
        ctest -j 2 --timeout 5 --output-junit tests.xml --output-on-failure
      shell: bash
      working-directory: ./build
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: './build/tests.xml'
