name: "Run tests"

runs:
  using: "composite"
  steps:
    - name: "Run tests"
      run: |
        ctest -j 2 --timeout 5 --output-junit tests.xml
      shell: bash
      working-directory:
        ./build
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: './build/test.xml'
