name: "Filter tests"

inputs:
  base_sha:
    description: "The SHA of the PR base"
    required: true

runs:
  using: "composite"
  steps:
  - name: "Get changed files"
    run: |
      git config --global --add safe.directory $(pwd)
      git fetch --no-recurse-submodules origin ${{ inputs.base_sha }}
      git diff --name-only ${{ inputs.base_sha }} > changed_files.txt  
    shell: bash
  - name: "Check filters"
    run: |
      FOUND_SLL=$(grep "vendor/sll/.*" -x changed_files.txt || true)
      if [ -z "$FOUND_SLL" ]; then echo "SLL_BUILD_TESTING=OFF" >> $GITHUB_ENV; else echo "SLL_BUILD_TESTING=ON" >> $GITHUB_ENV; fi
      FOUND_POISSON_2D=$(grep "src/geometryRTheta/poisson/.*" -x changed_files.txt || true)
      if [ -z "$FOUND_POISSON_2D" ]; then echo "POISSON_2D_BUILD_TESTING=OFF" >> $GITHUB_ENV; else echo "POISSON_2D_BUILD_TESTING=ON" >> $GITHUB_ENV; fi
      FOUND_DDC=$(grep "vendor/ddc" changed_files.txt || true)
      if [ -z "$FOUND_DDC" ]; then echo "DDC_BUILD_TESTING=OFF" >> $GITHUB_ENV; else echo "DDC_BUILD_TESTING=ON" >> $GITHUB_ENV; fi
    shell: bash

