SplineMesh:
  x_min: 0.0
  x_max: 12.56637061435917
  x_ncells: 256
  y_min: 0.0
  y_max: 6.2831853071795864770
  y_ncells : 128

PerturbationInfo:
  perturb_amplitude: 0.015

Algorithm:
  delta_t: 0.05
  final_time: 30

Output:
  nbstep_diag: 4