#!/usr/bin/env python3

# SPDX-License-Identifier: MIT
"""Plot neutral density
"""

from argparse import ArgumentParser
from pathlib import Path

from gysdata import DiskStore
from plot_utils import plot_field1d, plot_field2d

if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the density of neutrals')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    path_data_structure = Path('data_structure_neutral.yaml')
    ds = DiskStore(args.data_dir, data_structure=path_data_structure)
    fluid_moments = ds['fluid_moments']

    current_nspecies = 'neutrals'
    moment_order = 'density'

    # Neutral density
    density_n = fluid_moments.sel(speciesn=current_nspecies, moment=moment_order)
    density_n = density_n.chunk({'time': len(density_n['time'])})

    time_init = fluid_moments.coords['time'].values[0]
    time_diag = fluid_moments.coords['time'].values[args.itime]
    time_values = density_n.coords['time'].values
    dt = time_values[1] - time_values[0]
    title = f'density {current_nspecies}, t={time_diag}, dt={dt}'

    output_filename = Path.cwd() / f'density_{current_nspecies}_xt_dt{dt}.png'
    plot_field2d(density_n,
                 title,
                 output_filename,
                 scale='linear',
                 cmap='viridis')

    data_dict = {f'$t={time_init}$': density_n.sel(time=time_init),
                 f'$t={time_diag}$': density_n.sel(time=time_diag)}

    output_filename = Path.cwd() / f'density_{current_nspecies}_t{time_diag}_dt{dt}.png'
    plot_field1d(data_dict, title, output_filename)
