# Deactivate slow tests if requested
if (DEFINED ENV{GYSELALIBXX_POISSON_2D_BUILD_TESTING})
    set(GYSELALIBXX_POISSON_2D_BUILD_TESTING $ENV{GYSELALIBXX_POISSON_2D_BUILD_TESTING})
endif()

# CTest flags
set(CTEST_OUTPUT_ON_FAILURE ON)
