spack:
  definitions:
  - packages:
    - cmake
    - 'ddc@0.14 +fft +pdi +splines'
    - ginkgo@1.9 ~openmp +rocm amdgpu_target=gfx90a
    - gmgpolar@2.3
    - googletest +gmock
    - kokkos@4.7 ~openmp +rocm amdgpu_target=gfx90a
    - kokkos-kernels@4.7 ~shared
    - kokkos-tools@git.3d33d0a783c5321d6981b3b4e43d3c157d2ca887=develop
    - 'koliop@0.1.2:0.1'
    - lapack
    - mpi
    - ninja
    - paraconf
    - pdi@1.10.1:1
    - pdiplugin-decl-hdf5 +mpi
    - pdiplugin-decl-netcdf +mpi
    - pdiplugin-mpi
    - pdiplugin-pycall
    - pdiplugin-set-value
    - pdiplugin-trace
    - 'python@3.13'

    - py-dask
    - py-h5py
    - py-imageio
    - py-matplotlib
    - py-netcdf4 +mpi
    - py-numpy
    - py-pyyaml
    - py-scipy
    - py-sympy
    - py-xarray
  - architectures:
    - target=x86_64_v3
  specs:
  - gcc # NOTE: not in the matrix to avoid unification issues when the packages target arch is not the arch the compiler was compiled for.
  - matrix:
    - [$packages]
    - [$architectures]
  repos:
    patches:
      git: https://github.com/etiennemlb/gysela-spack.git
      branch: releases/v2026.03_lumi_tmp
    builtin:
      tag: v2025.11.0
  concretizer:
    unify: true
    reuse: false
    duplicates:
      strategy: none
  packages:
    all:
      permissions:
        read: world
        write: group
      variants: ~fortran ~mpi
    c:
      require: gcc@14.2
    cxx:
      require: gcc@14.2
    kokkos-fft:
      require: 'host_backend=fftw-serial'
    lapack:
      require: openblas
    mpi:
      require: cray-mpich
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
  modules:
    default:
      roots: {}
      enable: []
  view: false
