name: "Check which files have been changed"

runs:
  using: "composite"
  steps:
    - run: |
        git config --global --add safe.directory $(pwd)
        git fetch --no-recurse-submodules origin ${CHANGES_REF}
        git diff --name-only ${CHANGES_REF} > changed_files.txt
      shell: bash
