name: "Check which files have been changed"

runs:
  using: "composite"
  steps:
    - run: |
        git fetch --no-recurse-submodules origin ${CHANGES_REF}
        if [[ -n "$(git branch -r --list origin/${CHANGES_REF})" ]]
        then
          REF=$(git log -1 --format=%H origin/${CHANGES_REF})
        else
          REF=${CHANGES_REF}
        fi

        git config --global --add safe.directory $(pwd)
        git diff --name-only ${REF} > changed_files.txt
        cat changed_files.txt
      shell: bash
    - if: github.event_name == 'push'
      run: |
        git config --global --add safe.directory $(pwd)
        git show ${{ github.sha }} --name-only --pretty= > changed_files.txt
      shell: bash
