name: "Check which files have been changed"

runs:
  using: "composite"
  steps:
    - if: github.event_name == 'pull_request'
      run: |
        gh pr diff ${{ github.event.pull_request.number }} --name-only > changed_files.txt
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - if: github.event_name == 'merge_group'
      run: |
        git diff --name-only origin/devel > changed_files.txt
      shell: bash
    - if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
      run: |
        git show ${{ github.sha }} --name-only --pretty= > changed_files.txt
      shell: bash
