var dir_7974be65ea6ed963c26698ca8e6c9478 =
[
    [ "deprecated", "dir_84955663f9d24b90d62bd695016ef2f6.html", "dir_84955663f9d24b90d62bd695016ef2f6" ],
    [ "mapping", "dir_8563757934f61fa3b133ea79518635d1.html", "dir_8563757934f61fa3b133ea79518635d1" ],
    [ "bernstein.hpp", "bernstein_8hpp_source.html", null ],
    [ "bspline.hpp", "bspline_8hpp_source.html", null ],
    [ "bsplines_non_uniform.hpp", "bsplines__non__uniform_8hpp_source.html", null ],
    [ "bsplines_uniform.hpp", "bsplines__uniform_8hpp_source.html", null ],
    [ "constant_extrapolation_boundary_value.hpp", "constant__extrapolation__boundary__value_8hpp_source.html", null ],
    [ "gauss_legendre_integration.hpp", "gauss__legendre__integration_8hpp_source.html", null ],
    [ "greville_interpolation_points.hpp", "greville__interpolation__points_8hpp_source.html", null ],
    [ "knots_as_interpolation_points.hpp", "knots__as__interpolation__points_8hpp_source.html", null ],
    [ "math_tools.hpp", "math__tools_8hpp_source.html", null ],
    [ "matrix.hpp", "matrix_8hpp_source.html", null ],
    [ "matrix_banded.hpp", "matrix__banded_8hpp_source.html", null ],
    [ "matrix_center_block.hpp", "matrix__center__block_8hpp_source.html", null ],
    [ "matrix_corner_block.hpp", "matrix__corner__block_8hpp_source.html", null ],
    [ "matrix_dense.hpp", "matrix__dense_8hpp_source.html", null ],
    [ "matrix_pds_tridiag.hpp", "matrix__pds__tridiag_8hpp_source.html", null ],
    [ "matrix_periodic_banded.hpp", "matrix__periodic__banded_8hpp_source.html", null ],
    [ "null_boundary_value.hpp", "null__boundary__value_8hpp_source.html", null ],
    [ "polar_bsplines.hpp", "polar__bsplines_8hpp_source.html", null ],
    [ "polar_spline.hpp", "polar__spline_8hpp_source.html", null ],
    [ "polar_spline_evaluator.hpp", "polar__spline__evaluator_8hpp_source.html", null ],
    [ "spline_boundary_conditions.hpp", "spline__boundary__conditions_8hpp_source.html", null ],
    [ "spline_boundary_value.hpp", "spline__boundary__value_8hpp_source.html", null ],
    [ "spline_builder.hpp", "spline__builder_8hpp_source.html", null ],
    [ "spline_builder_2d.hpp", "spline__builder__2d_8hpp_source.html", null ],
    [ "spline_evaluator.hpp", "spline__evaluator_8hpp_source.html", null ],
    [ "spline_evaluator_2d.hpp", "spline__evaluator__2d_8hpp_source.html", null ],
    [ "view.hpp", "view_8hpp_source.html", null ]
];