#!/bin/bash

# -----------------------------------------------------------------
# script used for submit gysela5D job
# -----------------------------------------------------------------
arg=$#

if [ $# -lt 2 ]; then
    echo " Syntaxe:  subgys DATA_filename nnodes"
fi

INPUTYAML=$1
((NNODES="$2"))
((MAXIMUM_RANK_PER_NODE=8))
((NTHREADS=48))

# data name
# ---------
DATANAME=${INPUTYAML}
echo "DATANAME= ${DATANAME}"

# case name
# ---------
CASENAME=`basename ${DATANAME} .yaml | tr '[:lower:]' '[:upper:]'`
MACHNAME=`echo $ARCH | tr '[:lower:]' '[:upper:]'`

CASE=D$(echo ${MACHNAME} | sed -r -e "s/([A-Z])[A-Z]*/\\1/g" -e "s/_//g")_${CASENAME}_GENOA_N${NNODES}
echo "CASE = ${CASE}"


# job parameters
# --------------
# time in seconds format
TIMEH="01:00:00"
TIME=$(echo $TIMEH |awk -F: '{print 3600*$1+60*$2+$3}')
# job Name
JOBNAME='Landau4D'
STATUSOK=0


# Environment
# -----------
DIR=$(basename $(dirname $PWD))
exec_file="/lus/work/CT5/gen2224/gdgirard/gyselalibxx_github/build-genoa/simulations/geometryXYVxVy/landau/landau4d_fft"
go_file_cmd="go_"$DATANAME"_genoa_nodes"$NNODES".cmd"

HOMEDIR="$(readlink -f "$(dirname "$0")/..")"
WKDIR=${HOMEDIR}/wk
RESDIR1=${SCRATCHDIR}/${DIR}
echo "DIR = ${DIR}"
echo "HOMEDIR = ${HOMEDIR}"
echo "WKDIR = ${WKDIR}"
echo "RESDIR1 = ${RESDIR1}"

# Creation of the work directory
# ------------------------------
if [ ! -d ${RESDIR1} ]
then
    mkdir -p ${RESDIR1}
fi
RESDIR=${RESDIR1}/${CASE}
if [ ! -d ${RESDIR} ]; then
    mkdir -p ${RESDIR}
    ln -s ${RESDIR} ${CASE}
fi
echo "RESDIR = ${RESDIR}"

# Batch control
# -------------

((THREAD_PER_NODE=384))
if ((NTHREAD > (THREAD_PER_NODE/MAXIMUM_RANK_PER_NODE))); then
    echo "Oversubscribing threads is not supported."
    exit 1
fi


PROFILE_COMMAND=""
# PROFILE_COMMAND="rocprof --stats"
# PROFILE_COMMAND="rocprof --hip-trace"


CMD_MPIRUN="srun -l --ntasks-per-node=${MAXIMUM_RANK_PER_NODE} --cpus-per-task=${NTHREADS} --threads-per-core=2 -- ${exec_file} ${INPUTYAML} 1>> ${RESDIR}/gyselalibxx.out 2>> ${RESDIR}/gyselalibxx.err"

CMD_SUB="sbatch ${go_file_cmd}"


cat <<EOF > ${go_file_cmd}
#!/bin/bash
#SBATCH --account="${ACTIVE_PROJECT}"
#SBATCH --job-name="${JOBNAME}"
#SBATCH --constraint=GENOA
#SBATCH --nodes=${NNODES}
#SBATCH --exclusive
#SBATCH --time=${TIMEH}
#SBATCH -o $JOBNAME.o.%j.out
#SBATCH -e $JOBNAME.e.%j.out
set -eu
ulimit -s unlimited
ulimit -c 0

source  ${HOMEDIR}/toolchains/genoa.gcc.adastra.spack/environment.sh

export KOKKOS_TOOLS_LIBS=$WORKDIR/kokkos-tools/install/lib64/libkp_kernel_timer.so
export OMP_DISPLAY_AFFINITY=TRUE
export OMP_PROC_BIND=CLOSE
export OMP_PLACES=THREADS
export OMP_NUM_THREADS=${NTHREADS}
set +v

EOF

cat <<EOF >> ${go_file_cmd}
cp ${INPUTYAML} ${RESDIR}
cd ${RESDIR}
${CMD_MPIRUN}
EOF

#VG#printf " #Watch your job with:\n  squeue -u \$USER\n" 
#VG#printf " #Delete your job with:\n scancel Job_ID\n" 

# --------------------------------------------------------------------- 
# Launch submission
# -----------------------------------------------------------------
chmod +x ${go_file_cmd}
cd ${WKDIR}
echo " ... ${CMD_SUB}"
${CMD_SUB}
