name: Functionality tests
inputs:
  additional_cmake_commands:
    description: 'Any additional commands/flags which should be passed to cmake'
    required: false
    default: ''
  ctest_commands:
    description: 'Any additional commands/flags which should be passed to ctest'
    required: false
    default: ''
  SLL_BUILD_TESTING:
    description: 'Indicate whether the SLL build should be tested'
    required: true
  POISSON_2D_TESTING:
    description: 'Indicate whether the Poisson 2D should be tested'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup'
      run:
        mkdir build
      shell: bash
    - name: 'CMake call'
      run: |
        cmake ${{ inputs.additional_cmake_commands }} \
            -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
            -DSLL_SPLINES_TEST_DEGREE_MIN=1 -DSLL_SPLINES_TEST_DEGREE_MAX=7 \
            -DSLL_BUILD_TESTING=${{ inputs.SLL_BUILD_TESTING }} \
            -DPOISSON_2D_BUILD_TESTING=${{ inputs.POISSON_2D_TESTING }}
      shell: bash
    - name: 'Compilation'
      run: |
        make -j VERBOSE=1
    - name: 'Run tests'
      run: |
        ctest --output-on-failure --timeout 5 --output-junit tests.xml ${{ inputs.ctest_commands }}
