spack:
  definitions:
  - packages:
    - 'cmake@3.31'
    - 'ddc@0.12 +fft +pdi +splines'
    - 'ginkgo@1.9 +openmp'
    - 'googletest@1.17 +gmock'
    - 'kokkos@4.6:4 +openmp'
    - 'kokkos-kernels@4.6:4'
    - 'kokkos-tools@git.e222e7b6cc7faae5d096e3520d95ca832fb9f889'
    - 'koliop@0.1.2:0.1'
    - 'lapack'
    - 'mpi'
    - 'ninja@1.13'
    - 'paraconf@1.0'
    - 'pdi@1.10.1:1.10'
    - 'pdiplugin-decl-hdf5@1.10 +mpi'
    - 'pdiplugin-decl-netcdf@1.10 +mpi'
    - 'pdiplugin-mpi@1.10'
    - 'pdiplugin-pycall@1.10'
    - 'pdiplugin-set-value@1.10'
    - 'pdiplugin-trace@1.10'
    - 'python@3.13'

    - 'py-dask'
    - 'py-h5py'
    - 'py-imageio'
    - 'py-matplotlib'
    - 'py-netcdf4 +mpi'
    - 'py-numpy'
    - 'py-pyyaml'
    - 'py-scipy'
    - 'py-sympy'
    - 'py-xarray'
  specs:
  - matrix:
    - [$packages]
  repos:
    patches:
      git: https://github.com/gyselax/spack.git
      branch: releases/v2025.11
      destination: /data/gyselarunner/patches-2025.11.0
    builtin:
      git: https://github.com/spack/spack-packages.git
      tag: v2025.11.0
      destination: /data/gyselarunner/spack-packages-2025.11.0
  concretizer:
    unify: true
    reuse: false
  view:
    default:
      root: .spack-env/view
      exclude: ['gcc-runtime']
  packages:
    all:
      permissions:
        group: gysela
        read: world
        write: group
      require: ~cuda
      variants: ~fortran ~mpi +openmp cxxstd=17
    c:
      require: gcc@13.2.0
    cxx:
      require: gcc@13.2.0
    gcc:
      externals:
      - spec: gcc@13.2.0 languages:='c,c++,fortran'
        prefix: /Applications/compilers/gcc/13.2.0
        extra_attributes:
          compilers:
            c: /Applications/compilers/gcc/13.2.0/bin/gcc
            cxx: /Applications/compilers/gcc/13.2.0/bin/g++
            fortran: /Applications/compilers/gcc/13.2.0/bin/gfortran
    kokkos-fft:
      require: 'host_backend=fftw-openmp'
    lapack:
      require: openblas
    mpi:
      require: openmpi ~cuda
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
