spack:
  definitions:
  - packages:
    - 'cmake@3.31'
    - 'ddc@0.15 +fft +pdi +splines'
    - 'ginkgo@1.11 +openmp'
    - 'gmgpolar@2.3'
    - 'googletest@1.17 +gmock'
    - 'kokkos@5.1 +openmp'
    - 'kokkos-kernels@5.1'
    - 'kokkos-tools@git.3d33d0a783c5321d6981b3b4e43d3c157d2ca887=develop'
    - 'koliop@0.2'
    - 'lapack'
    - 'mpi'
    - 'ninja@1.13'
    - 'paraconf@1.0'
    - 'pdi@1.11'
    - 'pdiplugin-decl-hdf5@1.11 +mpi'
    - 'pdiplugin-decl-netcdf@1.11 +mpi'
    - 'pdiplugin-mpi@1.11'
    - 'pdiplugin-pycall@1.11'
    - 'pdiplugin-set-value@1.11'
    - 'pdiplugin-trace@1.11'
    - 'python@3.14'

    - 'py-dask'
    - 'py-h5py'
    - 'py-imageio'
    - 'py-matplotlib'
    - 'py-netcdf4 +mpi'
    - 'py-numpy'
    - 'py-pyyaml'
    - 'py-scipy'
    - 'py-sympy'
    - 'py-xarray'
  specs:
  - matrix:
    - [$packages]
  repos:
    patches:
      git: https://github.com/gyselax/spack.git
      branch: releases/v2026.06
    builtin:
      branch: releases/v2026.06
  concretizer:
    unify: true
  view:
    default:
      root: .spack-env/view
      exclude: ['gcc-runtime']
  packages:
    all:
      permissions:
        read: world
        write: group
      require: ~cuda
      variants: ~fortran ~mpi +openmp
    c:
      require: gcc@13
    cxx:
      require: gcc@13
    kokkos-fft:
      require: 'host_backend=fftw-openmp'
    lapack:
      require: openblas@0.3
    mpi:
      require: openmpi@5.0 ~cuda
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
