spack:
  definitions:
  - packages:
    - 'cmake@3.31'
    - 'ddc@0.15 +fft +pdi +splines'
    - 'ginkgo@1.11 +cuda cuda_arch=70 +openmp'
    - 'gmgpolar@2.3'
    - 'googletest@1.17 +gmock'
    - 'kokkos@5.1 ~shared +wrapper +cuda +cuda_constexpr cuda_arch=70 +openmp'
    - 'kokkos-kernels@5.1 ~shared'
    - 'kokkos-tools@git.3d33d0a783c5321d6981b3b4e43d3c157d2ca887=develop'
    - 'koliop@0.2'
    - 'lapack'
    - 'mpi'
    - 'ninja@1.13'
    - 'paraconf@1.0'
    - 'pdi@1.11'
    - 'pdiplugin-decl-hdf5@1.11 +mpi'
    - 'pdiplugin-decl-netcdf@1.11 +mpi'
    - 'pdiplugin-mpi@1.11'
    - 'pdiplugin-pycall@1.11'
    - 'pdiplugin-set-value@1.11'
    - 'pdiplugin-trace@1.11'
    - 'python@3.14'

    - 'py-dask@2026.3'
    - 'py-h5py@3.16'
    - 'py-imageio@2.37'
    - 'py-matplotlib@3.11 ^freetype@2.14.1'
    - 'py-netcdf4@1.7 +mpi'
    - 'py-numpy@2.4'
    - 'py-pyyaml@6.0'
    - 'py-scipy@1.17'
    - 'py-sympy@1.14'
    - 'py-xarray@2026.4'
  specs:
  - matrix:
    - [$packages]
  repos:
    patches:
      git: https://github.com/gyselax/spack.git
      branch: releases/v2026.06
    builtin:
      branch: releases/v2026.06
  concretizer:
    unify: true
  view:
    default:
      root: .spack-env/view
      exclude: ['gcc-runtime']
  packages:
    all:
      permissions:
        read: world
        write: group
      variants: ~fortran ~mpi +openmp
    c:
      require: gcc@13
    cxx:
      require: gcc@13
    kokkos-fft:
      require: 'host_backend=fftw-openmp'
    lapack:
      require: openblas@0.3
    mpi:
      require: openmpi@5.0 +cuda
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
