spack:
  definitions:
  - packages:
    - cmake@3.31
    - 'ddc@0.15 +fft +pdi +splines'
    - ginkgo@1.11 ~openmp +cuda cuda_arch=80
    - gmgpolar@2.3
    - googletest@1.17 +gmock
    - kokkos@5.1 ~openmp +cuda +cuda_constexpr cuda_arch=80
    - kokkos-kernels@5.1 ~shared
    - kokkos-tools@git.3d33d0a783c5321d6981b3b4e43d3c157d2ca887=develop
    - 'koliop@0.2'
    - lapack
    - mpi
    - ninja@1.13
    - paraconf@1.0
    - pdi@1.11
    - pdiplugin-decl-hdf5@1.11 +mpi
    - pdiplugin-decl-netcdf@1.11 +mpi
    - pdiplugin-mpi@1.11
    - pdiplugin-pycall@1.11
    - pdiplugin-set-value@1.11
    - pdiplugin-trace@1.11
    - 'python@3.14'

    - py-dask@2026.3
    - py-h5py@3.16
    - py-imageio@2.37
    - py-matplotlib@3.11
    - py-netcdf4@1.7 +mpi
    - py-numpy@2.4
    - py-pyyaml@6.0
    - py-scipy@1.17
    - py-sympy@1.14
    - py-xarray@2026.4
  - architectures:
    - arch=linux-sles15-icelake
  specs:
  - matrix:
    - [$packages]
    - [$architectures]
  repos:
    patches:
      git: https://github.com/gyselax/spack.git
      branch: releases/v2026.06
    builtin:
      branch: releases/v2026.06
  concretizer:
    unify: true
  packages:
    all:
      permissions:
        read: group
        write: group
      variants: ~fortran ~mpi
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.8.93
        prefix: /mpcdf/soft/SLE_15/packages/x86_64/cuda/12.8.1
    c:
      require: gcc@14.1.0
    cxx:
      require: gcc@14.1.0
    gcc:
      externals:
      - spec: gcc@14.1.0
        prefix: /mpcdf/soft/SLE_15/packages/x86_64/gcc/14.1.0
        extra_attributes:
          compilers:
            c: /mpcdf/soft/SLE_15/packages/x86_64/gcc/14.1.0/bin/gcc
            cxx: /mpcdf/soft/SLE_15/packages/x86_64/gcc/14.1.0/bin/g++
            fortran: /mpcdf/soft/SLE_15/packages/x86_64/gcc/14.1.0/bin/gfortran
    kokkos-fft:
      require: 'host_backend=fftw-serial'
    lapack:
      require: openblas@0.3
    mpi:
      require: openmpi@5.0
    openmpi:
      buildable: false
      externals:
      - spec: openmpi@5.0.9+cuda~java~memchecker~rocm~static~wrapper-rpath fabrics=psm2,ucx schedulers=none
        prefix: /mpcdf/soft/SLE_15/packages/skylake/openmpi_gpu/cuda_12.8-12.8.1-gcc_14-14.1.0/5.0.9
    py-dask:
      prefer: ['~dataframe']
    py-pandas:
      prefer: ['~performance']
  view: false
