#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import os

from argparse import ArgumentParser
from pathlib import Path

from gysdata import DiskStore
from plot_utils import plot_field1d, plot_field2d


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the electrostatic potential')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    data = ds['electrostatic_potential']
    time_init = data.coords['time'].values[0]
    time_diag = data.coords['time'].values[args.itime]

    output_filename = os.path.join(Path.cwd(), 'electrostatic_potential_xt.png')
    plot_field2d(data, '', output_filename, cmap='viridis', scale='linear')

    output_filename = os.path.join(Path.cwd(), f'electrostatic_potential_t{time_diag}.png')
    data_dict = {f't={time_init}': data.sel(time=time_init),
                 f't={time_diag}': data.sel(time=time_diag)}
    plot_field1d(data_dict, 'electrostatic potential', output_filename)
