#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import os

from argparse import ArgumentParser
from pathlib import Path

from gysdata import DiskStore
from plot_utils import plot_field2d


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the distribution function')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    data = ds['fdistribu']
    time_init = data.coords['time'].values[0]
    time_diag = data.coords['time'].values[args.itime]

    for scale in ['linear', 'log']:
        for species in ['ions', 'electrons']:
            for time in [time_init, time_diag]:
                output_filename = os.path.join(Path.cwd(), f'fdistribu_xv_{species}_t{time}_{scale}.png')
                plot_field2d(data.sel(time=time_diag, species=species).T,
                             f't={time}',
                             output_filename,
                             cmap='viridis',
                             scale=scale)
