#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import os

from argparse import ArgumentParser
from pathlib import Path

from gysdata import DiskStore
from plot_utils import plot_field1d, plot_field2d
from math_utils import compute_moment


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the plasma charge density')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    fdistribu = ds['fdistribu']
    charges = ds['fdistribu_charges']

    density = compute_moment(fdistribu, 'v_x', moment_order=0)
    data = density * charges
    data = data.sum('species')

    time_init = fdistribu.coords['time'].values[0]
    time_diag = fdistribu.coords['time'].values[args.itime]
    title = r'charge density $q_e n_e + q_i n_i$'
    output_filename = os.path.join(Path.cwd(), 'charge_density_xt.png')
    plot_field2d(data,
                 title,
                 output_filename,
                 scale='linear',
                 cmap='viridis')

    output_filename = os.path.join(Path.cwd(), f'charge_density_t{time_diag}.png')
    data_dict = {f't={time_init}': data.sel(time=time_init),
                 f't={time_diag}': data.sel(time=time_diag)}
    plot_field1d(data_dict, title, output_filename)
