#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import numpy as np
import os

from argparse import ArgumentParser
from pathlib import Path

from gysdata import DiskStore
from plot_utils import plot_field1d, plot_field2d
from math_utils import second_moment


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Plots the plasma current')
    parser.add_argument('data_dir',
                        action='store',
                        nargs='?',
                        default=Path.cwd(),
                        type=Path,
                        help='location of the results')
    parser.add_argument('--itime',
                        action='store',
                        default=-1,
                        type=int,
                        help='time index')

    args = parser.parse_args()

    # Load data
    ds = DiskStore(args.data_dir)
    fdistribu = ds['fdistribu']
    charges = ds['fdistribu_charges']
    masses = ds['fdistribu_masses']

    particle_flux = second_moment(fdistribu, 'v_x')
    data = particle_flux * charges / np.sqrt(masses)
    data = data.sum('species')

    time_init = fdistribu.coords['time'].values[0]
    time_diag = fdistribu.coords['time'].values[args.itime]
    title = r'current $q_e \Gamma_e / \sqrt{m_e} + q_i \Gamma_i / \sqrt{m_i}$'
    output_filename = os.path.join(Path.cwd(), 'current_xt.png')
    plot_field2d(data,
                 title,
                 output_filename,
                 scale='linear',
                 cmap='viridis')

    output_filename = os.path.join(Path.cwd(), f'current_t{time_diag}.png')
    data_dict = {f't={time_init}': data.sel(time=time_init),
                 f't={time_diag}': data.sel(time=time_diag)}
    plot_field1d(data_dict, title, output_filename)
