name: Check required test result

# Check the status of the PR following the conclusion of a required test
# If any required tests are failing the PR is pub back into draft.
# If all the required tests (except the GPU tests which are very slow)
# are passing then the "Ready to review" label is added to the PR.

on:
  check_run:
    types: completed

jobs:

  set_labels:
    runs-on: ubuntu-latest
    name: Set PR labels
    if: |
      github.repository == 'gyselax/gyselalibxx' && github.event.check_run.pull_requests &&
      (github.event.check_run.conclusion == 'success' || github.event.check_run.conclusion == 'failure')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set PR labels for reviews
        run: |
          pr_number=$(gh pr list --search "${}" --state --json number --jq '.[]["number"]')
          if [[ -n "${pr_number}" ]]
            STATES=$(gh pr checks ${pr_number} --required --json state)
            N_PASSES=$(echo $STATES | grep -o "\"state\":\"SUCCESS\"" | wc -l)
            N_FAILS=$(echo $STATES | grep -o "\"state\":\"FAILURE\"" | wc -l)
            if [[ ${N_FAILS} != 0 ]]
            then
              # If any required tests are failing
              gh pr ready ${{ github.event.pull_request.number }} --undo
            elif [[ ${N_PASSES} >= 10 ]]
            then
              # If all required tests are passing then mark as ready to review
              gh pr edit ${pr_number} --add-label "Ready to review"
            fi
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}

