name: Docker

on:
  workflow_call:
    inputs:
      SHA:
        description: "The SHA of the commit being tested"
        required: true
        type: string
      update_latest:
        description: "Indicate if the latest reference should be updated"
        required: false
        default: false
        type: bool
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to tag
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          tags: ghcr.io/gyselax/gyselalibxx_env:${{ inputs.SHA }}
      - name: Build and push latest
        if: ${{ inputs.update_latest }}
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          tags: ghcr.io/gyselax/gyselalibxx_env:latest

