name: Docker

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to tag
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          tags: ghcr.io/gyselax/gyselalibxx_env:${{ github.sha }}
      - name: Build and push latest
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: ./docker/gyselalibxx_env
          cache-from: type=registry,ref=ghcr.io/gyselax/gyselalibxx_env:latest
          pull: true
          push: true
          tags: ghcr.io/gyselax/gyselalibxx_env:latest

