name: Documentation Generation

on:
  push:
    branches: [ ebourne_doc_setup_test ]

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: code_branch
      - name: Checkout documentation
        uses: actions/checkout@v3
        with:
          ref: documentation
          path: doc_branch
      - name: Generate docs
        run: |
          cd code_branch
          mkdir build
          cd build
          make doc
          cd ../..
        shell: bash
      - name: Update documentation
        run: |
          cd doc_branch
          git rm *
          cp -r ../code_branch/build/docs/html .
          git add .
          git commit -m "Update docs"
          git push
        env:
          GH_TOKEN: ${{ github.token }}
