name: Tag and release new version

on:
  push:
    branches:
    - 'main'

jobs:
  deployVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Get tag name"
        id: tag_name
        run: |
          version=$(cat src/version.txt)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=v${version}" >> $GITHUB_OUTPUT
      - name: "Get release notes"
        id: release_notes
        run: |
          START_LINE=$(grep "^## " CHANGELOG.md -n | head -1 | cut -d: -f -1)
          END_LINE=$(grep "^## " CHANGELOG.md -n | head -2 | tail -1 | cut -d: -f -1)
          START_LINE=$((${START_LINE}+1))
          END_LINE=$((${END_LINE}-1))
          echo "## What's New" > release_notes.md
          sed -n ${START_LINE},${END_LINE}p CHANGELOG.md >> release_notes.md
      - name: "Get contributors"
        run: |
          # Get relevant commits
          CURRENT_RELEASE_COMMIT=$(git log -1 --pretty=%H)

          # Find the PR which created the release
          PR_ID=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /search/issues?q="${CURRENT_RELEASE_COMMIT}" | jq '.["items"][0]["number"]')
          # Extract authors from all commits in the PR
          CONTRIBUTORS=$(gh pr view ${PR_ID} --json commits | jq '.["commits"][]["authors"][]["login"]' | tr -d '"' | sort -u)

          # Add a hidden section listing the user names of all authors on commits in this release
          echo "<details>" >> release_notes.md
          echo "" >> release_notes.md
          echo "## Contributors" >> release_notes.md
          for c in ${CONTRIBUTORS}
          do
            echo "- @$c" >> release_notes.md
          done
          echo "" >> release_notes.md
          echo "</details>" >> release_notes.md

          # Get the full changelog link
          PREVIOUS_TAG=$(gh release list --limit 1 --json tagName | jq '.[]["tagName"]' | tr -d '"')

          echo "" >> release_notes.md
          echo "**Full list of changes**: [${PREVIOUS_TAG}..${tag_name}](https://github.com/gyselax/gyselalibxx/compare/${PREVIOUS_TAG}..${tag_name})" >> release_notes.md

        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
      - name: "Update repo tags"
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ steps.tag_name.outputs.TAG_NAME }}
      - name: "Update releases"
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/gyselax/gyselalibxx/releases \
             -f "tag_name=${tag_name}" -f "name=Version ${version}" -F "body=@release_notes.md" -F "draft=false" -F "prerelease=false" -F "generate_release_notes=false"
        shell: bash
        env:
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          version: ${{ steps.tag_name.outputs.VERSION }}
          release_notes: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          GH_TOKEN: ${{ github.token }}

